FROM lyonmu/quebec:builder-bookworm AS builder

WORKDIR /build

COPY . .

RUN make gateway && chmod +x /build/bin/gateway

FROM busybox:stable-uclibc AS runner

COPY --from=builder /build/bin/gateway /usr/bin/gateway

EXPOSE 59025

ENTRYPOINT [ "/usr/bin/gateway" ]