// Code generated by ent, DO NOT EDIT.

package corecert

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lyonmu/quebec/pkg/constant"
)

const (
	// Label holds the string label denoting the corecert type in the database.
	Label = "core_cert"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSerialNumber holds the string denoting the serial_number field in the database.
	FieldSerialNumber = "serial_number"
	// FieldIssuerCn holds the string denoting the issuer_cn field in the database.
	FieldIssuerCn = "issuer_cn"
	// FieldSubjectCn holds the string denoting the subject_cn field in the database.
	FieldSubjectCn = "subject_cn"
	// FieldNotBefore holds the string denoting the not_before field in the database.
	FieldNotBefore = "not_before"
	// FieldNotAfter holds the string denoting the not_after field in the database.
	FieldNotAfter = "not_after"
	// FieldSecretType holds the string denoting the secret_type field in the database.
	FieldSecretType = "secret_type"
	// FieldCertificateHash holds the string denoting the certificate_hash field in the database.
	FieldCertificateHash = "certificate_hash"
	// FieldCertificate holds the string denoting the certificate field in the database.
	FieldCertificate = "certificate"
	// FieldPrivateKeyHash holds the string denoting the private_key_hash field in the database.
	FieldPrivateKeyHash = "private_key_hash"
	// FieldPrivateKey holds the string denoting the private_key field in the database.
	FieldPrivateKey = "private_key"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldIsDefault holds the string denoting the is_default field in the database.
	FieldIsDefault = "is_default"
	// Table holds the table name of the corecert in the database.
	Table = "quebec_core_cert"
)

// Columns holds all SQL columns for corecert fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldSerialNumber,
	FieldIssuerCn,
	FieldSubjectCn,
	FieldNotBefore,
	FieldNotAfter,
	FieldSecretType,
	FieldCertificateHash,
	FieldCertificate,
	FieldPrivateKeyHash,
	FieldPrivateKey,
	FieldStatus,
	FieldIsDefault,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/lyonmu/quebec/cmd/core/internal/ent/runtime"
var (
	Hooks [2]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultSecretType holds the default value on creation for the "secret_type" field.
	DefaultSecretType constant.CertType
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus constant.YesOrNo
	// DefaultIsDefault holds the default value on creation for the "is_default" field.
	DefaultIsDefault constant.YesOrNo
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the CoreCert queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySerialNumber orders the results by the serial_number field.
func BySerialNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSerialNumber, opts...).ToFunc()
}

// ByIssuerCn orders the results by the issuer_cn field.
func ByIssuerCn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuerCn, opts...).ToFunc()
}

// BySubjectCn orders the results by the subject_cn field.
func BySubjectCn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectCn, opts...).ToFunc()
}

// ByNotBefore orders the results by the not_before field.
func ByNotBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotBefore, opts...).ToFunc()
}

// ByNotAfter orders the results by the not_after field.
func ByNotAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotAfter, opts...).ToFunc()
}

// BySecretType orders the results by the secret_type field.
func BySecretType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretType, opts...).ToFunc()
}

// ByCertificateHash orders the results by the certificate_hash field.
func ByCertificateHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCertificateHash, opts...).ToFunc()
}

// ByCertificate orders the results by the certificate field.
func ByCertificate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCertificate, opts...).ToFunc()
}

// ByPrivateKeyHash orders the results by the private_key_hash field.
func ByPrivateKeyHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrivateKeyHash, opts...).ToFunc()
}

// ByPrivateKey orders the results by the private_key field.
func ByPrivateKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrivateKey, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIsDefault orders the results by the is_default field.
func ByIsDefault(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDefault, opts...).ToFunc()
}
