// Code generated by ent, DO NOT EDIT.

package corecert

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/predicate"
	"github.com/lyonmu/quebec/pkg/constant"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldName, v))
}

// SerialNumber applies equality check predicate on the "serial_number" field. It's identical to SerialNumberEQ.
func SerialNumber(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldSerialNumber, v))
}

// IssuerCn applies equality check predicate on the "issuer_cn" field. It's identical to IssuerCnEQ.
func IssuerCn(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldIssuerCn, v))
}

// SubjectCn applies equality check predicate on the "subject_cn" field. It's identical to SubjectCnEQ.
func SubjectCn(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldSubjectCn, v))
}

// NotBefore applies equality check predicate on the "not_before" field. It's identical to NotBeforeEQ.
func NotBefore(v int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldNotBefore, v))
}

// NotAfter applies equality check predicate on the "not_after" field. It's identical to NotAfterEQ.
func NotAfter(v int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldNotAfter, v))
}

// SecretType applies equality check predicate on the "secret_type" field. It's identical to SecretTypeEQ.
func SecretType(v constant.CertType) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldEQ(FieldSecretType, vc))
}

// CertificateHash applies equality check predicate on the "certificate_hash" field. It's identical to CertificateHashEQ.
func CertificateHash(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldCertificateHash, v))
}

// Certificate applies equality check predicate on the "certificate" field. It's identical to CertificateEQ.
func Certificate(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldCertificate, v))
}

// PrivateKeyHash applies equality check predicate on the "private_key_hash" field. It's identical to PrivateKeyHashEQ.
func PrivateKeyHash(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldPrivateKeyHash, v))
}

// PrivateKey applies equality check predicate on the "private_key" field. It's identical to PrivateKeyEQ.
func PrivateKey(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldPrivateKey, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v constant.YesOrNo) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldEQ(FieldStatus, vc))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v constant.YesOrNo) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldEQ(FieldIsDefault, vc))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContainsFold(FieldName, v))
}

// SerialNumberEQ applies the EQ predicate on the "serial_number" field.
func SerialNumberEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldSerialNumber, v))
}

// SerialNumberNEQ applies the NEQ predicate on the "serial_number" field.
func SerialNumberNEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNEQ(FieldSerialNumber, v))
}

// SerialNumberIn applies the In predicate on the "serial_number" field.
func SerialNumberIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIn(FieldSerialNumber, vs...))
}

// SerialNumberNotIn applies the NotIn predicate on the "serial_number" field.
func SerialNumberNotIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotIn(FieldSerialNumber, vs...))
}

// SerialNumberGT applies the GT predicate on the "serial_number" field.
func SerialNumberGT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGT(FieldSerialNumber, v))
}

// SerialNumberGTE applies the GTE predicate on the "serial_number" field.
func SerialNumberGTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGTE(FieldSerialNumber, v))
}

// SerialNumberLT applies the LT predicate on the "serial_number" field.
func SerialNumberLT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLT(FieldSerialNumber, v))
}

// SerialNumberLTE applies the LTE predicate on the "serial_number" field.
func SerialNumberLTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLTE(FieldSerialNumber, v))
}

// SerialNumberContains applies the Contains predicate on the "serial_number" field.
func SerialNumberContains(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContains(FieldSerialNumber, v))
}

// SerialNumberHasPrefix applies the HasPrefix predicate on the "serial_number" field.
func SerialNumberHasPrefix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasPrefix(FieldSerialNumber, v))
}

// SerialNumberHasSuffix applies the HasSuffix predicate on the "serial_number" field.
func SerialNumberHasSuffix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasSuffix(FieldSerialNumber, v))
}

// SerialNumberIsNil applies the IsNil predicate on the "serial_number" field.
func SerialNumberIsNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIsNull(FieldSerialNumber))
}

// SerialNumberNotNil applies the NotNil predicate on the "serial_number" field.
func SerialNumberNotNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotNull(FieldSerialNumber))
}

// SerialNumberEqualFold applies the EqualFold predicate on the "serial_number" field.
func SerialNumberEqualFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEqualFold(FieldSerialNumber, v))
}

// SerialNumberContainsFold applies the ContainsFold predicate on the "serial_number" field.
func SerialNumberContainsFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContainsFold(FieldSerialNumber, v))
}

// IssuerCnEQ applies the EQ predicate on the "issuer_cn" field.
func IssuerCnEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldIssuerCn, v))
}

// IssuerCnNEQ applies the NEQ predicate on the "issuer_cn" field.
func IssuerCnNEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNEQ(FieldIssuerCn, v))
}

// IssuerCnIn applies the In predicate on the "issuer_cn" field.
func IssuerCnIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIn(FieldIssuerCn, vs...))
}

// IssuerCnNotIn applies the NotIn predicate on the "issuer_cn" field.
func IssuerCnNotIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotIn(FieldIssuerCn, vs...))
}

// IssuerCnGT applies the GT predicate on the "issuer_cn" field.
func IssuerCnGT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGT(FieldIssuerCn, v))
}

// IssuerCnGTE applies the GTE predicate on the "issuer_cn" field.
func IssuerCnGTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGTE(FieldIssuerCn, v))
}

// IssuerCnLT applies the LT predicate on the "issuer_cn" field.
func IssuerCnLT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLT(FieldIssuerCn, v))
}

// IssuerCnLTE applies the LTE predicate on the "issuer_cn" field.
func IssuerCnLTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLTE(FieldIssuerCn, v))
}

// IssuerCnContains applies the Contains predicate on the "issuer_cn" field.
func IssuerCnContains(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContains(FieldIssuerCn, v))
}

// IssuerCnHasPrefix applies the HasPrefix predicate on the "issuer_cn" field.
func IssuerCnHasPrefix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasPrefix(FieldIssuerCn, v))
}

// IssuerCnHasSuffix applies the HasSuffix predicate on the "issuer_cn" field.
func IssuerCnHasSuffix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasSuffix(FieldIssuerCn, v))
}

// IssuerCnIsNil applies the IsNil predicate on the "issuer_cn" field.
func IssuerCnIsNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIsNull(FieldIssuerCn))
}

// IssuerCnNotNil applies the NotNil predicate on the "issuer_cn" field.
func IssuerCnNotNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotNull(FieldIssuerCn))
}

// IssuerCnEqualFold applies the EqualFold predicate on the "issuer_cn" field.
func IssuerCnEqualFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEqualFold(FieldIssuerCn, v))
}

// IssuerCnContainsFold applies the ContainsFold predicate on the "issuer_cn" field.
func IssuerCnContainsFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContainsFold(FieldIssuerCn, v))
}

// SubjectCnEQ applies the EQ predicate on the "subject_cn" field.
func SubjectCnEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldSubjectCn, v))
}

// SubjectCnNEQ applies the NEQ predicate on the "subject_cn" field.
func SubjectCnNEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNEQ(FieldSubjectCn, v))
}

// SubjectCnIn applies the In predicate on the "subject_cn" field.
func SubjectCnIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIn(FieldSubjectCn, vs...))
}

// SubjectCnNotIn applies the NotIn predicate on the "subject_cn" field.
func SubjectCnNotIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotIn(FieldSubjectCn, vs...))
}

// SubjectCnGT applies the GT predicate on the "subject_cn" field.
func SubjectCnGT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGT(FieldSubjectCn, v))
}

// SubjectCnGTE applies the GTE predicate on the "subject_cn" field.
func SubjectCnGTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGTE(FieldSubjectCn, v))
}

// SubjectCnLT applies the LT predicate on the "subject_cn" field.
func SubjectCnLT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLT(FieldSubjectCn, v))
}

// SubjectCnLTE applies the LTE predicate on the "subject_cn" field.
func SubjectCnLTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLTE(FieldSubjectCn, v))
}

// SubjectCnContains applies the Contains predicate on the "subject_cn" field.
func SubjectCnContains(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContains(FieldSubjectCn, v))
}

// SubjectCnHasPrefix applies the HasPrefix predicate on the "subject_cn" field.
func SubjectCnHasPrefix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasPrefix(FieldSubjectCn, v))
}

// SubjectCnHasSuffix applies the HasSuffix predicate on the "subject_cn" field.
func SubjectCnHasSuffix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasSuffix(FieldSubjectCn, v))
}

// SubjectCnIsNil applies the IsNil predicate on the "subject_cn" field.
func SubjectCnIsNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIsNull(FieldSubjectCn))
}

// SubjectCnNotNil applies the NotNil predicate on the "subject_cn" field.
func SubjectCnNotNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotNull(FieldSubjectCn))
}

// SubjectCnEqualFold applies the EqualFold predicate on the "subject_cn" field.
func SubjectCnEqualFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEqualFold(FieldSubjectCn, v))
}

// SubjectCnContainsFold applies the ContainsFold predicate on the "subject_cn" field.
func SubjectCnContainsFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContainsFold(FieldSubjectCn, v))
}

// NotBeforeEQ applies the EQ predicate on the "not_before" field.
func NotBeforeEQ(v int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldNotBefore, v))
}

// NotBeforeNEQ applies the NEQ predicate on the "not_before" field.
func NotBeforeNEQ(v int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNEQ(FieldNotBefore, v))
}

// NotBeforeIn applies the In predicate on the "not_before" field.
func NotBeforeIn(vs ...int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIn(FieldNotBefore, vs...))
}

// NotBeforeNotIn applies the NotIn predicate on the "not_before" field.
func NotBeforeNotIn(vs ...int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotIn(FieldNotBefore, vs...))
}

// NotBeforeGT applies the GT predicate on the "not_before" field.
func NotBeforeGT(v int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGT(FieldNotBefore, v))
}

// NotBeforeGTE applies the GTE predicate on the "not_before" field.
func NotBeforeGTE(v int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGTE(FieldNotBefore, v))
}

// NotBeforeLT applies the LT predicate on the "not_before" field.
func NotBeforeLT(v int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLT(FieldNotBefore, v))
}

// NotBeforeLTE applies the LTE predicate on the "not_before" field.
func NotBeforeLTE(v int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLTE(FieldNotBefore, v))
}

// NotBeforeIsNil applies the IsNil predicate on the "not_before" field.
func NotBeforeIsNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIsNull(FieldNotBefore))
}

// NotBeforeNotNil applies the NotNil predicate on the "not_before" field.
func NotBeforeNotNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotNull(FieldNotBefore))
}

// NotAfterEQ applies the EQ predicate on the "not_after" field.
func NotAfterEQ(v int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldNotAfter, v))
}

// NotAfterNEQ applies the NEQ predicate on the "not_after" field.
func NotAfterNEQ(v int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNEQ(FieldNotAfter, v))
}

// NotAfterIn applies the In predicate on the "not_after" field.
func NotAfterIn(vs ...int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIn(FieldNotAfter, vs...))
}

// NotAfterNotIn applies the NotIn predicate on the "not_after" field.
func NotAfterNotIn(vs ...int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotIn(FieldNotAfter, vs...))
}

// NotAfterGT applies the GT predicate on the "not_after" field.
func NotAfterGT(v int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGT(FieldNotAfter, v))
}

// NotAfterGTE applies the GTE predicate on the "not_after" field.
func NotAfterGTE(v int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGTE(FieldNotAfter, v))
}

// NotAfterLT applies the LT predicate on the "not_after" field.
func NotAfterLT(v int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLT(FieldNotAfter, v))
}

// NotAfterLTE applies the LTE predicate on the "not_after" field.
func NotAfterLTE(v int64) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLTE(FieldNotAfter, v))
}

// NotAfterIsNil applies the IsNil predicate on the "not_after" field.
func NotAfterIsNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIsNull(FieldNotAfter))
}

// NotAfterNotNil applies the NotNil predicate on the "not_after" field.
func NotAfterNotNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotNull(FieldNotAfter))
}

// SecretTypeEQ applies the EQ predicate on the "secret_type" field.
func SecretTypeEQ(v constant.CertType) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldEQ(FieldSecretType, vc))
}

// SecretTypeNEQ applies the NEQ predicate on the "secret_type" field.
func SecretTypeNEQ(v constant.CertType) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldNEQ(FieldSecretType, vc))
}

// SecretTypeIn applies the In predicate on the "secret_type" field.
func SecretTypeIn(vs ...constant.CertType) predicate.CoreCert {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int8(vs[i])
	}
	return predicate.CoreCert(sql.FieldIn(FieldSecretType, v...))
}

// SecretTypeNotIn applies the NotIn predicate on the "secret_type" field.
func SecretTypeNotIn(vs ...constant.CertType) predicate.CoreCert {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int8(vs[i])
	}
	return predicate.CoreCert(sql.FieldNotIn(FieldSecretType, v...))
}

// SecretTypeGT applies the GT predicate on the "secret_type" field.
func SecretTypeGT(v constant.CertType) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldGT(FieldSecretType, vc))
}

// SecretTypeGTE applies the GTE predicate on the "secret_type" field.
func SecretTypeGTE(v constant.CertType) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldGTE(FieldSecretType, vc))
}

// SecretTypeLT applies the LT predicate on the "secret_type" field.
func SecretTypeLT(v constant.CertType) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldLT(FieldSecretType, vc))
}

// SecretTypeLTE applies the LTE predicate on the "secret_type" field.
func SecretTypeLTE(v constant.CertType) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldLTE(FieldSecretType, vc))
}

// SecretTypeIsNil applies the IsNil predicate on the "secret_type" field.
func SecretTypeIsNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIsNull(FieldSecretType))
}

// SecretTypeNotNil applies the NotNil predicate on the "secret_type" field.
func SecretTypeNotNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotNull(FieldSecretType))
}

// CertificateHashEQ applies the EQ predicate on the "certificate_hash" field.
func CertificateHashEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldCertificateHash, v))
}

// CertificateHashNEQ applies the NEQ predicate on the "certificate_hash" field.
func CertificateHashNEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNEQ(FieldCertificateHash, v))
}

// CertificateHashIn applies the In predicate on the "certificate_hash" field.
func CertificateHashIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIn(FieldCertificateHash, vs...))
}

// CertificateHashNotIn applies the NotIn predicate on the "certificate_hash" field.
func CertificateHashNotIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotIn(FieldCertificateHash, vs...))
}

// CertificateHashGT applies the GT predicate on the "certificate_hash" field.
func CertificateHashGT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGT(FieldCertificateHash, v))
}

// CertificateHashGTE applies the GTE predicate on the "certificate_hash" field.
func CertificateHashGTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGTE(FieldCertificateHash, v))
}

// CertificateHashLT applies the LT predicate on the "certificate_hash" field.
func CertificateHashLT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLT(FieldCertificateHash, v))
}

// CertificateHashLTE applies the LTE predicate on the "certificate_hash" field.
func CertificateHashLTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLTE(FieldCertificateHash, v))
}

// CertificateHashContains applies the Contains predicate on the "certificate_hash" field.
func CertificateHashContains(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContains(FieldCertificateHash, v))
}

// CertificateHashHasPrefix applies the HasPrefix predicate on the "certificate_hash" field.
func CertificateHashHasPrefix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasPrefix(FieldCertificateHash, v))
}

// CertificateHashHasSuffix applies the HasSuffix predicate on the "certificate_hash" field.
func CertificateHashHasSuffix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasSuffix(FieldCertificateHash, v))
}

// CertificateHashIsNil applies the IsNil predicate on the "certificate_hash" field.
func CertificateHashIsNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIsNull(FieldCertificateHash))
}

// CertificateHashNotNil applies the NotNil predicate on the "certificate_hash" field.
func CertificateHashNotNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotNull(FieldCertificateHash))
}

// CertificateHashEqualFold applies the EqualFold predicate on the "certificate_hash" field.
func CertificateHashEqualFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEqualFold(FieldCertificateHash, v))
}

// CertificateHashContainsFold applies the ContainsFold predicate on the "certificate_hash" field.
func CertificateHashContainsFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContainsFold(FieldCertificateHash, v))
}

// CertificateEQ applies the EQ predicate on the "certificate" field.
func CertificateEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldCertificate, v))
}

// CertificateNEQ applies the NEQ predicate on the "certificate" field.
func CertificateNEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNEQ(FieldCertificate, v))
}

// CertificateIn applies the In predicate on the "certificate" field.
func CertificateIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIn(FieldCertificate, vs...))
}

// CertificateNotIn applies the NotIn predicate on the "certificate" field.
func CertificateNotIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotIn(FieldCertificate, vs...))
}

// CertificateGT applies the GT predicate on the "certificate" field.
func CertificateGT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGT(FieldCertificate, v))
}

// CertificateGTE applies the GTE predicate on the "certificate" field.
func CertificateGTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGTE(FieldCertificate, v))
}

// CertificateLT applies the LT predicate on the "certificate" field.
func CertificateLT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLT(FieldCertificate, v))
}

// CertificateLTE applies the LTE predicate on the "certificate" field.
func CertificateLTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLTE(FieldCertificate, v))
}

// CertificateContains applies the Contains predicate on the "certificate" field.
func CertificateContains(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContains(FieldCertificate, v))
}

// CertificateHasPrefix applies the HasPrefix predicate on the "certificate" field.
func CertificateHasPrefix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasPrefix(FieldCertificate, v))
}

// CertificateHasSuffix applies the HasSuffix predicate on the "certificate" field.
func CertificateHasSuffix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasSuffix(FieldCertificate, v))
}

// CertificateIsNil applies the IsNil predicate on the "certificate" field.
func CertificateIsNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIsNull(FieldCertificate))
}

// CertificateNotNil applies the NotNil predicate on the "certificate" field.
func CertificateNotNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotNull(FieldCertificate))
}

// CertificateEqualFold applies the EqualFold predicate on the "certificate" field.
func CertificateEqualFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEqualFold(FieldCertificate, v))
}

// CertificateContainsFold applies the ContainsFold predicate on the "certificate" field.
func CertificateContainsFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContainsFold(FieldCertificate, v))
}

// PrivateKeyHashEQ applies the EQ predicate on the "private_key_hash" field.
func PrivateKeyHashEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldPrivateKeyHash, v))
}

// PrivateKeyHashNEQ applies the NEQ predicate on the "private_key_hash" field.
func PrivateKeyHashNEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNEQ(FieldPrivateKeyHash, v))
}

// PrivateKeyHashIn applies the In predicate on the "private_key_hash" field.
func PrivateKeyHashIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIn(FieldPrivateKeyHash, vs...))
}

// PrivateKeyHashNotIn applies the NotIn predicate on the "private_key_hash" field.
func PrivateKeyHashNotIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotIn(FieldPrivateKeyHash, vs...))
}

// PrivateKeyHashGT applies the GT predicate on the "private_key_hash" field.
func PrivateKeyHashGT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGT(FieldPrivateKeyHash, v))
}

// PrivateKeyHashGTE applies the GTE predicate on the "private_key_hash" field.
func PrivateKeyHashGTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGTE(FieldPrivateKeyHash, v))
}

// PrivateKeyHashLT applies the LT predicate on the "private_key_hash" field.
func PrivateKeyHashLT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLT(FieldPrivateKeyHash, v))
}

// PrivateKeyHashLTE applies the LTE predicate on the "private_key_hash" field.
func PrivateKeyHashLTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLTE(FieldPrivateKeyHash, v))
}

// PrivateKeyHashContains applies the Contains predicate on the "private_key_hash" field.
func PrivateKeyHashContains(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContains(FieldPrivateKeyHash, v))
}

// PrivateKeyHashHasPrefix applies the HasPrefix predicate on the "private_key_hash" field.
func PrivateKeyHashHasPrefix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasPrefix(FieldPrivateKeyHash, v))
}

// PrivateKeyHashHasSuffix applies the HasSuffix predicate on the "private_key_hash" field.
func PrivateKeyHashHasSuffix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasSuffix(FieldPrivateKeyHash, v))
}

// PrivateKeyHashIsNil applies the IsNil predicate on the "private_key_hash" field.
func PrivateKeyHashIsNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIsNull(FieldPrivateKeyHash))
}

// PrivateKeyHashNotNil applies the NotNil predicate on the "private_key_hash" field.
func PrivateKeyHashNotNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotNull(FieldPrivateKeyHash))
}

// PrivateKeyHashEqualFold applies the EqualFold predicate on the "private_key_hash" field.
func PrivateKeyHashEqualFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEqualFold(FieldPrivateKeyHash, v))
}

// PrivateKeyHashContainsFold applies the ContainsFold predicate on the "private_key_hash" field.
func PrivateKeyHashContainsFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContainsFold(FieldPrivateKeyHash, v))
}

// PrivateKeyEQ applies the EQ predicate on the "private_key" field.
func PrivateKeyEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEQ(FieldPrivateKey, v))
}

// PrivateKeyNEQ applies the NEQ predicate on the "private_key" field.
func PrivateKeyNEQ(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNEQ(FieldPrivateKey, v))
}

// PrivateKeyIn applies the In predicate on the "private_key" field.
func PrivateKeyIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIn(FieldPrivateKey, vs...))
}

// PrivateKeyNotIn applies the NotIn predicate on the "private_key" field.
func PrivateKeyNotIn(vs ...string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotIn(FieldPrivateKey, vs...))
}

// PrivateKeyGT applies the GT predicate on the "private_key" field.
func PrivateKeyGT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGT(FieldPrivateKey, v))
}

// PrivateKeyGTE applies the GTE predicate on the "private_key" field.
func PrivateKeyGTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldGTE(FieldPrivateKey, v))
}

// PrivateKeyLT applies the LT predicate on the "private_key" field.
func PrivateKeyLT(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLT(FieldPrivateKey, v))
}

// PrivateKeyLTE applies the LTE predicate on the "private_key" field.
func PrivateKeyLTE(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldLTE(FieldPrivateKey, v))
}

// PrivateKeyContains applies the Contains predicate on the "private_key" field.
func PrivateKeyContains(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContains(FieldPrivateKey, v))
}

// PrivateKeyHasPrefix applies the HasPrefix predicate on the "private_key" field.
func PrivateKeyHasPrefix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasPrefix(FieldPrivateKey, v))
}

// PrivateKeyHasSuffix applies the HasSuffix predicate on the "private_key" field.
func PrivateKeyHasSuffix(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldHasSuffix(FieldPrivateKey, v))
}

// PrivateKeyIsNil applies the IsNil predicate on the "private_key" field.
func PrivateKeyIsNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIsNull(FieldPrivateKey))
}

// PrivateKeyNotNil applies the NotNil predicate on the "private_key" field.
func PrivateKeyNotNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotNull(FieldPrivateKey))
}

// PrivateKeyEqualFold applies the EqualFold predicate on the "private_key" field.
func PrivateKeyEqualFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldEqualFold(FieldPrivateKey, v))
}

// PrivateKeyContainsFold applies the ContainsFold predicate on the "private_key" field.
func PrivateKeyContainsFold(v string) predicate.CoreCert {
	return predicate.CoreCert(sql.FieldContainsFold(FieldPrivateKey, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v constant.YesOrNo) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v constant.YesOrNo) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...constant.YesOrNo) predicate.CoreCert {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int8(vs[i])
	}
	return predicate.CoreCert(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...constant.YesOrNo) predicate.CoreCert {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int8(vs[i])
	}
	return predicate.CoreCert(sql.FieldNotIn(FieldStatus, v...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v constant.YesOrNo) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldGT(FieldStatus, vc))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v constant.YesOrNo) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldGTE(FieldStatus, vc))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v constant.YesOrNo) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldLT(FieldStatus, vc))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v constant.YesOrNo) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldLTE(FieldStatus, vc))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotNull(FieldStatus))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v constant.YesOrNo) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldEQ(FieldIsDefault, vc))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v constant.YesOrNo) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldNEQ(FieldIsDefault, vc))
}

// IsDefaultIn applies the In predicate on the "is_default" field.
func IsDefaultIn(vs ...constant.YesOrNo) predicate.CoreCert {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int8(vs[i])
	}
	return predicate.CoreCert(sql.FieldIn(FieldIsDefault, v...))
}

// IsDefaultNotIn applies the NotIn predicate on the "is_default" field.
func IsDefaultNotIn(vs ...constant.YesOrNo) predicate.CoreCert {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int8(vs[i])
	}
	return predicate.CoreCert(sql.FieldNotIn(FieldIsDefault, v...))
}

// IsDefaultGT applies the GT predicate on the "is_default" field.
func IsDefaultGT(v constant.YesOrNo) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldGT(FieldIsDefault, vc))
}

// IsDefaultGTE applies the GTE predicate on the "is_default" field.
func IsDefaultGTE(v constant.YesOrNo) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldGTE(FieldIsDefault, vc))
}

// IsDefaultLT applies the LT predicate on the "is_default" field.
func IsDefaultLT(v constant.YesOrNo) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldLT(FieldIsDefault, vc))
}

// IsDefaultLTE applies the LTE predicate on the "is_default" field.
func IsDefaultLTE(v constant.YesOrNo) predicate.CoreCert {
	vc := int8(v)
	return predicate.CoreCert(sql.FieldLTE(FieldIsDefault, vc))
}

// IsDefaultIsNil applies the IsNil predicate on the "is_default" field.
func IsDefaultIsNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldIsNull(FieldIsDefault))
}

// IsDefaultNotNil applies the NotNil predicate on the "is_default" field.
func IsDefaultNotNil() predicate.CoreCert {
	return predicate.CoreCert(sql.FieldNotNull(FieldIsDefault))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CoreCert) predicate.CoreCert {
	return predicate.CoreCert(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CoreCert) predicate.CoreCert {
	return predicate.CoreCert(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CoreCert) predicate.CoreCert {
	return predicate.CoreCert(sql.NotPredicates(p))
}
