// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coregatewayhttproute"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/predicate"
	"github.com/lyonmu/quebec/pkg/constant"
)

// CoreGatewayHttpRouteUpdate is the builder for updating CoreGatewayHttpRoute entities.
type CoreGatewayHttpRouteUpdate struct {
	config
	hooks     []Hook
	mutation  *CoreGatewayHttpRouteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CoreGatewayHttpRouteUpdate builder.
func (_u *CoreGatewayHttpRouteUpdate) Where(ps ...predicate.CoreGatewayHttpRoute) *CoreGatewayHttpRouteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CoreGatewayHttpRouteUpdate) SetUpdatedAt(v time.Time) *CoreGatewayHttpRouteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CoreGatewayHttpRouteUpdate) SetDeletedAt(v time.Time) *CoreGatewayHttpRouteUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdate) SetNillableDeletedAt(v *time.Time) *CoreGatewayHttpRouteUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CoreGatewayHttpRouteUpdate) ClearDeletedAt() *CoreGatewayHttpRouteUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *CoreGatewayHttpRouteUpdate) SetName(v string) *CoreGatewayHttpRouteUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdate) SetNillableName(v *string) *CoreGatewayHttpRouteUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *CoreGatewayHttpRouteUpdate) ClearName() *CoreGatewayHttpRouteUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *CoreGatewayHttpRouteUpdate) SetDescription(v string) *CoreGatewayHttpRouteUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdate) SetNillableDescription(v *string) *CoreGatewayHttpRouteUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CoreGatewayHttpRouteUpdate) ClearDescription() *CoreGatewayHttpRouteUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetMatchType sets the "match_type" field.
func (_u *CoreGatewayHttpRouteUpdate) SetMatchType(v constant.ProxyHttpRouteMatchType) *CoreGatewayHttpRouteUpdate {
	_u.mutation.ResetMatchType()
	_u.mutation.SetMatchType(v)
	return _u
}

// SetNillableMatchType sets the "match_type" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdate) SetNillableMatchType(v *constant.ProxyHttpRouteMatchType) *CoreGatewayHttpRouteUpdate {
	if v != nil {
		_u.SetMatchType(*v)
	}
	return _u
}

// AddMatchType adds value to the "match_type" field.
func (_u *CoreGatewayHttpRouteUpdate) AddMatchType(v constant.ProxyHttpRouteMatchType) *CoreGatewayHttpRouteUpdate {
	_u.mutation.AddMatchType(v)
	return _u
}

// ClearMatchType clears the value of the "match_type" field.
func (_u *CoreGatewayHttpRouteUpdate) ClearMatchType() *CoreGatewayHttpRouteUpdate {
	_u.mutation.ClearMatchType()
	return _u
}

// SetMatchPattern sets the "match_pattern" field.
func (_u *CoreGatewayHttpRouteUpdate) SetMatchPattern(v string) *CoreGatewayHttpRouteUpdate {
	_u.mutation.SetMatchPattern(v)
	return _u
}

// SetNillableMatchPattern sets the "match_pattern" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdate) SetNillableMatchPattern(v *string) *CoreGatewayHttpRouteUpdate {
	if v != nil {
		_u.SetMatchPattern(*v)
	}
	return _u
}

// ClearMatchPattern clears the value of the "match_pattern" field.
func (_u *CoreGatewayHttpRouteUpdate) ClearMatchPattern() *CoreGatewayHttpRouteUpdate {
	_u.mutation.ClearMatchPattern()
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *CoreGatewayHttpRouteUpdate) SetTimeoutMs(v int) *CoreGatewayHttpRouteUpdate {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdate) SetNillableTimeoutMs(v *int) *CoreGatewayHttpRouteUpdate {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *CoreGatewayHttpRouteUpdate) AddTimeoutMs(v int) *CoreGatewayHttpRouteUpdate {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// ClearTimeoutMs clears the value of the "timeout_ms" field.
func (_u *CoreGatewayHttpRouteUpdate) ClearTimeoutMs() *CoreGatewayHttpRouteUpdate {
	_u.mutation.ClearTimeoutMs()
	return _u
}

// SetEnablePathRewrite sets the "enable_path_rewrite" field.
func (_u *CoreGatewayHttpRouteUpdate) SetEnablePathRewrite(v constant.YesOrNo) *CoreGatewayHttpRouteUpdate {
	_u.mutation.ResetEnablePathRewrite()
	_u.mutation.SetEnablePathRewrite(v)
	return _u
}

// SetNillableEnablePathRewrite sets the "enable_path_rewrite" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdate) SetNillableEnablePathRewrite(v *constant.YesOrNo) *CoreGatewayHttpRouteUpdate {
	if v != nil {
		_u.SetEnablePathRewrite(*v)
	}
	return _u
}

// AddEnablePathRewrite adds value to the "enable_path_rewrite" field.
func (_u *CoreGatewayHttpRouteUpdate) AddEnablePathRewrite(v constant.YesOrNo) *CoreGatewayHttpRouteUpdate {
	_u.mutation.AddEnablePathRewrite(v)
	return _u
}

// ClearEnablePathRewrite clears the value of the "enable_path_rewrite" field.
func (_u *CoreGatewayHttpRouteUpdate) ClearEnablePathRewrite() *CoreGatewayHttpRouteUpdate {
	_u.mutation.ClearEnablePathRewrite()
	return _u
}

// SetPathRewrite sets the "path_rewrite" field.
func (_u *CoreGatewayHttpRouteUpdate) SetPathRewrite(v string) *CoreGatewayHttpRouteUpdate {
	_u.mutation.SetPathRewrite(v)
	return _u
}

// SetNillablePathRewrite sets the "path_rewrite" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdate) SetNillablePathRewrite(v *string) *CoreGatewayHttpRouteUpdate {
	if v != nil {
		_u.SetPathRewrite(*v)
	}
	return _u
}

// ClearPathRewrite clears the value of the "path_rewrite" field.
func (_u *CoreGatewayHttpRouteUpdate) ClearPathRewrite() *CoreGatewayHttpRouteUpdate {
	_u.mutation.ClearPathRewrite()
	return _u
}

// SetEnableRedirect sets the "enable_redirect" field.
func (_u *CoreGatewayHttpRouteUpdate) SetEnableRedirect(v constant.YesOrNo) *CoreGatewayHttpRouteUpdate {
	_u.mutation.ResetEnableRedirect()
	_u.mutation.SetEnableRedirect(v)
	return _u
}

// SetNillableEnableRedirect sets the "enable_redirect" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdate) SetNillableEnableRedirect(v *constant.YesOrNo) *CoreGatewayHttpRouteUpdate {
	if v != nil {
		_u.SetEnableRedirect(*v)
	}
	return _u
}

// AddEnableRedirect adds value to the "enable_redirect" field.
func (_u *CoreGatewayHttpRouteUpdate) AddEnableRedirect(v constant.YesOrNo) *CoreGatewayHttpRouteUpdate {
	_u.mutation.AddEnableRedirect(v)
	return _u
}

// ClearEnableRedirect clears the value of the "enable_redirect" field.
func (_u *CoreGatewayHttpRouteUpdate) ClearEnableRedirect() *CoreGatewayHttpRouteUpdate {
	_u.mutation.ClearEnableRedirect()
	return _u
}

// SetRedirectURL sets the "redirect_url" field.
func (_u *CoreGatewayHttpRouteUpdate) SetRedirectURL(v string) *CoreGatewayHttpRouteUpdate {
	_u.mutation.SetRedirectURL(v)
	return _u
}

// SetNillableRedirectURL sets the "redirect_url" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdate) SetNillableRedirectURL(v *string) *CoreGatewayHttpRouteUpdate {
	if v != nil {
		_u.SetRedirectURL(*v)
	}
	return _u
}

// ClearRedirectURL clears the value of the "redirect_url" field.
func (_u *CoreGatewayHttpRouteUpdate) ClearRedirectURL() *CoreGatewayHttpRouteUpdate {
	_u.mutation.ClearRedirectURL()
	return _u
}

// SetRedirectCode sets the "redirect_code" field.
func (_u *CoreGatewayHttpRouteUpdate) SetRedirectCode(v int) *CoreGatewayHttpRouteUpdate {
	_u.mutation.ResetRedirectCode()
	_u.mutation.SetRedirectCode(v)
	return _u
}

// SetNillableRedirectCode sets the "redirect_code" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdate) SetNillableRedirectCode(v *int) *CoreGatewayHttpRouteUpdate {
	if v != nil {
		_u.SetRedirectCode(*v)
	}
	return _u
}

// AddRedirectCode adds value to the "redirect_code" field.
func (_u *CoreGatewayHttpRouteUpdate) AddRedirectCode(v int) *CoreGatewayHttpRouteUpdate {
	_u.mutation.AddRedirectCode(v)
	return _u
}

// ClearRedirectCode clears the value of the "redirect_code" field.
func (_u *CoreGatewayHttpRouteUpdate) ClearRedirectCode() *CoreGatewayHttpRouteUpdate {
	_u.mutation.ClearRedirectCode()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CoreGatewayHttpRouteUpdate) SetStatus(v constant.YesOrNo) *CoreGatewayHttpRouteUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdate) SetNillableStatus(v *constant.YesOrNo) *CoreGatewayHttpRouteUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *CoreGatewayHttpRouteUpdate) AddStatus(v constant.YesOrNo) *CoreGatewayHttpRouteUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *CoreGatewayHttpRouteUpdate) ClearStatus() *CoreGatewayHttpRouteUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// Mutation returns the CoreGatewayHttpRouteMutation object of the builder.
func (_u *CoreGatewayHttpRouteUpdate) Mutation() *CoreGatewayHttpRouteMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CoreGatewayHttpRouteUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoreGatewayHttpRouteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CoreGatewayHttpRouteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoreGatewayHttpRouteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CoreGatewayHttpRouteUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if coregatewayhttproute.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized coregatewayhttproute.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := coregatewayhttproute.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CoreGatewayHttpRouteUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CoreGatewayHttpRouteUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CoreGatewayHttpRouteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(coregatewayhttproute.Table, coregatewayhttproute.Columns, sqlgraph.NewFieldSpec(coregatewayhttproute.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(coregatewayhttproute.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(coregatewayhttproute.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(coregatewayhttproute.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(coregatewayhttproute.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(coregatewayhttproute.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(coregatewayhttproute.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(coregatewayhttproute.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.MatchType(); ok {
		_spec.SetField(coregatewayhttproute.FieldMatchType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMatchType(); ok {
		_spec.AddField(coregatewayhttproute.FieldMatchType, field.TypeInt8, value)
	}
	if _u.mutation.MatchTypeCleared() {
		_spec.ClearField(coregatewayhttproute.FieldMatchType, field.TypeInt8)
	}
	if value, ok := _u.mutation.MatchPattern(); ok {
		_spec.SetField(coregatewayhttproute.FieldMatchPattern, field.TypeString, value)
	}
	if _u.mutation.MatchPatternCleared() {
		_spec.ClearField(coregatewayhttproute.FieldMatchPattern, field.TypeString)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(coregatewayhttproute.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(coregatewayhttproute.FieldTimeoutMs, field.TypeInt, value)
	}
	if _u.mutation.TimeoutMsCleared() {
		_spec.ClearField(coregatewayhttproute.FieldTimeoutMs, field.TypeInt)
	}
	if value, ok := _u.mutation.EnablePathRewrite(); ok {
		_spec.SetField(coregatewayhttproute.FieldEnablePathRewrite, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedEnablePathRewrite(); ok {
		_spec.AddField(coregatewayhttproute.FieldEnablePathRewrite, field.TypeInt8, value)
	}
	if _u.mutation.EnablePathRewriteCleared() {
		_spec.ClearField(coregatewayhttproute.FieldEnablePathRewrite, field.TypeInt8)
	}
	if value, ok := _u.mutation.PathRewrite(); ok {
		_spec.SetField(coregatewayhttproute.FieldPathRewrite, field.TypeString, value)
	}
	if _u.mutation.PathRewriteCleared() {
		_spec.ClearField(coregatewayhttproute.FieldPathRewrite, field.TypeString)
	}
	if value, ok := _u.mutation.EnableRedirect(); ok {
		_spec.SetField(coregatewayhttproute.FieldEnableRedirect, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedEnableRedirect(); ok {
		_spec.AddField(coregatewayhttproute.FieldEnableRedirect, field.TypeInt8, value)
	}
	if _u.mutation.EnableRedirectCleared() {
		_spec.ClearField(coregatewayhttproute.FieldEnableRedirect, field.TypeInt8)
	}
	if value, ok := _u.mutation.RedirectURL(); ok {
		_spec.SetField(coregatewayhttproute.FieldRedirectURL, field.TypeString, value)
	}
	if _u.mutation.RedirectURLCleared() {
		_spec.ClearField(coregatewayhttproute.FieldRedirectURL, field.TypeString)
	}
	if value, ok := _u.mutation.RedirectCode(); ok {
		_spec.SetField(coregatewayhttproute.FieldRedirectCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRedirectCode(); ok {
		_spec.AddField(coregatewayhttproute.FieldRedirectCode, field.TypeInt, value)
	}
	if _u.mutation.RedirectCodeCleared() {
		_spec.ClearField(coregatewayhttproute.FieldRedirectCode, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(coregatewayhttproute.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(coregatewayhttproute.FieldStatus, field.TypeInt8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(coregatewayhttproute.FieldStatus, field.TypeInt8)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coregatewayhttproute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CoreGatewayHttpRouteUpdateOne is the builder for updating a single CoreGatewayHttpRoute entity.
type CoreGatewayHttpRouteUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CoreGatewayHttpRouteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CoreGatewayHttpRouteUpdateOne) SetUpdatedAt(v time.Time) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CoreGatewayHttpRouteUpdateOne) SetDeletedAt(v time.Time) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdateOne) SetNillableDeletedAt(v *time.Time) *CoreGatewayHttpRouteUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CoreGatewayHttpRouteUpdateOne) ClearDeletedAt() *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *CoreGatewayHttpRouteUpdateOne) SetName(v string) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdateOne) SetNillableName(v *string) *CoreGatewayHttpRouteUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *CoreGatewayHttpRouteUpdateOne) ClearName() *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *CoreGatewayHttpRouteUpdateOne) SetDescription(v string) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdateOne) SetNillableDescription(v *string) *CoreGatewayHttpRouteUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CoreGatewayHttpRouteUpdateOne) ClearDescription() *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetMatchType sets the "match_type" field.
func (_u *CoreGatewayHttpRouteUpdateOne) SetMatchType(v constant.ProxyHttpRouteMatchType) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ResetMatchType()
	_u.mutation.SetMatchType(v)
	return _u
}

// SetNillableMatchType sets the "match_type" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdateOne) SetNillableMatchType(v *constant.ProxyHttpRouteMatchType) *CoreGatewayHttpRouteUpdateOne {
	if v != nil {
		_u.SetMatchType(*v)
	}
	return _u
}

// AddMatchType adds value to the "match_type" field.
func (_u *CoreGatewayHttpRouteUpdateOne) AddMatchType(v constant.ProxyHttpRouteMatchType) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.AddMatchType(v)
	return _u
}

// ClearMatchType clears the value of the "match_type" field.
func (_u *CoreGatewayHttpRouteUpdateOne) ClearMatchType() *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ClearMatchType()
	return _u
}

// SetMatchPattern sets the "match_pattern" field.
func (_u *CoreGatewayHttpRouteUpdateOne) SetMatchPattern(v string) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.SetMatchPattern(v)
	return _u
}

// SetNillableMatchPattern sets the "match_pattern" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdateOne) SetNillableMatchPattern(v *string) *CoreGatewayHttpRouteUpdateOne {
	if v != nil {
		_u.SetMatchPattern(*v)
	}
	return _u
}

// ClearMatchPattern clears the value of the "match_pattern" field.
func (_u *CoreGatewayHttpRouteUpdateOne) ClearMatchPattern() *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ClearMatchPattern()
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *CoreGatewayHttpRouteUpdateOne) SetTimeoutMs(v int) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdateOne) SetNillableTimeoutMs(v *int) *CoreGatewayHttpRouteUpdateOne {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *CoreGatewayHttpRouteUpdateOne) AddTimeoutMs(v int) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// ClearTimeoutMs clears the value of the "timeout_ms" field.
func (_u *CoreGatewayHttpRouteUpdateOne) ClearTimeoutMs() *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ClearTimeoutMs()
	return _u
}

// SetEnablePathRewrite sets the "enable_path_rewrite" field.
func (_u *CoreGatewayHttpRouteUpdateOne) SetEnablePathRewrite(v constant.YesOrNo) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ResetEnablePathRewrite()
	_u.mutation.SetEnablePathRewrite(v)
	return _u
}

// SetNillableEnablePathRewrite sets the "enable_path_rewrite" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdateOne) SetNillableEnablePathRewrite(v *constant.YesOrNo) *CoreGatewayHttpRouteUpdateOne {
	if v != nil {
		_u.SetEnablePathRewrite(*v)
	}
	return _u
}

// AddEnablePathRewrite adds value to the "enable_path_rewrite" field.
func (_u *CoreGatewayHttpRouteUpdateOne) AddEnablePathRewrite(v constant.YesOrNo) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.AddEnablePathRewrite(v)
	return _u
}

// ClearEnablePathRewrite clears the value of the "enable_path_rewrite" field.
func (_u *CoreGatewayHttpRouteUpdateOne) ClearEnablePathRewrite() *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ClearEnablePathRewrite()
	return _u
}

// SetPathRewrite sets the "path_rewrite" field.
func (_u *CoreGatewayHttpRouteUpdateOne) SetPathRewrite(v string) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.SetPathRewrite(v)
	return _u
}

// SetNillablePathRewrite sets the "path_rewrite" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdateOne) SetNillablePathRewrite(v *string) *CoreGatewayHttpRouteUpdateOne {
	if v != nil {
		_u.SetPathRewrite(*v)
	}
	return _u
}

// ClearPathRewrite clears the value of the "path_rewrite" field.
func (_u *CoreGatewayHttpRouteUpdateOne) ClearPathRewrite() *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ClearPathRewrite()
	return _u
}

// SetEnableRedirect sets the "enable_redirect" field.
func (_u *CoreGatewayHttpRouteUpdateOne) SetEnableRedirect(v constant.YesOrNo) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ResetEnableRedirect()
	_u.mutation.SetEnableRedirect(v)
	return _u
}

// SetNillableEnableRedirect sets the "enable_redirect" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdateOne) SetNillableEnableRedirect(v *constant.YesOrNo) *CoreGatewayHttpRouteUpdateOne {
	if v != nil {
		_u.SetEnableRedirect(*v)
	}
	return _u
}

// AddEnableRedirect adds value to the "enable_redirect" field.
func (_u *CoreGatewayHttpRouteUpdateOne) AddEnableRedirect(v constant.YesOrNo) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.AddEnableRedirect(v)
	return _u
}

// ClearEnableRedirect clears the value of the "enable_redirect" field.
func (_u *CoreGatewayHttpRouteUpdateOne) ClearEnableRedirect() *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ClearEnableRedirect()
	return _u
}

// SetRedirectURL sets the "redirect_url" field.
func (_u *CoreGatewayHttpRouteUpdateOne) SetRedirectURL(v string) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.SetRedirectURL(v)
	return _u
}

// SetNillableRedirectURL sets the "redirect_url" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdateOne) SetNillableRedirectURL(v *string) *CoreGatewayHttpRouteUpdateOne {
	if v != nil {
		_u.SetRedirectURL(*v)
	}
	return _u
}

// ClearRedirectURL clears the value of the "redirect_url" field.
func (_u *CoreGatewayHttpRouteUpdateOne) ClearRedirectURL() *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ClearRedirectURL()
	return _u
}

// SetRedirectCode sets the "redirect_code" field.
func (_u *CoreGatewayHttpRouteUpdateOne) SetRedirectCode(v int) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ResetRedirectCode()
	_u.mutation.SetRedirectCode(v)
	return _u
}

// SetNillableRedirectCode sets the "redirect_code" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdateOne) SetNillableRedirectCode(v *int) *CoreGatewayHttpRouteUpdateOne {
	if v != nil {
		_u.SetRedirectCode(*v)
	}
	return _u
}

// AddRedirectCode adds value to the "redirect_code" field.
func (_u *CoreGatewayHttpRouteUpdateOne) AddRedirectCode(v int) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.AddRedirectCode(v)
	return _u
}

// ClearRedirectCode clears the value of the "redirect_code" field.
func (_u *CoreGatewayHttpRouteUpdateOne) ClearRedirectCode() *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ClearRedirectCode()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CoreGatewayHttpRouteUpdateOne) SetStatus(v constant.YesOrNo) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CoreGatewayHttpRouteUpdateOne) SetNillableStatus(v *constant.YesOrNo) *CoreGatewayHttpRouteUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *CoreGatewayHttpRouteUpdateOne) AddStatus(v constant.YesOrNo) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *CoreGatewayHttpRouteUpdateOne) ClearStatus() *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// Mutation returns the CoreGatewayHttpRouteMutation object of the builder.
func (_u *CoreGatewayHttpRouteUpdateOne) Mutation() *CoreGatewayHttpRouteMutation {
	return _u.mutation
}

// Where appends a list predicates to the CoreGatewayHttpRouteUpdate builder.
func (_u *CoreGatewayHttpRouteUpdateOne) Where(ps ...predicate.CoreGatewayHttpRoute) *CoreGatewayHttpRouteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CoreGatewayHttpRouteUpdateOne) Select(field string, fields ...string) *CoreGatewayHttpRouteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CoreGatewayHttpRoute entity.
func (_u *CoreGatewayHttpRouteUpdateOne) Save(ctx context.Context) (*CoreGatewayHttpRoute, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoreGatewayHttpRouteUpdateOne) SaveX(ctx context.Context) *CoreGatewayHttpRoute {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CoreGatewayHttpRouteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoreGatewayHttpRouteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CoreGatewayHttpRouteUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if coregatewayhttproute.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized coregatewayhttproute.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := coregatewayhttproute.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CoreGatewayHttpRouteUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CoreGatewayHttpRouteUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CoreGatewayHttpRouteUpdateOne) sqlSave(ctx context.Context) (_node *CoreGatewayHttpRoute, err error) {
	_spec := sqlgraph.NewUpdateSpec(coregatewayhttproute.Table, coregatewayhttproute.Columns, sqlgraph.NewFieldSpec(coregatewayhttproute.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CoreGatewayHttpRoute.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coregatewayhttproute.FieldID)
		for _, f := range fields {
			if !coregatewayhttproute.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != coregatewayhttproute.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(coregatewayhttproute.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(coregatewayhttproute.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(coregatewayhttproute.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(coregatewayhttproute.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(coregatewayhttproute.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(coregatewayhttproute.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(coregatewayhttproute.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.MatchType(); ok {
		_spec.SetField(coregatewayhttproute.FieldMatchType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedMatchType(); ok {
		_spec.AddField(coregatewayhttproute.FieldMatchType, field.TypeInt8, value)
	}
	if _u.mutation.MatchTypeCleared() {
		_spec.ClearField(coregatewayhttproute.FieldMatchType, field.TypeInt8)
	}
	if value, ok := _u.mutation.MatchPattern(); ok {
		_spec.SetField(coregatewayhttproute.FieldMatchPattern, field.TypeString, value)
	}
	if _u.mutation.MatchPatternCleared() {
		_spec.ClearField(coregatewayhttproute.FieldMatchPattern, field.TypeString)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(coregatewayhttproute.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(coregatewayhttproute.FieldTimeoutMs, field.TypeInt, value)
	}
	if _u.mutation.TimeoutMsCleared() {
		_spec.ClearField(coregatewayhttproute.FieldTimeoutMs, field.TypeInt)
	}
	if value, ok := _u.mutation.EnablePathRewrite(); ok {
		_spec.SetField(coregatewayhttproute.FieldEnablePathRewrite, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedEnablePathRewrite(); ok {
		_spec.AddField(coregatewayhttproute.FieldEnablePathRewrite, field.TypeInt8, value)
	}
	if _u.mutation.EnablePathRewriteCleared() {
		_spec.ClearField(coregatewayhttproute.FieldEnablePathRewrite, field.TypeInt8)
	}
	if value, ok := _u.mutation.PathRewrite(); ok {
		_spec.SetField(coregatewayhttproute.FieldPathRewrite, field.TypeString, value)
	}
	if _u.mutation.PathRewriteCleared() {
		_spec.ClearField(coregatewayhttproute.FieldPathRewrite, field.TypeString)
	}
	if value, ok := _u.mutation.EnableRedirect(); ok {
		_spec.SetField(coregatewayhttproute.FieldEnableRedirect, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedEnableRedirect(); ok {
		_spec.AddField(coregatewayhttproute.FieldEnableRedirect, field.TypeInt8, value)
	}
	if _u.mutation.EnableRedirectCleared() {
		_spec.ClearField(coregatewayhttproute.FieldEnableRedirect, field.TypeInt8)
	}
	if value, ok := _u.mutation.RedirectURL(); ok {
		_spec.SetField(coregatewayhttproute.FieldRedirectURL, field.TypeString, value)
	}
	if _u.mutation.RedirectURLCleared() {
		_spec.ClearField(coregatewayhttproute.FieldRedirectURL, field.TypeString)
	}
	if value, ok := _u.mutation.RedirectCode(); ok {
		_spec.SetField(coregatewayhttproute.FieldRedirectCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRedirectCode(); ok {
		_spec.AddField(coregatewayhttproute.FieldRedirectCode, field.TypeInt, value)
	}
	if _u.mutation.RedirectCodeCleared() {
		_spec.ClearField(coregatewayhttproute.FieldRedirectCode, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(coregatewayhttproute.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(coregatewayhttproute.FieldStatus, field.TypeInt8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(coregatewayhttproute.FieldStatus, field.TypeInt8)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &CoreGatewayHttpRoute{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coregatewayhttproute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
