// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coredatarelationship"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/corerole"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coreuser"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/predicate"
)

// CoreRoleQuery is the builder for querying CoreRole entities.
type CoreRoleQuery struct {
	config
	ctx                        *QueryContext
	order                      []corerole.OrderOption
	inters                     []Interceptor
	predicates                 []predicate.CoreRole
	withRoleToUser             *CoreUserQuery
	withRoleToDataRelationship *CoreDataRelationshipQuery
	modifiers                  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CoreRoleQuery builder.
func (_q *CoreRoleQuery) Where(ps ...predicate.CoreRole) *CoreRoleQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CoreRoleQuery) Limit(limit int) *CoreRoleQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CoreRoleQuery) Offset(offset int) *CoreRoleQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CoreRoleQuery) Unique(unique bool) *CoreRoleQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CoreRoleQuery) Order(o ...corerole.OrderOption) *CoreRoleQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRoleToUser chains the current query on the "role_to_user" edge.
func (_q *CoreRoleQuery) QueryRoleToUser() *CoreUserQuery {
	query := (&CoreUserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(corerole.Table, corerole.FieldID, selector),
			sqlgraph.To(coreuser.Table, coreuser.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, corerole.RoleToUserTable, corerole.RoleToUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRoleToDataRelationship chains the current query on the "role_to_data_relationship" edge.
func (_q *CoreRoleQuery) QueryRoleToDataRelationship() *CoreDataRelationshipQuery {
	query := (&CoreDataRelationshipClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(corerole.Table, corerole.FieldID, selector),
			sqlgraph.To(coredatarelationship.Table, coredatarelationship.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, corerole.RoleToDataRelationshipTable, corerole.RoleToDataRelationshipColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CoreRole entity from the query.
// Returns a *NotFoundError when no CoreRole was found.
func (_q *CoreRoleQuery) First(ctx context.Context) (*CoreRole, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{corerole.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CoreRoleQuery) FirstX(ctx context.Context) *CoreRole {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CoreRole ID from the query.
// Returns a *NotFoundError when no CoreRole ID was found.
func (_q *CoreRoleQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{corerole.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CoreRoleQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CoreRole entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CoreRole entity is found.
// Returns a *NotFoundError when no CoreRole entities are found.
func (_q *CoreRoleQuery) Only(ctx context.Context) (*CoreRole, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{corerole.Label}
	default:
		return nil, &NotSingularError{corerole.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CoreRoleQuery) OnlyX(ctx context.Context) *CoreRole {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CoreRole ID in the query.
// Returns a *NotSingularError when more than one CoreRole ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CoreRoleQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{corerole.Label}
	default:
		err = &NotSingularError{corerole.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CoreRoleQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CoreRoles.
func (_q *CoreRoleQuery) All(ctx context.Context) ([]*CoreRole, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CoreRole, *CoreRoleQuery]()
	return withInterceptors[[]*CoreRole](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CoreRoleQuery) AllX(ctx context.Context) []*CoreRole {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CoreRole IDs.
func (_q *CoreRoleQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(corerole.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CoreRoleQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CoreRoleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CoreRoleQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CoreRoleQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CoreRoleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CoreRoleQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CoreRoleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CoreRoleQuery) Clone() *CoreRoleQuery {
	if _q == nil {
		return nil
	}
	return &CoreRoleQuery{
		config:                     _q.config,
		ctx:                        _q.ctx.Clone(),
		order:                      append([]corerole.OrderOption{}, _q.order...),
		inters:                     append([]Interceptor{}, _q.inters...),
		predicates:                 append([]predicate.CoreRole{}, _q.predicates...),
		withRoleToUser:             _q.withRoleToUser.Clone(),
		withRoleToDataRelationship: _q.withRoleToDataRelationship.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithRoleToUser tells the query-builder to eager-load the nodes that are connected to
// the "role_to_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CoreRoleQuery) WithRoleToUser(opts ...func(*CoreUserQuery)) *CoreRoleQuery {
	query := (&CoreUserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRoleToUser = query
	return _q
}

// WithRoleToDataRelationship tells the query-builder to eager-load the nodes that are connected to
// the "role_to_data_relationship" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CoreRoleQuery) WithRoleToDataRelationship(opts ...func(*CoreDataRelationshipQuery)) *CoreRoleQuery {
	query := (&CoreDataRelationshipClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRoleToDataRelationship = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CoreRole.Query().
//		GroupBy(corerole.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CoreRoleQuery) GroupBy(field string, fields ...string) *CoreRoleGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CoreRoleGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = corerole.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.CoreRole.Query().
//		Select(corerole.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *CoreRoleQuery) Select(fields ...string) *CoreRoleSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CoreRoleSelect{CoreRoleQuery: _q}
	sbuild.label = corerole.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CoreRoleSelect configured with the given aggregations.
func (_q *CoreRoleQuery) Aggregate(fns ...AggregateFunc) *CoreRoleSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CoreRoleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !corerole.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CoreRoleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CoreRole, error) {
	var (
		nodes       = []*CoreRole{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withRoleToUser != nil,
			_q.withRoleToDataRelationship != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CoreRole).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CoreRole{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRoleToUser; query != nil {
		if err := _q.loadRoleToUser(ctx, query, nodes,
			func(n *CoreRole) { n.Edges.RoleToUser = []*CoreUser{} },
			func(n *CoreRole, e *CoreUser) { n.Edges.RoleToUser = append(n.Edges.RoleToUser, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRoleToDataRelationship; query != nil {
		if err := _q.loadRoleToDataRelationship(ctx, query, nodes,
			func(n *CoreRole) { n.Edges.RoleToDataRelationship = []*CoreDataRelationship{} },
			func(n *CoreRole, e *CoreDataRelationship) {
				n.Edges.RoleToDataRelationship = append(n.Edges.RoleToDataRelationship, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CoreRoleQuery) loadRoleToUser(ctx context.Context, query *CoreUserQuery, nodes []*CoreRole, init func(*CoreRole), assign func(*CoreRole, *CoreUser)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*CoreRole)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(coreuser.FieldRoleID)
	}
	query.Where(predicate.CoreUser(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(corerole.RoleToUserColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RoleID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "role_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *CoreRoleQuery) loadRoleToDataRelationship(ctx context.Context, query *CoreDataRelationshipQuery, nodes []*CoreRole, init func(*CoreRole), assign func(*CoreRole, *CoreDataRelationship)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*CoreRole)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(coredatarelationship.FieldRoleID)
	}
	query.Where(predicate.CoreDataRelationship(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(corerole.RoleToDataRelationshipColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RoleID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "role_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *CoreRoleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CoreRoleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(corerole.Table, corerole.Columns, sqlgraph.NewFieldSpec(corerole.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, corerole.FieldID)
		for i := range fields {
			if fields[i] != corerole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CoreRoleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(corerole.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = corerole.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *CoreRoleQuery) Modify(modifiers ...func(s *sql.Selector)) *CoreRoleSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// CoreRoleGroupBy is the group-by builder for CoreRole entities.
type CoreRoleGroupBy struct {
	selector
	build *CoreRoleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CoreRoleGroupBy) Aggregate(fns ...AggregateFunc) *CoreRoleGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CoreRoleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CoreRoleQuery, *CoreRoleGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CoreRoleGroupBy) sqlScan(ctx context.Context, root *CoreRoleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CoreRoleSelect is the builder for selecting fields of CoreRole entities.
type CoreRoleSelect struct {
	*CoreRoleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CoreRoleSelect) Aggregate(fns ...AggregateFunc) *CoreRoleSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CoreRoleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CoreRoleQuery, *CoreRoleSelect](ctx, _s.CoreRoleQuery, _s, _s.inters, v)
}

func (_s *CoreRoleSelect) sqlScan(ctx context.Context, root *CoreRoleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *CoreRoleSelect) Modify(modifiers ...func(s *sql.Selector)) *CoreRoleSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
