// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coredatarelationship"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coremenu"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/corerole"
	"github.com/lyonmu/quebec/pkg/common"
)

// CoreDataRelationshipCreate is the builder for creating a CoreDataRelationship entity.
type CoreDataRelationshipCreate struct {
	config
	mutation *CoreDataRelationshipMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CoreDataRelationshipCreate) SetCreatedAt(v time.Time) *CoreDataRelationshipCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CoreDataRelationshipCreate) SetNillableCreatedAt(v *time.Time) *CoreDataRelationshipCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CoreDataRelationshipCreate) SetUpdatedAt(v time.Time) *CoreDataRelationshipCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CoreDataRelationshipCreate) SetNillableUpdatedAt(v *time.Time) *CoreDataRelationshipCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *CoreDataRelationshipCreate) SetDeletedAt(v time.Time) *CoreDataRelationshipCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *CoreDataRelationshipCreate) SetNillableDeletedAt(v *time.Time) *CoreDataRelationshipCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDataRelationshipType sets the "data_relationship_type" field.
func (_c *CoreDataRelationshipCreate) SetDataRelationshipType(v common.DataRelationshipType) *CoreDataRelationshipCreate {
	_c.mutation.SetDataRelationshipType(v)
	return _c
}

// SetNillableDataRelationshipType sets the "data_relationship_type" field if the given value is not nil.
func (_c *CoreDataRelationshipCreate) SetNillableDataRelationshipType(v *common.DataRelationshipType) *CoreDataRelationshipCreate {
	if v != nil {
		_c.SetDataRelationshipType(*v)
	}
	return _c
}

// SetMenuID sets the "menu_id" field.
func (_c *CoreDataRelationshipCreate) SetMenuID(v string) *CoreDataRelationshipCreate {
	_c.mutation.SetMenuID(v)
	return _c
}

// SetNillableMenuID sets the "menu_id" field if the given value is not nil.
func (_c *CoreDataRelationshipCreate) SetNillableMenuID(v *string) *CoreDataRelationshipCreate {
	if v != nil {
		_c.SetMenuID(*v)
	}
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *CoreDataRelationshipCreate) SetRoleID(v string) *CoreDataRelationshipCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_c *CoreDataRelationshipCreate) SetNillableRoleID(v *string) *CoreDataRelationshipCreate {
	if v != nil {
		_c.SetRoleID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CoreDataRelationshipCreate) SetID(v string) *CoreDataRelationshipCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CoreDataRelationshipCreate) SetNillableID(v *string) *CoreDataRelationshipCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetDataRelationshipFromMenuID sets the "data_relationship_from_menu" edge to the CoreMenu entity by ID.
func (_c *CoreDataRelationshipCreate) SetDataRelationshipFromMenuID(id string) *CoreDataRelationshipCreate {
	_c.mutation.SetDataRelationshipFromMenuID(id)
	return _c
}

// SetNillableDataRelationshipFromMenuID sets the "data_relationship_from_menu" edge to the CoreMenu entity by ID if the given value is not nil.
func (_c *CoreDataRelationshipCreate) SetNillableDataRelationshipFromMenuID(id *string) *CoreDataRelationshipCreate {
	if id != nil {
		_c = _c.SetDataRelationshipFromMenuID(*id)
	}
	return _c
}

// SetDataRelationshipFromMenu sets the "data_relationship_from_menu" edge to the CoreMenu entity.
func (_c *CoreDataRelationshipCreate) SetDataRelationshipFromMenu(v *CoreMenu) *CoreDataRelationshipCreate {
	return _c.SetDataRelationshipFromMenuID(v.ID)
}

// SetDataRelationshipFromRoleID sets the "data_relationship_from_role" edge to the CoreRole entity by ID.
func (_c *CoreDataRelationshipCreate) SetDataRelationshipFromRoleID(id string) *CoreDataRelationshipCreate {
	_c.mutation.SetDataRelationshipFromRoleID(id)
	return _c
}

// SetNillableDataRelationshipFromRoleID sets the "data_relationship_from_role" edge to the CoreRole entity by ID if the given value is not nil.
func (_c *CoreDataRelationshipCreate) SetNillableDataRelationshipFromRoleID(id *string) *CoreDataRelationshipCreate {
	if id != nil {
		_c = _c.SetDataRelationshipFromRoleID(*id)
	}
	return _c
}

// SetDataRelationshipFromRole sets the "data_relationship_from_role" edge to the CoreRole entity.
func (_c *CoreDataRelationshipCreate) SetDataRelationshipFromRole(v *CoreRole) *CoreDataRelationshipCreate {
	return _c.SetDataRelationshipFromRoleID(v.ID)
}

// Mutation returns the CoreDataRelationshipMutation object of the builder.
func (_c *CoreDataRelationshipCreate) Mutation() *CoreDataRelationshipMutation {
	return _c.mutation
}

// Save creates the CoreDataRelationship in the database.
func (_c *CoreDataRelationshipCreate) Save(ctx context.Context) (*CoreDataRelationship, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CoreDataRelationshipCreate) SaveX(ctx context.Context) *CoreDataRelationship {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CoreDataRelationshipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CoreDataRelationshipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CoreDataRelationshipCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if coredatarelationship.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized coredatarelationship.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := coredatarelationship.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if coredatarelationship.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized coredatarelationship.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := coredatarelationship.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if coredatarelationship.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized coredatarelationship.DefaultID (forgotten import ent/runtime?)")
		}
		v := coredatarelationship.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *CoreDataRelationshipCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CoreDataRelationship.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CoreDataRelationship.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := coredatarelationship.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "CoreDataRelationship.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CoreDataRelationshipCreate) sqlSave(ctx context.Context) (*CoreDataRelationship, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CoreDataRelationship.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CoreDataRelationshipCreate) createSpec() (*CoreDataRelationship, *sqlgraph.CreateSpec) {
	var (
		_node = &CoreDataRelationship{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(coredatarelationship.Table, sqlgraph.NewFieldSpec(coredatarelationship.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(coredatarelationship.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(coredatarelationship.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(coredatarelationship.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.DataRelationshipType(); ok {
		_spec.SetField(coredatarelationship.FieldDataRelationshipType, field.TypeInt8, value)
		_node.DataRelationshipType = value
	}
	if nodes := _c.mutation.DataRelationshipFromMenuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coredatarelationship.DataRelationshipFromMenuTable,
			Columns: []string{coredatarelationship.DataRelationshipFromMenuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coremenu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MenuID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DataRelationshipFromRoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coredatarelationship.DataRelationshipFromRoleTable,
			Columns: []string{coredatarelationship.DataRelationshipFromRoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(corerole.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoreDataRelationship.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoreDataRelationshipUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CoreDataRelationshipCreate) OnConflict(opts ...sql.ConflictOption) *CoreDataRelationshipUpsertOne {
	_c.conflict = opts
	return &CoreDataRelationshipUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoreDataRelationship.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CoreDataRelationshipCreate) OnConflictColumns(columns ...string) *CoreDataRelationshipUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CoreDataRelationshipUpsertOne{
		create: _c,
	}
}

type (
	// CoreDataRelationshipUpsertOne is the builder for "upsert"-ing
	//  one CoreDataRelationship node.
	CoreDataRelationshipUpsertOne struct {
		create *CoreDataRelationshipCreate
	}

	// CoreDataRelationshipUpsert is the "OnConflict" setter.
	CoreDataRelationshipUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CoreDataRelationshipUpsert) SetUpdatedAt(v time.Time) *CoreDataRelationshipUpsert {
	u.Set(coredatarelationship.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoreDataRelationshipUpsert) UpdateUpdatedAt() *CoreDataRelationshipUpsert {
	u.SetExcluded(coredatarelationship.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoreDataRelationshipUpsert) SetDeletedAt(v time.Time) *CoreDataRelationshipUpsert {
	u.Set(coredatarelationship.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoreDataRelationshipUpsert) UpdateDeletedAt() *CoreDataRelationshipUpsert {
	u.SetExcluded(coredatarelationship.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CoreDataRelationshipUpsert) ClearDeletedAt() *CoreDataRelationshipUpsert {
	u.SetNull(coredatarelationship.FieldDeletedAt)
	return u
}

// SetDataRelationshipType sets the "data_relationship_type" field.
func (u *CoreDataRelationshipUpsert) SetDataRelationshipType(v common.DataRelationshipType) *CoreDataRelationshipUpsert {
	u.Set(coredatarelationship.FieldDataRelationshipType, v)
	return u
}

// UpdateDataRelationshipType sets the "data_relationship_type" field to the value that was provided on create.
func (u *CoreDataRelationshipUpsert) UpdateDataRelationshipType() *CoreDataRelationshipUpsert {
	u.SetExcluded(coredatarelationship.FieldDataRelationshipType)
	return u
}

// AddDataRelationshipType adds v to the "data_relationship_type" field.
func (u *CoreDataRelationshipUpsert) AddDataRelationshipType(v common.DataRelationshipType) *CoreDataRelationshipUpsert {
	u.Add(coredatarelationship.FieldDataRelationshipType, v)
	return u
}

// ClearDataRelationshipType clears the value of the "data_relationship_type" field.
func (u *CoreDataRelationshipUpsert) ClearDataRelationshipType() *CoreDataRelationshipUpsert {
	u.SetNull(coredatarelationship.FieldDataRelationshipType)
	return u
}

// SetMenuID sets the "menu_id" field.
func (u *CoreDataRelationshipUpsert) SetMenuID(v string) *CoreDataRelationshipUpsert {
	u.Set(coredatarelationship.FieldMenuID, v)
	return u
}

// UpdateMenuID sets the "menu_id" field to the value that was provided on create.
func (u *CoreDataRelationshipUpsert) UpdateMenuID() *CoreDataRelationshipUpsert {
	u.SetExcluded(coredatarelationship.FieldMenuID)
	return u
}

// ClearMenuID clears the value of the "menu_id" field.
func (u *CoreDataRelationshipUpsert) ClearMenuID() *CoreDataRelationshipUpsert {
	u.SetNull(coredatarelationship.FieldMenuID)
	return u
}

// SetRoleID sets the "role_id" field.
func (u *CoreDataRelationshipUpsert) SetRoleID(v string) *CoreDataRelationshipUpsert {
	u.Set(coredatarelationship.FieldRoleID, v)
	return u
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *CoreDataRelationshipUpsert) UpdateRoleID() *CoreDataRelationshipUpsert {
	u.SetExcluded(coredatarelationship.FieldRoleID)
	return u
}

// ClearRoleID clears the value of the "role_id" field.
func (u *CoreDataRelationshipUpsert) ClearRoleID() *CoreDataRelationshipUpsert {
	u.SetNull(coredatarelationship.FieldRoleID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CoreDataRelationship.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coredatarelationship.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CoreDataRelationshipUpsertOne) UpdateNewValues() *CoreDataRelationshipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(coredatarelationship.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(coredatarelationship.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CoreDataRelationship.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CoreDataRelationshipUpsertOne) Ignore() *CoreDataRelationshipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoreDataRelationshipUpsertOne) DoNothing() *CoreDataRelationshipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoreDataRelationshipCreate.OnConflict
// documentation for more info.
func (u *CoreDataRelationshipUpsertOne) Update(set func(*CoreDataRelationshipUpsert)) *CoreDataRelationshipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoreDataRelationshipUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoreDataRelationshipUpsertOne) SetUpdatedAt(v time.Time) *CoreDataRelationshipUpsertOne {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoreDataRelationshipUpsertOne) UpdateUpdatedAt() *CoreDataRelationshipUpsertOne {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoreDataRelationshipUpsertOne) SetDeletedAt(v time.Time) *CoreDataRelationshipUpsertOne {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoreDataRelationshipUpsertOne) UpdateDeletedAt() *CoreDataRelationshipUpsertOne {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CoreDataRelationshipUpsertOne) ClearDeletedAt() *CoreDataRelationshipUpsertOne {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDataRelationshipType sets the "data_relationship_type" field.
func (u *CoreDataRelationshipUpsertOne) SetDataRelationshipType(v common.DataRelationshipType) *CoreDataRelationshipUpsertOne {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.SetDataRelationshipType(v)
	})
}

// AddDataRelationshipType adds v to the "data_relationship_type" field.
func (u *CoreDataRelationshipUpsertOne) AddDataRelationshipType(v common.DataRelationshipType) *CoreDataRelationshipUpsertOne {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.AddDataRelationshipType(v)
	})
}

// UpdateDataRelationshipType sets the "data_relationship_type" field to the value that was provided on create.
func (u *CoreDataRelationshipUpsertOne) UpdateDataRelationshipType() *CoreDataRelationshipUpsertOne {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.UpdateDataRelationshipType()
	})
}

// ClearDataRelationshipType clears the value of the "data_relationship_type" field.
func (u *CoreDataRelationshipUpsertOne) ClearDataRelationshipType() *CoreDataRelationshipUpsertOne {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.ClearDataRelationshipType()
	})
}

// SetMenuID sets the "menu_id" field.
func (u *CoreDataRelationshipUpsertOne) SetMenuID(v string) *CoreDataRelationshipUpsertOne {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.SetMenuID(v)
	})
}

// UpdateMenuID sets the "menu_id" field to the value that was provided on create.
func (u *CoreDataRelationshipUpsertOne) UpdateMenuID() *CoreDataRelationshipUpsertOne {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.UpdateMenuID()
	})
}

// ClearMenuID clears the value of the "menu_id" field.
func (u *CoreDataRelationshipUpsertOne) ClearMenuID() *CoreDataRelationshipUpsertOne {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.ClearMenuID()
	})
}

// SetRoleID sets the "role_id" field.
func (u *CoreDataRelationshipUpsertOne) SetRoleID(v string) *CoreDataRelationshipUpsertOne {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.SetRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *CoreDataRelationshipUpsertOne) UpdateRoleID() *CoreDataRelationshipUpsertOne {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.UpdateRoleID()
	})
}

// ClearRoleID clears the value of the "role_id" field.
func (u *CoreDataRelationshipUpsertOne) ClearRoleID() *CoreDataRelationshipUpsertOne {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.ClearRoleID()
	})
}

// Exec executes the query.
func (u *CoreDataRelationshipUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoreDataRelationshipCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoreDataRelationshipUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CoreDataRelationshipUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CoreDataRelationshipUpsertOne.ID is not supported by MySQL driver. Use CoreDataRelationshipUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CoreDataRelationshipUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CoreDataRelationshipCreateBulk is the builder for creating many CoreDataRelationship entities in bulk.
type CoreDataRelationshipCreateBulk struct {
	config
	err      error
	builders []*CoreDataRelationshipCreate
	conflict []sql.ConflictOption
}

// Save creates the CoreDataRelationship entities in the database.
func (_c *CoreDataRelationshipCreateBulk) Save(ctx context.Context) ([]*CoreDataRelationship, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CoreDataRelationship, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CoreDataRelationshipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CoreDataRelationshipCreateBulk) SaveX(ctx context.Context) []*CoreDataRelationship {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CoreDataRelationshipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CoreDataRelationshipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoreDataRelationship.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoreDataRelationshipUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CoreDataRelationshipCreateBulk) OnConflict(opts ...sql.ConflictOption) *CoreDataRelationshipUpsertBulk {
	_c.conflict = opts
	return &CoreDataRelationshipUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoreDataRelationship.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CoreDataRelationshipCreateBulk) OnConflictColumns(columns ...string) *CoreDataRelationshipUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CoreDataRelationshipUpsertBulk{
		create: _c,
	}
}

// CoreDataRelationshipUpsertBulk is the builder for "upsert"-ing
// a bulk of CoreDataRelationship nodes.
type CoreDataRelationshipUpsertBulk struct {
	create *CoreDataRelationshipCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CoreDataRelationship.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coredatarelationship.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CoreDataRelationshipUpsertBulk) UpdateNewValues() *CoreDataRelationshipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(coredatarelationship.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(coredatarelationship.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CoreDataRelationship.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CoreDataRelationshipUpsertBulk) Ignore() *CoreDataRelationshipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoreDataRelationshipUpsertBulk) DoNothing() *CoreDataRelationshipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoreDataRelationshipCreateBulk.OnConflict
// documentation for more info.
func (u *CoreDataRelationshipUpsertBulk) Update(set func(*CoreDataRelationshipUpsert)) *CoreDataRelationshipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoreDataRelationshipUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoreDataRelationshipUpsertBulk) SetUpdatedAt(v time.Time) *CoreDataRelationshipUpsertBulk {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoreDataRelationshipUpsertBulk) UpdateUpdatedAt() *CoreDataRelationshipUpsertBulk {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoreDataRelationshipUpsertBulk) SetDeletedAt(v time.Time) *CoreDataRelationshipUpsertBulk {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoreDataRelationshipUpsertBulk) UpdateDeletedAt() *CoreDataRelationshipUpsertBulk {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CoreDataRelationshipUpsertBulk) ClearDeletedAt() *CoreDataRelationshipUpsertBulk {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDataRelationshipType sets the "data_relationship_type" field.
func (u *CoreDataRelationshipUpsertBulk) SetDataRelationshipType(v common.DataRelationshipType) *CoreDataRelationshipUpsertBulk {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.SetDataRelationshipType(v)
	})
}

// AddDataRelationshipType adds v to the "data_relationship_type" field.
func (u *CoreDataRelationshipUpsertBulk) AddDataRelationshipType(v common.DataRelationshipType) *CoreDataRelationshipUpsertBulk {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.AddDataRelationshipType(v)
	})
}

// UpdateDataRelationshipType sets the "data_relationship_type" field to the value that was provided on create.
func (u *CoreDataRelationshipUpsertBulk) UpdateDataRelationshipType() *CoreDataRelationshipUpsertBulk {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.UpdateDataRelationshipType()
	})
}

// ClearDataRelationshipType clears the value of the "data_relationship_type" field.
func (u *CoreDataRelationshipUpsertBulk) ClearDataRelationshipType() *CoreDataRelationshipUpsertBulk {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.ClearDataRelationshipType()
	})
}

// SetMenuID sets the "menu_id" field.
func (u *CoreDataRelationshipUpsertBulk) SetMenuID(v string) *CoreDataRelationshipUpsertBulk {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.SetMenuID(v)
	})
}

// UpdateMenuID sets the "menu_id" field to the value that was provided on create.
func (u *CoreDataRelationshipUpsertBulk) UpdateMenuID() *CoreDataRelationshipUpsertBulk {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.UpdateMenuID()
	})
}

// ClearMenuID clears the value of the "menu_id" field.
func (u *CoreDataRelationshipUpsertBulk) ClearMenuID() *CoreDataRelationshipUpsertBulk {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.ClearMenuID()
	})
}

// SetRoleID sets the "role_id" field.
func (u *CoreDataRelationshipUpsertBulk) SetRoleID(v string) *CoreDataRelationshipUpsertBulk {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.SetRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *CoreDataRelationshipUpsertBulk) UpdateRoleID() *CoreDataRelationshipUpsertBulk {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.UpdateRoleID()
	})
}

// ClearRoleID clears the value of the "role_id" field.
func (u *CoreDataRelationshipUpsertBulk) ClearRoleID() *CoreDataRelationshipUpsertBulk {
	return u.Update(func(s *CoreDataRelationshipUpsert) {
		s.ClearRoleID()
	})
}

// Exec executes the query.
func (u *CoreDataRelationshipUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CoreDataRelationshipCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoreDataRelationshipCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoreDataRelationshipUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
