// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coreupstream"
	"github.com/lyonmu/quebec/pkg/constant"
)

// 上游服务信息表
type CoreUpstream struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID string `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 上游服务名称
	Name string `json:"name,omitempty"`
	// 上游服务描述
	Description string `json:"description,omitempty"`
	// 负载均衡策略: 1-ROUND_ROBIN 2-LEAST_REQUEST 3-RANDOM 4-RING_HASH 5-MAGLEV
	LbPolicy constant.ProxyLbPolicy `json:"lb_policy,omitempty"`
	// 连接超时(毫秒)
	ConnectTimeoutMs int `json:"connect_timeout_ms,omitempty"`
	// 最大连接数
	MaxConnections int `json:"max_connections,omitempty"`
	// 最大等待请求数
	MaxPendingRequests int `json:"max_pending_requests,omitempty"`
	// 最大请求数
	MaxRequests int `json:"max_requests,omitempty"`
	// 最大重试次数
	MaxRetries int `json:"max_retries,omitempty"`
	// 状态 [1-启用 2-禁用]
	Status       constant.YesOrNo `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CoreUpstream) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case coreupstream.FieldLbPolicy, coreupstream.FieldConnectTimeoutMs, coreupstream.FieldMaxConnections, coreupstream.FieldMaxPendingRequests, coreupstream.FieldMaxRequests, coreupstream.FieldMaxRetries, coreupstream.FieldStatus:
			values[i] = new(sql.NullInt64)
		case coreupstream.FieldID, coreupstream.FieldName, coreupstream.FieldDescription:
			values[i] = new(sql.NullString)
		case coreupstream.FieldCreatedAt, coreupstream.FieldUpdatedAt, coreupstream.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CoreUpstream fields.
func (_m *CoreUpstream) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case coreupstream.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case coreupstream.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case coreupstream.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case coreupstream.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case coreupstream.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case coreupstream.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case coreupstream.FieldLbPolicy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lb_policy", values[i])
			} else if value.Valid {
				_m.LbPolicy = constant.ProxyLbPolicy(value.Int64)
			}
		case coreupstream.FieldConnectTimeoutMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field connect_timeout_ms", values[i])
			} else if value.Valid {
				_m.ConnectTimeoutMs = int(value.Int64)
			}
		case coreupstream.FieldMaxConnections:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_connections", values[i])
			} else if value.Valid {
				_m.MaxConnections = int(value.Int64)
			}
		case coreupstream.FieldMaxPendingRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_pending_requests", values[i])
			} else if value.Valid {
				_m.MaxPendingRequests = int(value.Int64)
			}
		case coreupstream.FieldMaxRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_requests", values[i])
			} else if value.Valid {
				_m.MaxRequests = int(value.Int64)
			}
		case coreupstream.FieldMaxRetries:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_retries", values[i])
			} else if value.Valid {
				_m.MaxRetries = int(value.Int64)
			}
		case coreupstream.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = constant.YesOrNo(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CoreUpstream.
// This includes values selected through modifiers, order, etc.
func (_m *CoreUpstream) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CoreUpstream.
// Note that you need to call CoreUpstream.Unwrap() before calling this method if this CoreUpstream
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CoreUpstream) Update() *CoreUpstreamUpdateOne {
	return NewCoreUpstreamClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CoreUpstream entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CoreUpstream) Unwrap() *CoreUpstream {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CoreUpstream is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CoreUpstream) String() string {
	var builder strings.Builder
	builder.WriteString("CoreUpstream(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("lb_policy=")
	builder.WriteString(fmt.Sprintf("%v", _m.LbPolicy))
	builder.WriteString(", ")
	builder.WriteString("connect_timeout_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConnectTimeoutMs))
	builder.WriteString(", ")
	builder.WriteString("max_connections=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxConnections))
	builder.WriteString(", ")
	builder.WriteString("max_pending_requests=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxPendingRequests))
	builder.WriteString(", ")
	builder.WriteString("max_requests=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxRequests))
	builder.WriteString(", ")
	builder.WriteString("max_retries=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxRetries))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// CoreUpstreams is a parsable slice of CoreUpstream.
type CoreUpstreams []*CoreUpstream
