// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coreupstream"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/predicate"
	"github.com/lyonmu/quebec/pkg/constant"
)

// CoreUpstreamUpdate is the builder for updating CoreUpstream entities.
type CoreUpstreamUpdate struct {
	config
	hooks     []Hook
	mutation  *CoreUpstreamMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CoreUpstreamUpdate builder.
func (_u *CoreUpstreamUpdate) Where(ps ...predicate.CoreUpstream) *CoreUpstreamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CoreUpstreamUpdate) SetUpdatedAt(v time.Time) *CoreUpstreamUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CoreUpstreamUpdate) SetDeletedAt(v time.Time) *CoreUpstreamUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CoreUpstreamUpdate) SetNillableDeletedAt(v *time.Time) *CoreUpstreamUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CoreUpstreamUpdate) ClearDeletedAt() *CoreUpstreamUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *CoreUpstreamUpdate) SetName(v string) *CoreUpstreamUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CoreUpstreamUpdate) SetNillableName(v *string) *CoreUpstreamUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *CoreUpstreamUpdate) ClearName() *CoreUpstreamUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *CoreUpstreamUpdate) SetDescription(v string) *CoreUpstreamUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CoreUpstreamUpdate) SetNillableDescription(v *string) *CoreUpstreamUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CoreUpstreamUpdate) ClearDescription() *CoreUpstreamUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetLbPolicy sets the "lb_policy" field.
func (_u *CoreUpstreamUpdate) SetLbPolicy(v constant.ProxyLbPolicy) *CoreUpstreamUpdate {
	_u.mutation.ResetLbPolicy()
	_u.mutation.SetLbPolicy(v)
	return _u
}

// SetNillableLbPolicy sets the "lb_policy" field if the given value is not nil.
func (_u *CoreUpstreamUpdate) SetNillableLbPolicy(v *constant.ProxyLbPolicy) *CoreUpstreamUpdate {
	if v != nil {
		_u.SetLbPolicy(*v)
	}
	return _u
}

// AddLbPolicy adds value to the "lb_policy" field.
func (_u *CoreUpstreamUpdate) AddLbPolicy(v constant.ProxyLbPolicy) *CoreUpstreamUpdate {
	_u.mutation.AddLbPolicy(v)
	return _u
}

// ClearLbPolicy clears the value of the "lb_policy" field.
func (_u *CoreUpstreamUpdate) ClearLbPolicy() *CoreUpstreamUpdate {
	_u.mutation.ClearLbPolicy()
	return _u
}

// SetConnectTimeoutMs sets the "connect_timeout_ms" field.
func (_u *CoreUpstreamUpdate) SetConnectTimeoutMs(v int) *CoreUpstreamUpdate {
	_u.mutation.ResetConnectTimeoutMs()
	_u.mutation.SetConnectTimeoutMs(v)
	return _u
}

// SetNillableConnectTimeoutMs sets the "connect_timeout_ms" field if the given value is not nil.
func (_u *CoreUpstreamUpdate) SetNillableConnectTimeoutMs(v *int) *CoreUpstreamUpdate {
	if v != nil {
		_u.SetConnectTimeoutMs(*v)
	}
	return _u
}

// AddConnectTimeoutMs adds value to the "connect_timeout_ms" field.
func (_u *CoreUpstreamUpdate) AddConnectTimeoutMs(v int) *CoreUpstreamUpdate {
	_u.mutation.AddConnectTimeoutMs(v)
	return _u
}

// ClearConnectTimeoutMs clears the value of the "connect_timeout_ms" field.
func (_u *CoreUpstreamUpdate) ClearConnectTimeoutMs() *CoreUpstreamUpdate {
	_u.mutation.ClearConnectTimeoutMs()
	return _u
}

// SetMaxConnections sets the "max_connections" field.
func (_u *CoreUpstreamUpdate) SetMaxConnections(v int) *CoreUpstreamUpdate {
	_u.mutation.ResetMaxConnections()
	_u.mutation.SetMaxConnections(v)
	return _u
}

// SetNillableMaxConnections sets the "max_connections" field if the given value is not nil.
func (_u *CoreUpstreamUpdate) SetNillableMaxConnections(v *int) *CoreUpstreamUpdate {
	if v != nil {
		_u.SetMaxConnections(*v)
	}
	return _u
}

// AddMaxConnections adds value to the "max_connections" field.
func (_u *CoreUpstreamUpdate) AddMaxConnections(v int) *CoreUpstreamUpdate {
	_u.mutation.AddMaxConnections(v)
	return _u
}

// ClearMaxConnections clears the value of the "max_connections" field.
func (_u *CoreUpstreamUpdate) ClearMaxConnections() *CoreUpstreamUpdate {
	_u.mutation.ClearMaxConnections()
	return _u
}

// SetMaxPendingRequests sets the "max_pending_requests" field.
func (_u *CoreUpstreamUpdate) SetMaxPendingRequests(v int) *CoreUpstreamUpdate {
	_u.mutation.ResetMaxPendingRequests()
	_u.mutation.SetMaxPendingRequests(v)
	return _u
}

// SetNillableMaxPendingRequests sets the "max_pending_requests" field if the given value is not nil.
func (_u *CoreUpstreamUpdate) SetNillableMaxPendingRequests(v *int) *CoreUpstreamUpdate {
	if v != nil {
		_u.SetMaxPendingRequests(*v)
	}
	return _u
}

// AddMaxPendingRequests adds value to the "max_pending_requests" field.
func (_u *CoreUpstreamUpdate) AddMaxPendingRequests(v int) *CoreUpstreamUpdate {
	_u.mutation.AddMaxPendingRequests(v)
	return _u
}

// ClearMaxPendingRequests clears the value of the "max_pending_requests" field.
func (_u *CoreUpstreamUpdate) ClearMaxPendingRequests() *CoreUpstreamUpdate {
	_u.mutation.ClearMaxPendingRequests()
	return _u
}

// SetMaxRequests sets the "max_requests" field.
func (_u *CoreUpstreamUpdate) SetMaxRequests(v int) *CoreUpstreamUpdate {
	_u.mutation.ResetMaxRequests()
	_u.mutation.SetMaxRequests(v)
	return _u
}

// SetNillableMaxRequests sets the "max_requests" field if the given value is not nil.
func (_u *CoreUpstreamUpdate) SetNillableMaxRequests(v *int) *CoreUpstreamUpdate {
	if v != nil {
		_u.SetMaxRequests(*v)
	}
	return _u
}

// AddMaxRequests adds value to the "max_requests" field.
func (_u *CoreUpstreamUpdate) AddMaxRequests(v int) *CoreUpstreamUpdate {
	_u.mutation.AddMaxRequests(v)
	return _u
}

// ClearMaxRequests clears the value of the "max_requests" field.
func (_u *CoreUpstreamUpdate) ClearMaxRequests() *CoreUpstreamUpdate {
	_u.mutation.ClearMaxRequests()
	return _u
}

// SetMaxRetries sets the "max_retries" field.
func (_u *CoreUpstreamUpdate) SetMaxRetries(v int) *CoreUpstreamUpdate {
	_u.mutation.ResetMaxRetries()
	_u.mutation.SetMaxRetries(v)
	return _u
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (_u *CoreUpstreamUpdate) SetNillableMaxRetries(v *int) *CoreUpstreamUpdate {
	if v != nil {
		_u.SetMaxRetries(*v)
	}
	return _u
}

// AddMaxRetries adds value to the "max_retries" field.
func (_u *CoreUpstreamUpdate) AddMaxRetries(v int) *CoreUpstreamUpdate {
	_u.mutation.AddMaxRetries(v)
	return _u
}

// ClearMaxRetries clears the value of the "max_retries" field.
func (_u *CoreUpstreamUpdate) ClearMaxRetries() *CoreUpstreamUpdate {
	_u.mutation.ClearMaxRetries()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CoreUpstreamUpdate) SetStatus(v constant.YesOrNo) *CoreUpstreamUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CoreUpstreamUpdate) SetNillableStatus(v *constant.YesOrNo) *CoreUpstreamUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *CoreUpstreamUpdate) AddStatus(v constant.YesOrNo) *CoreUpstreamUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *CoreUpstreamUpdate) ClearStatus() *CoreUpstreamUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// Mutation returns the CoreUpstreamMutation object of the builder.
func (_u *CoreUpstreamUpdate) Mutation() *CoreUpstreamMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CoreUpstreamUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoreUpstreamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CoreUpstreamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoreUpstreamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CoreUpstreamUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if coreupstream.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized coreupstream.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := coreupstream.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CoreUpstreamUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CoreUpstreamUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CoreUpstreamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(coreupstream.Table, coreupstream.Columns, sqlgraph.NewFieldSpec(coreupstream.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(coreupstream.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(coreupstream.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(coreupstream.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(coreupstream.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(coreupstream.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(coreupstream.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(coreupstream.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.LbPolicy(); ok {
		_spec.SetField(coreupstream.FieldLbPolicy, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedLbPolicy(); ok {
		_spec.AddField(coreupstream.FieldLbPolicy, field.TypeInt8, value)
	}
	if _u.mutation.LbPolicyCleared() {
		_spec.ClearField(coreupstream.FieldLbPolicy, field.TypeInt8)
	}
	if value, ok := _u.mutation.ConnectTimeoutMs(); ok {
		_spec.SetField(coreupstream.FieldConnectTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConnectTimeoutMs(); ok {
		_spec.AddField(coreupstream.FieldConnectTimeoutMs, field.TypeInt, value)
	}
	if _u.mutation.ConnectTimeoutMsCleared() {
		_spec.ClearField(coreupstream.FieldConnectTimeoutMs, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxConnections(); ok {
		_spec.SetField(coreupstream.FieldMaxConnections, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxConnections(); ok {
		_spec.AddField(coreupstream.FieldMaxConnections, field.TypeInt, value)
	}
	if _u.mutation.MaxConnectionsCleared() {
		_spec.ClearField(coreupstream.FieldMaxConnections, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxPendingRequests(); ok {
		_spec.SetField(coreupstream.FieldMaxPendingRequests, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxPendingRequests(); ok {
		_spec.AddField(coreupstream.FieldMaxPendingRequests, field.TypeInt, value)
	}
	if _u.mutation.MaxPendingRequestsCleared() {
		_spec.ClearField(coreupstream.FieldMaxPendingRequests, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxRequests(); ok {
		_spec.SetField(coreupstream.FieldMaxRequests, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRequests(); ok {
		_spec.AddField(coreupstream.FieldMaxRequests, field.TypeInt, value)
	}
	if _u.mutation.MaxRequestsCleared() {
		_spec.ClearField(coreupstream.FieldMaxRequests, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxRetries(); ok {
		_spec.SetField(coreupstream.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRetries(); ok {
		_spec.AddField(coreupstream.FieldMaxRetries, field.TypeInt, value)
	}
	if _u.mutation.MaxRetriesCleared() {
		_spec.ClearField(coreupstream.FieldMaxRetries, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(coreupstream.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(coreupstream.FieldStatus, field.TypeInt8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(coreupstream.FieldStatus, field.TypeInt8)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coreupstream.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CoreUpstreamUpdateOne is the builder for updating a single CoreUpstream entity.
type CoreUpstreamUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CoreUpstreamMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CoreUpstreamUpdateOne) SetUpdatedAt(v time.Time) *CoreUpstreamUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CoreUpstreamUpdateOne) SetDeletedAt(v time.Time) *CoreUpstreamUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CoreUpstreamUpdateOne) SetNillableDeletedAt(v *time.Time) *CoreUpstreamUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CoreUpstreamUpdateOne) ClearDeletedAt() *CoreUpstreamUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *CoreUpstreamUpdateOne) SetName(v string) *CoreUpstreamUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CoreUpstreamUpdateOne) SetNillableName(v *string) *CoreUpstreamUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *CoreUpstreamUpdateOne) ClearName() *CoreUpstreamUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *CoreUpstreamUpdateOne) SetDescription(v string) *CoreUpstreamUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CoreUpstreamUpdateOne) SetNillableDescription(v *string) *CoreUpstreamUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CoreUpstreamUpdateOne) ClearDescription() *CoreUpstreamUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetLbPolicy sets the "lb_policy" field.
func (_u *CoreUpstreamUpdateOne) SetLbPolicy(v constant.ProxyLbPolicy) *CoreUpstreamUpdateOne {
	_u.mutation.ResetLbPolicy()
	_u.mutation.SetLbPolicy(v)
	return _u
}

// SetNillableLbPolicy sets the "lb_policy" field if the given value is not nil.
func (_u *CoreUpstreamUpdateOne) SetNillableLbPolicy(v *constant.ProxyLbPolicy) *CoreUpstreamUpdateOne {
	if v != nil {
		_u.SetLbPolicy(*v)
	}
	return _u
}

// AddLbPolicy adds value to the "lb_policy" field.
func (_u *CoreUpstreamUpdateOne) AddLbPolicy(v constant.ProxyLbPolicy) *CoreUpstreamUpdateOne {
	_u.mutation.AddLbPolicy(v)
	return _u
}

// ClearLbPolicy clears the value of the "lb_policy" field.
func (_u *CoreUpstreamUpdateOne) ClearLbPolicy() *CoreUpstreamUpdateOne {
	_u.mutation.ClearLbPolicy()
	return _u
}

// SetConnectTimeoutMs sets the "connect_timeout_ms" field.
func (_u *CoreUpstreamUpdateOne) SetConnectTimeoutMs(v int) *CoreUpstreamUpdateOne {
	_u.mutation.ResetConnectTimeoutMs()
	_u.mutation.SetConnectTimeoutMs(v)
	return _u
}

// SetNillableConnectTimeoutMs sets the "connect_timeout_ms" field if the given value is not nil.
func (_u *CoreUpstreamUpdateOne) SetNillableConnectTimeoutMs(v *int) *CoreUpstreamUpdateOne {
	if v != nil {
		_u.SetConnectTimeoutMs(*v)
	}
	return _u
}

// AddConnectTimeoutMs adds value to the "connect_timeout_ms" field.
func (_u *CoreUpstreamUpdateOne) AddConnectTimeoutMs(v int) *CoreUpstreamUpdateOne {
	_u.mutation.AddConnectTimeoutMs(v)
	return _u
}

// ClearConnectTimeoutMs clears the value of the "connect_timeout_ms" field.
func (_u *CoreUpstreamUpdateOne) ClearConnectTimeoutMs() *CoreUpstreamUpdateOne {
	_u.mutation.ClearConnectTimeoutMs()
	return _u
}

// SetMaxConnections sets the "max_connections" field.
func (_u *CoreUpstreamUpdateOne) SetMaxConnections(v int) *CoreUpstreamUpdateOne {
	_u.mutation.ResetMaxConnections()
	_u.mutation.SetMaxConnections(v)
	return _u
}

// SetNillableMaxConnections sets the "max_connections" field if the given value is not nil.
func (_u *CoreUpstreamUpdateOne) SetNillableMaxConnections(v *int) *CoreUpstreamUpdateOne {
	if v != nil {
		_u.SetMaxConnections(*v)
	}
	return _u
}

// AddMaxConnections adds value to the "max_connections" field.
func (_u *CoreUpstreamUpdateOne) AddMaxConnections(v int) *CoreUpstreamUpdateOne {
	_u.mutation.AddMaxConnections(v)
	return _u
}

// ClearMaxConnections clears the value of the "max_connections" field.
func (_u *CoreUpstreamUpdateOne) ClearMaxConnections() *CoreUpstreamUpdateOne {
	_u.mutation.ClearMaxConnections()
	return _u
}

// SetMaxPendingRequests sets the "max_pending_requests" field.
func (_u *CoreUpstreamUpdateOne) SetMaxPendingRequests(v int) *CoreUpstreamUpdateOne {
	_u.mutation.ResetMaxPendingRequests()
	_u.mutation.SetMaxPendingRequests(v)
	return _u
}

// SetNillableMaxPendingRequests sets the "max_pending_requests" field if the given value is not nil.
func (_u *CoreUpstreamUpdateOne) SetNillableMaxPendingRequests(v *int) *CoreUpstreamUpdateOne {
	if v != nil {
		_u.SetMaxPendingRequests(*v)
	}
	return _u
}

// AddMaxPendingRequests adds value to the "max_pending_requests" field.
func (_u *CoreUpstreamUpdateOne) AddMaxPendingRequests(v int) *CoreUpstreamUpdateOne {
	_u.mutation.AddMaxPendingRequests(v)
	return _u
}

// ClearMaxPendingRequests clears the value of the "max_pending_requests" field.
func (_u *CoreUpstreamUpdateOne) ClearMaxPendingRequests() *CoreUpstreamUpdateOne {
	_u.mutation.ClearMaxPendingRequests()
	return _u
}

// SetMaxRequests sets the "max_requests" field.
func (_u *CoreUpstreamUpdateOne) SetMaxRequests(v int) *CoreUpstreamUpdateOne {
	_u.mutation.ResetMaxRequests()
	_u.mutation.SetMaxRequests(v)
	return _u
}

// SetNillableMaxRequests sets the "max_requests" field if the given value is not nil.
func (_u *CoreUpstreamUpdateOne) SetNillableMaxRequests(v *int) *CoreUpstreamUpdateOne {
	if v != nil {
		_u.SetMaxRequests(*v)
	}
	return _u
}

// AddMaxRequests adds value to the "max_requests" field.
func (_u *CoreUpstreamUpdateOne) AddMaxRequests(v int) *CoreUpstreamUpdateOne {
	_u.mutation.AddMaxRequests(v)
	return _u
}

// ClearMaxRequests clears the value of the "max_requests" field.
func (_u *CoreUpstreamUpdateOne) ClearMaxRequests() *CoreUpstreamUpdateOne {
	_u.mutation.ClearMaxRequests()
	return _u
}

// SetMaxRetries sets the "max_retries" field.
func (_u *CoreUpstreamUpdateOne) SetMaxRetries(v int) *CoreUpstreamUpdateOne {
	_u.mutation.ResetMaxRetries()
	_u.mutation.SetMaxRetries(v)
	return _u
}

// SetNillableMaxRetries sets the "max_retries" field if the given value is not nil.
func (_u *CoreUpstreamUpdateOne) SetNillableMaxRetries(v *int) *CoreUpstreamUpdateOne {
	if v != nil {
		_u.SetMaxRetries(*v)
	}
	return _u
}

// AddMaxRetries adds value to the "max_retries" field.
func (_u *CoreUpstreamUpdateOne) AddMaxRetries(v int) *CoreUpstreamUpdateOne {
	_u.mutation.AddMaxRetries(v)
	return _u
}

// ClearMaxRetries clears the value of the "max_retries" field.
func (_u *CoreUpstreamUpdateOne) ClearMaxRetries() *CoreUpstreamUpdateOne {
	_u.mutation.ClearMaxRetries()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CoreUpstreamUpdateOne) SetStatus(v constant.YesOrNo) *CoreUpstreamUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CoreUpstreamUpdateOne) SetNillableStatus(v *constant.YesOrNo) *CoreUpstreamUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *CoreUpstreamUpdateOne) AddStatus(v constant.YesOrNo) *CoreUpstreamUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *CoreUpstreamUpdateOne) ClearStatus() *CoreUpstreamUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// Mutation returns the CoreUpstreamMutation object of the builder.
func (_u *CoreUpstreamUpdateOne) Mutation() *CoreUpstreamMutation {
	return _u.mutation
}

// Where appends a list predicates to the CoreUpstreamUpdate builder.
func (_u *CoreUpstreamUpdateOne) Where(ps ...predicate.CoreUpstream) *CoreUpstreamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CoreUpstreamUpdateOne) Select(field string, fields ...string) *CoreUpstreamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CoreUpstream entity.
func (_u *CoreUpstreamUpdateOne) Save(ctx context.Context) (*CoreUpstream, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoreUpstreamUpdateOne) SaveX(ctx context.Context) *CoreUpstream {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CoreUpstreamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoreUpstreamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CoreUpstreamUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if coreupstream.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized coreupstream.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := coreupstream.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CoreUpstreamUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CoreUpstreamUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CoreUpstreamUpdateOne) sqlSave(ctx context.Context) (_node *CoreUpstream, err error) {
	_spec := sqlgraph.NewUpdateSpec(coreupstream.Table, coreupstream.Columns, sqlgraph.NewFieldSpec(coreupstream.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CoreUpstream.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coreupstream.FieldID)
		for _, f := range fields {
			if !coreupstream.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != coreupstream.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(coreupstream.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(coreupstream.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(coreupstream.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(coreupstream.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(coreupstream.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(coreupstream.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(coreupstream.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.LbPolicy(); ok {
		_spec.SetField(coreupstream.FieldLbPolicy, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedLbPolicy(); ok {
		_spec.AddField(coreupstream.FieldLbPolicy, field.TypeInt8, value)
	}
	if _u.mutation.LbPolicyCleared() {
		_spec.ClearField(coreupstream.FieldLbPolicy, field.TypeInt8)
	}
	if value, ok := _u.mutation.ConnectTimeoutMs(); ok {
		_spec.SetField(coreupstream.FieldConnectTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConnectTimeoutMs(); ok {
		_spec.AddField(coreupstream.FieldConnectTimeoutMs, field.TypeInt, value)
	}
	if _u.mutation.ConnectTimeoutMsCleared() {
		_spec.ClearField(coreupstream.FieldConnectTimeoutMs, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxConnections(); ok {
		_spec.SetField(coreupstream.FieldMaxConnections, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxConnections(); ok {
		_spec.AddField(coreupstream.FieldMaxConnections, field.TypeInt, value)
	}
	if _u.mutation.MaxConnectionsCleared() {
		_spec.ClearField(coreupstream.FieldMaxConnections, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxPendingRequests(); ok {
		_spec.SetField(coreupstream.FieldMaxPendingRequests, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxPendingRequests(); ok {
		_spec.AddField(coreupstream.FieldMaxPendingRequests, field.TypeInt, value)
	}
	if _u.mutation.MaxPendingRequestsCleared() {
		_spec.ClearField(coreupstream.FieldMaxPendingRequests, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxRequests(); ok {
		_spec.SetField(coreupstream.FieldMaxRequests, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRequests(); ok {
		_spec.AddField(coreupstream.FieldMaxRequests, field.TypeInt, value)
	}
	if _u.mutation.MaxRequestsCleared() {
		_spec.ClearField(coreupstream.FieldMaxRequests, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxRetries(); ok {
		_spec.SetField(coreupstream.FieldMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRetries(); ok {
		_spec.AddField(coreupstream.FieldMaxRetries, field.TypeInt, value)
	}
	if _u.mutation.MaxRetriesCleared() {
		_spec.ClearField(coreupstream.FieldMaxRetries, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(coreupstream.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(coreupstream.FieldStatus, field.TypeInt8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(coreupstream.FieldStatus, field.TypeInt8)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &CoreUpstream{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coreupstream.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
