// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coregatewayhttproute"
	"github.com/lyonmu/quebec/pkg/constant"
)

// CoreGatewayHttpRouteCreate is the builder for creating a CoreGatewayHttpRoute entity.
type CoreGatewayHttpRouteCreate struct {
	config
	mutation *CoreGatewayHttpRouteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CoreGatewayHttpRouteCreate) SetCreatedAt(v time.Time) *CoreGatewayHttpRouteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CoreGatewayHttpRouteCreate) SetNillableCreatedAt(v *time.Time) *CoreGatewayHttpRouteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CoreGatewayHttpRouteCreate) SetUpdatedAt(v time.Time) *CoreGatewayHttpRouteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CoreGatewayHttpRouteCreate) SetNillableUpdatedAt(v *time.Time) *CoreGatewayHttpRouteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *CoreGatewayHttpRouteCreate) SetDeletedAt(v time.Time) *CoreGatewayHttpRouteCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *CoreGatewayHttpRouteCreate) SetNillableDeletedAt(v *time.Time) *CoreGatewayHttpRouteCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *CoreGatewayHttpRouteCreate) SetName(v string) *CoreGatewayHttpRouteCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *CoreGatewayHttpRouteCreate) SetNillableName(v *string) *CoreGatewayHttpRouteCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *CoreGatewayHttpRouteCreate) SetDescription(v string) *CoreGatewayHttpRouteCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CoreGatewayHttpRouteCreate) SetNillableDescription(v *string) *CoreGatewayHttpRouteCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetMatchType sets the "match_type" field.
func (_c *CoreGatewayHttpRouteCreate) SetMatchType(v constant.ProxyHttpRouteMatchType) *CoreGatewayHttpRouteCreate {
	_c.mutation.SetMatchType(v)
	return _c
}

// SetNillableMatchType sets the "match_type" field if the given value is not nil.
func (_c *CoreGatewayHttpRouteCreate) SetNillableMatchType(v *constant.ProxyHttpRouteMatchType) *CoreGatewayHttpRouteCreate {
	if v != nil {
		_c.SetMatchType(*v)
	}
	return _c
}

// SetMatchPattern sets the "match_pattern" field.
func (_c *CoreGatewayHttpRouteCreate) SetMatchPattern(v string) *CoreGatewayHttpRouteCreate {
	_c.mutation.SetMatchPattern(v)
	return _c
}

// SetNillableMatchPattern sets the "match_pattern" field if the given value is not nil.
func (_c *CoreGatewayHttpRouteCreate) SetNillableMatchPattern(v *string) *CoreGatewayHttpRouteCreate {
	if v != nil {
		_c.SetMatchPattern(*v)
	}
	return _c
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_c *CoreGatewayHttpRouteCreate) SetTimeoutMs(v int) *CoreGatewayHttpRouteCreate {
	_c.mutation.SetTimeoutMs(v)
	return _c
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_c *CoreGatewayHttpRouteCreate) SetNillableTimeoutMs(v *int) *CoreGatewayHttpRouteCreate {
	if v != nil {
		_c.SetTimeoutMs(*v)
	}
	return _c
}

// SetEnablePathRewrite sets the "enable_path_rewrite" field.
func (_c *CoreGatewayHttpRouteCreate) SetEnablePathRewrite(v constant.YesOrNo) *CoreGatewayHttpRouteCreate {
	_c.mutation.SetEnablePathRewrite(v)
	return _c
}

// SetNillableEnablePathRewrite sets the "enable_path_rewrite" field if the given value is not nil.
func (_c *CoreGatewayHttpRouteCreate) SetNillableEnablePathRewrite(v *constant.YesOrNo) *CoreGatewayHttpRouteCreate {
	if v != nil {
		_c.SetEnablePathRewrite(*v)
	}
	return _c
}

// SetPathRewrite sets the "path_rewrite" field.
func (_c *CoreGatewayHttpRouteCreate) SetPathRewrite(v string) *CoreGatewayHttpRouteCreate {
	_c.mutation.SetPathRewrite(v)
	return _c
}

// SetNillablePathRewrite sets the "path_rewrite" field if the given value is not nil.
func (_c *CoreGatewayHttpRouteCreate) SetNillablePathRewrite(v *string) *CoreGatewayHttpRouteCreate {
	if v != nil {
		_c.SetPathRewrite(*v)
	}
	return _c
}

// SetEnableRedirect sets the "enable_redirect" field.
func (_c *CoreGatewayHttpRouteCreate) SetEnableRedirect(v constant.YesOrNo) *CoreGatewayHttpRouteCreate {
	_c.mutation.SetEnableRedirect(v)
	return _c
}

// SetNillableEnableRedirect sets the "enable_redirect" field if the given value is not nil.
func (_c *CoreGatewayHttpRouteCreate) SetNillableEnableRedirect(v *constant.YesOrNo) *CoreGatewayHttpRouteCreate {
	if v != nil {
		_c.SetEnableRedirect(*v)
	}
	return _c
}

// SetRedirectURL sets the "redirect_url" field.
func (_c *CoreGatewayHttpRouteCreate) SetRedirectURL(v string) *CoreGatewayHttpRouteCreate {
	_c.mutation.SetRedirectURL(v)
	return _c
}

// SetNillableRedirectURL sets the "redirect_url" field if the given value is not nil.
func (_c *CoreGatewayHttpRouteCreate) SetNillableRedirectURL(v *string) *CoreGatewayHttpRouteCreate {
	if v != nil {
		_c.SetRedirectURL(*v)
	}
	return _c
}

// SetRedirectCode sets the "redirect_code" field.
func (_c *CoreGatewayHttpRouteCreate) SetRedirectCode(v int) *CoreGatewayHttpRouteCreate {
	_c.mutation.SetRedirectCode(v)
	return _c
}

// SetNillableRedirectCode sets the "redirect_code" field if the given value is not nil.
func (_c *CoreGatewayHttpRouteCreate) SetNillableRedirectCode(v *int) *CoreGatewayHttpRouteCreate {
	if v != nil {
		_c.SetRedirectCode(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CoreGatewayHttpRouteCreate) SetStatus(v constant.YesOrNo) *CoreGatewayHttpRouteCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CoreGatewayHttpRouteCreate) SetNillableStatus(v *constant.YesOrNo) *CoreGatewayHttpRouteCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CoreGatewayHttpRouteCreate) SetID(v string) *CoreGatewayHttpRouteCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CoreGatewayHttpRouteCreate) SetNillableID(v *string) *CoreGatewayHttpRouteCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the CoreGatewayHttpRouteMutation object of the builder.
func (_c *CoreGatewayHttpRouteCreate) Mutation() *CoreGatewayHttpRouteMutation {
	return _c.mutation
}

// Save creates the CoreGatewayHttpRoute in the database.
func (_c *CoreGatewayHttpRouteCreate) Save(ctx context.Context) (*CoreGatewayHttpRoute, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CoreGatewayHttpRouteCreate) SaveX(ctx context.Context) *CoreGatewayHttpRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CoreGatewayHttpRouteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CoreGatewayHttpRouteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CoreGatewayHttpRouteCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if coregatewayhttproute.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized coregatewayhttproute.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := coregatewayhttproute.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if coregatewayhttproute.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized coregatewayhttproute.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := coregatewayhttproute.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.MatchType(); !ok {
		v := coregatewayhttproute.DefaultMatchType
		_c.mutation.SetMatchType(v)
	}
	if _, ok := _c.mutation.TimeoutMs(); !ok {
		v := coregatewayhttproute.DefaultTimeoutMs
		_c.mutation.SetTimeoutMs(v)
	}
	if _, ok := _c.mutation.EnablePathRewrite(); !ok {
		v := coregatewayhttproute.DefaultEnablePathRewrite
		_c.mutation.SetEnablePathRewrite(v)
	}
	if _, ok := _c.mutation.EnableRedirect(); !ok {
		v := coregatewayhttproute.DefaultEnableRedirect
		_c.mutation.SetEnableRedirect(v)
	}
	if _, ok := _c.mutation.RedirectCode(); !ok {
		v := coregatewayhttproute.DefaultRedirectCode
		_c.mutation.SetRedirectCode(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := coregatewayhttproute.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if coregatewayhttproute.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized coregatewayhttproute.DefaultID (forgotten import ent/runtime?)")
		}
		v := coregatewayhttproute.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *CoreGatewayHttpRouteCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CoreGatewayHttpRoute.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CoreGatewayHttpRoute.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := coregatewayhttproute.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "CoreGatewayHttpRoute.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CoreGatewayHttpRouteCreate) sqlSave(ctx context.Context) (*CoreGatewayHttpRoute, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CoreGatewayHttpRoute.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CoreGatewayHttpRouteCreate) createSpec() (*CoreGatewayHttpRoute, *sqlgraph.CreateSpec) {
	var (
		_node = &CoreGatewayHttpRoute{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(coregatewayhttproute.Table, sqlgraph.NewFieldSpec(coregatewayhttproute.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(coregatewayhttproute.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(coregatewayhttproute.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(coregatewayhttproute.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(coregatewayhttproute.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(coregatewayhttproute.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.MatchType(); ok {
		_spec.SetField(coregatewayhttproute.FieldMatchType, field.TypeInt8, value)
		_node.MatchType = value
	}
	if value, ok := _c.mutation.MatchPattern(); ok {
		_spec.SetField(coregatewayhttproute.FieldMatchPattern, field.TypeString, value)
		_node.MatchPattern = value
	}
	if value, ok := _c.mutation.TimeoutMs(); ok {
		_spec.SetField(coregatewayhttproute.FieldTimeoutMs, field.TypeInt, value)
		_node.TimeoutMs = value
	}
	if value, ok := _c.mutation.EnablePathRewrite(); ok {
		_spec.SetField(coregatewayhttproute.FieldEnablePathRewrite, field.TypeInt8, value)
		_node.EnablePathRewrite = value
	}
	if value, ok := _c.mutation.PathRewrite(); ok {
		_spec.SetField(coregatewayhttproute.FieldPathRewrite, field.TypeString, value)
		_node.PathRewrite = value
	}
	if value, ok := _c.mutation.EnableRedirect(); ok {
		_spec.SetField(coregatewayhttproute.FieldEnableRedirect, field.TypeInt8, value)
		_node.EnableRedirect = value
	}
	if value, ok := _c.mutation.RedirectURL(); ok {
		_spec.SetField(coregatewayhttproute.FieldRedirectURL, field.TypeString, value)
		_node.RedirectURL = value
	}
	if value, ok := _c.mutation.RedirectCode(); ok {
		_spec.SetField(coregatewayhttproute.FieldRedirectCode, field.TypeInt, value)
		_node.RedirectCode = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(coregatewayhttproute.FieldStatus, field.TypeInt8, value)
		_node.Status = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoreGatewayHttpRoute.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoreGatewayHttpRouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CoreGatewayHttpRouteCreate) OnConflict(opts ...sql.ConflictOption) *CoreGatewayHttpRouteUpsertOne {
	_c.conflict = opts
	return &CoreGatewayHttpRouteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoreGatewayHttpRoute.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CoreGatewayHttpRouteCreate) OnConflictColumns(columns ...string) *CoreGatewayHttpRouteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CoreGatewayHttpRouteUpsertOne{
		create: _c,
	}
}

type (
	// CoreGatewayHttpRouteUpsertOne is the builder for "upsert"-ing
	//  one CoreGatewayHttpRoute node.
	CoreGatewayHttpRouteUpsertOne struct {
		create *CoreGatewayHttpRouteCreate
	}

	// CoreGatewayHttpRouteUpsert is the "OnConflict" setter.
	CoreGatewayHttpRouteUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CoreGatewayHttpRouteUpsert) SetUpdatedAt(v time.Time) *CoreGatewayHttpRouteUpsert {
	u.Set(coregatewayhttproute.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsert) UpdateUpdatedAt() *CoreGatewayHttpRouteUpsert {
	u.SetExcluded(coregatewayhttproute.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoreGatewayHttpRouteUpsert) SetDeletedAt(v time.Time) *CoreGatewayHttpRouteUpsert {
	u.Set(coregatewayhttproute.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsert) UpdateDeletedAt() *CoreGatewayHttpRouteUpsert {
	u.SetExcluded(coregatewayhttproute.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CoreGatewayHttpRouteUpsert) ClearDeletedAt() *CoreGatewayHttpRouteUpsert {
	u.SetNull(coregatewayhttproute.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *CoreGatewayHttpRouteUpsert) SetName(v string) *CoreGatewayHttpRouteUpsert {
	u.Set(coregatewayhttproute.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsert) UpdateName() *CoreGatewayHttpRouteUpsert {
	u.SetExcluded(coregatewayhttproute.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *CoreGatewayHttpRouteUpsert) ClearName() *CoreGatewayHttpRouteUpsert {
	u.SetNull(coregatewayhttproute.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *CoreGatewayHttpRouteUpsert) SetDescription(v string) *CoreGatewayHttpRouteUpsert {
	u.Set(coregatewayhttproute.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsert) UpdateDescription() *CoreGatewayHttpRouteUpsert {
	u.SetExcluded(coregatewayhttproute.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *CoreGatewayHttpRouteUpsert) ClearDescription() *CoreGatewayHttpRouteUpsert {
	u.SetNull(coregatewayhttproute.FieldDescription)
	return u
}

// SetMatchType sets the "match_type" field.
func (u *CoreGatewayHttpRouteUpsert) SetMatchType(v constant.ProxyHttpRouteMatchType) *CoreGatewayHttpRouteUpsert {
	u.Set(coregatewayhttproute.FieldMatchType, v)
	return u
}

// UpdateMatchType sets the "match_type" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsert) UpdateMatchType() *CoreGatewayHttpRouteUpsert {
	u.SetExcluded(coregatewayhttproute.FieldMatchType)
	return u
}

// AddMatchType adds v to the "match_type" field.
func (u *CoreGatewayHttpRouteUpsert) AddMatchType(v constant.ProxyHttpRouteMatchType) *CoreGatewayHttpRouteUpsert {
	u.Add(coregatewayhttproute.FieldMatchType, v)
	return u
}

// ClearMatchType clears the value of the "match_type" field.
func (u *CoreGatewayHttpRouteUpsert) ClearMatchType() *CoreGatewayHttpRouteUpsert {
	u.SetNull(coregatewayhttproute.FieldMatchType)
	return u
}

// SetMatchPattern sets the "match_pattern" field.
func (u *CoreGatewayHttpRouteUpsert) SetMatchPattern(v string) *CoreGatewayHttpRouteUpsert {
	u.Set(coregatewayhttproute.FieldMatchPattern, v)
	return u
}

// UpdateMatchPattern sets the "match_pattern" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsert) UpdateMatchPattern() *CoreGatewayHttpRouteUpsert {
	u.SetExcluded(coregatewayhttproute.FieldMatchPattern)
	return u
}

// ClearMatchPattern clears the value of the "match_pattern" field.
func (u *CoreGatewayHttpRouteUpsert) ClearMatchPattern() *CoreGatewayHttpRouteUpsert {
	u.SetNull(coregatewayhttproute.FieldMatchPattern)
	return u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (u *CoreGatewayHttpRouteUpsert) SetTimeoutMs(v int) *CoreGatewayHttpRouteUpsert {
	u.Set(coregatewayhttproute.FieldTimeoutMs, v)
	return u
}

// UpdateTimeoutMs sets the "timeout_ms" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsert) UpdateTimeoutMs() *CoreGatewayHttpRouteUpsert {
	u.SetExcluded(coregatewayhttproute.FieldTimeoutMs)
	return u
}

// AddTimeoutMs adds v to the "timeout_ms" field.
func (u *CoreGatewayHttpRouteUpsert) AddTimeoutMs(v int) *CoreGatewayHttpRouteUpsert {
	u.Add(coregatewayhttproute.FieldTimeoutMs, v)
	return u
}

// ClearTimeoutMs clears the value of the "timeout_ms" field.
func (u *CoreGatewayHttpRouteUpsert) ClearTimeoutMs() *CoreGatewayHttpRouteUpsert {
	u.SetNull(coregatewayhttproute.FieldTimeoutMs)
	return u
}

// SetEnablePathRewrite sets the "enable_path_rewrite" field.
func (u *CoreGatewayHttpRouteUpsert) SetEnablePathRewrite(v constant.YesOrNo) *CoreGatewayHttpRouteUpsert {
	u.Set(coregatewayhttproute.FieldEnablePathRewrite, v)
	return u
}

// UpdateEnablePathRewrite sets the "enable_path_rewrite" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsert) UpdateEnablePathRewrite() *CoreGatewayHttpRouteUpsert {
	u.SetExcluded(coregatewayhttproute.FieldEnablePathRewrite)
	return u
}

// AddEnablePathRewrite adds v to the "enable_path_rewrite" field.
func (u *CoreGatewayHttpRouteUpsert) AddEnablePathRewrite(v constant.YesOrNo) *CoreGatewayHttpRouteUpsert {
	u.Add(coregatewayhttproute.FieldEnablePathRewrite, v)
	return u
}

// ClearEnablePathRewrite clears the value of the "enable_path_rewrite" field.
func (u *CoreGatewayHttpRouteUpsert) ClearEnablePathRewrite() *CoreGatewayHttpRouteUpsert {
	u.SetNull(coregatewayhttproute.FieldEnablePathRewrite)
	return u
}

// SetPathRewrite sets the "path_rewrite" field.
func (u *CoreGatewayHttpRouteUpsert) SetPathRewrite(v string) *CoreGatewayHttpRouteUpsert {
	u.Set(coregatewayhttproute.FieldPathRewrite, v)
	return u
}

// UpdatePathRewrite sets the "path_rewrite" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsert) UpdatePathRewrite() *CoreGatewayHttpRouteUpsert {
	u.SetExcluded(coregatewayhttproute.FieldPathRewrite)
	return u
}

// ClearPathRewrite clears the value of the "path_rewrite" field.
func (u *CoreGatewayHttpRouteUpsert) ClearPathRewrite() *CoreGatewayHttpRouteUpsert {
	u.SetNull(coregatewayhttproute.FieldPathRewrite)
	return u
}

// SetEnableRedirect sets the "enable_redirect" field.
func (u *CoreGatewayHttpRouteUpsert) SetEnableRedirect(v constant.YesOrNo) *CoreGatewayHttpRouteUpsert {
	u.Set(coregatewayhttproute.FieldEnableRedirect, v)
	return u
}

// UpdateEnableRedirect sets the "enable_redirect" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsert) UpdateEnableRedirect() *CoreGatewayHttpRouteUpsert {
	u.SetExcluded(coregatewayhttproute.FieldEnableRedirect)
	return u
}

// AddEnableRedirect adds v to the "enable_redirect" field.
func (u *CoreGatewayHttpRouteUpsert) AddEnableRedirect(v constant.YesOrNo) *CoreGatewayHttpRouteUpsert {
	u.Add(coregatewayhttproute.FieldEnableRedirect, v)
	return u
}

// ClearEnableRedirect clears the value of the "enable_redirect" field.
func (u *CoreGatewayHttpRouteUpsert) ClearEnableRedirect() *CoreGatewayHttpRouteUpsert {
	u.SetNull(coregatewayhttproute.FieldEnableRedirect)
	return u
}

// SetRedirectURL sets the "redirect_url" field.
func (u *CoreGatewayHttpRouteUpsert) SetRedirectURL(v string) *CoreGatewayHttpRouteUpsert {
	u.Set(coregatewayhttproute.FieldRedirectURL, v)
	return u
}

// UpdateRedirectURL sets the "redirect_url" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsert) UpdateRedirectURL() *CoreGatewayHttpRouteUpsert {
	u.SetExcluded(coregatewayhttproute.FieldRedirectURL)
	return u
}

// ClearRedirectURL clears the value of the "redirect_url" field.
func (u *CoreGatewayHttpRouteUpsert) ClearRedirectURL() *CoreGatewayHttpRouteUpsert {
	u.SetNull(coregatewayhttproute.FieldRedirectURL)
	return u
}

// SetRedirectCode sets the "redirect_code" field.
func (u *CoreGatewayHttpRouteUpsert) SetRedirectCode(v int) *CoreGatewayHttpRouteUpsert {
	u.Set(coregatewayhttproute.FieldRedirectCode, v)
	return u
}

// UpdateRedirectCode sets the "redirect_code" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsert) UpdateRedirectCode() *CoreGatewayHttpRouteUpsert {
	u.SetExcluded(coregatewayhttproute.FieldRedirectCode)
	return u
}

// AddRedirectCode adds v to the "redirect_code" field.
func (u *CoreGatewayHttpRouteUpsert) AddRedirectCode(v int) *CoreGatewayHttpRouteUpsert {
	u.Add(coregatewayhttproute.FieldRedirectCode, v)
	return u
}

// ClearRedirectCode clears the value of the "redirect_code" field.
func (u *CoreGatewayHttpRouteUpsert) ClearRedirectCode() *CoreGatewayHttpRouteUpsert {
	u.SetNull(coregatewayhttproute.FieldRedirectCode)
	return u
}

// SetStatus sets the "status" field.
func (u *CoreGatewayHttpRouteUpsert) SetStatus(v constant.YesOrNo) *CoreGatewayHttpRouteUpsert {
	u.Set(coregatewayhttproute.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsert) UpdateStatus() *CoreGatewayHttpRouteUpsert {
	u.SetExcluded(coregatewayhttproute.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *CoreGatewayHttpRouteUpsert) AddStatus(v constant.YesOrNo) *CoreGatewayHttpRouteUpsert {
	u.Add(coregatewayhttproute.FieldStatus, v)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *CoreGatewayHttpRouteUpsert) ClearStatus() *CoreGatewayHttpRouteUpsert {
	u.SetNull(coregatewayhttproute.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CoreGatewayHttpRoute.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coregatewayhttproute.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CoreGatewayHttpRouteUpsertOne) UpdateNewValues() *CoreGatewayHttpRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(coregatewayhttproute.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(coregatewayhttproute.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CoreGatewayHttpRoute.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CoreGatewayHttpRouteUpsertOne) Ignore() *CoreGatewayHttpRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoreGatewayHttpRouteUpsertOne) DoNothing() *CoreGatewayHttpRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoreGatewayHttpRouteCreate.OnConflict
// documentation for more info.
func (u *CoreGatewayHttpRouteUpsertOne) Update(set func(*CoreGatewayHttpRouteUpsert)) *CoreGatewayHttpRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoreGatewayHttpRouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoreGatewayHttpRouteUpsertOne) SetUpdatedAt(v time.Time) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertOne) UpdateUpdatedAt() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoreGatewayHttpRouteUpsertOne) SetDeletedAt(v time.Time) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertOne) UpdateDeletedAt() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CoreGatewayHttpRouteUpsertOne) ClearDeletedAt() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *CoreGatewayHttpRouteUpsertOne) SetName(v string) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertOne) UpdateName() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *CoreGatewayHttpRouteUpsertOne) ClearName() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearName()
	})
}

// SetDescription sets the "description" field.
func (u *CoreGatewayHttpRouteUpsertOne) SetDescription(v string) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertOne) UpdateDescription() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *CoreGatewayHttpRouteUpsertOne) ClearDescription() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearDescription()
	})
}

// SetMatchType sets the "match_type" field.
func (u *CoreGatewayHttpRouteUpsertOne) SetMatchType(v constant.ProxyHttpRouteMatchType) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetMatchType(v)
	})
}

// AddMatchType adds v to the "match_type" field.
func (u *CoreGatewayHttpRouteUpsertOne) AddMatchType(v constant.ProxyHttpRouteMatchType) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.AddMatchType(v)
	})
}

// UpdateMatchType sets the "match_type" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertOne) UpdateMatchType() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateMatchType()
	})
}

// ClearMatchType clears the value of the "match_type" field.
func (u *CoreGatewayHttpRouteUpsertOne) ClearMatchType() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearMatchType()
	})
}

// SetMatchPattern sets the "match_pattern" field.
func (u *CoreGatewayHttpRouteUpsertOne) SetMatchPattern(v string) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetMatchPattern(v)
	})
}

// UpdateMatchPattern sets the "match_pattern" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertOne) UpdateMatchPattern() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateMatchPattern()
	})
}

// ClearMatchPattern clears the value of the "match_pattern" field.
func (u *CoreGatewayHttpRouteUpsertOne) ClearMatchPattern() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearMatchPattern()
	})
}

// SetTimeoutMs sets the "timeout_ms" field.
func (u *CoreGatewayHttpRouteUpsertOne) SetTimeoutMs(v int) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetTimeoutMs(v)
	})
}

// AddTimeoutMs adds v to the "timeout_ms" field.
func (u *CoreGatewayHttpRouteUpsertOne) AddTimeoutMs(v int) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.AddTimeoutMs(v)
	})
}

// UpdateTimeoutMs sets the "timeout_ms" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertOne) UpdateTimeoutMs() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateTimeoutMs()
	})
}

// ClearTimeoutMs clears the value of the "timeout_ms" field.
func (u *CoreGatewayHttpRouteUpsertOne) ClearTimeoutMs() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearTimeoutMs()
	})
}

// SetEnablePathRewrite sets the "enable_path_rewrite" field.
func (u *CoreGatewayHttpRouteUpsertOne) SetEnablePathRewrite(v constant.YesOrNo) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetEnablePathRewrite(v)
	})
}

// AddEnablePathRewrite adds v to the "enable_path_rewrite" field.
func (u *CoreGatewayHttpRouteUpsertOne) AddEnablePathRewrite(v constant.YesOrNo) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.AddEnablePathRewrite(v)
	})
}

// UpdateEnablePathRewrite sets the "enable_path_rewrite" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertOne) UpdateEnablePathRewrite() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateEnablePathRewrite()
	})
}

// ClearEnablePathRewrite clears the value of the "enable_path_rewrite" field.
func (u *CoreGatewayHttpRouteUpsertOne) ClearEnablePathRewrite() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearEnablePathRewrite()
	})
}

// SetPathRewrite sets the "path_rewrite" field.
func (u *CoreGatewayHttpRouteUpsertOne) SetPathRewrite(v string) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetPathRewrite(v)
	})
}

// UpdatePathRewrite sets the "path_rewrite" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertOne) UpdatePathRewrite() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdatePathRewrite()
	})
}

// ClearPathRewrite clears the value of the "path_rewrite" field.
func (u *CoreGatewayHttpRouteUpsertOne) ClearPathRewrite() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearPathRewrite()
	})
}

// SetEnableRedirect sets the "enable_redirect" field.
func (u *CoreGatewayHttpRouteUpsertOne) SetEnableRedirect(v constant.YesOrNo) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetEnableRedirect(v)
	})
}

// AddEnableRedirect adds v to the "enable_redirect" field.
func (u *CoreGatewayHttpRouteUpsertOne) AddEnableRedirect(v constant.YesOrNo) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.AddEnableRedirect(v)
	})
}

// UpdateEnableRedirect sets the "enable_redirect" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertOne) UpdateEnableRedirect() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateEnableRedirect()
	})
}

// ClearEnableRedirect clears the value of the "enable_redirect" field.
func (u *CoreGatewayHttpRouteUpsertOne) ClearEnableRedirect() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearEnableRedirect()
	})
}

// SetRedirectURL sets the "redirect_url" field.
func (u *CoreGatewayHttpRouteUpsertOne) SetRedirectURL(v string) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetRedirectURL(v)
	})
}

// UpdateRedirectURL sets the "redirect_url" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertOne) UpdateRedirectURL() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateRedirectURL()
	})
}

// ClearRedirectURL clears the value of the "redirect_url" field.
func (u *CoreGatewayHttpRouteUpsertOne) ClearRedirectURL() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearRedirectURL()
	})
}

// SetRedirectCode sets the "redirect_code" field.
func (u *CoreGatewayHttpRouteUpsertOne) SetRedirectCode(v int) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetRedirectCode(v)
	})
}

// AddRedirectCode adds v to the "redirect_code" field.
func (u *CoreGatewayHttpRouteUpsertOne) AddRedirectCode(v int) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.AddRedirectCode(v)
	})
}

// UpdateRedirectCode sets the "redirect_code" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertOne) UpdateRedirectCode() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateRedirectCode()
	})
}

// ClearRedirectCode clears the value of the "redirect_code" field.
func (u *CoreGatewayHttpRouteUpsertOne) ClearRedirectCode() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearRedirectCode()
	})
}

// SetStatus sets the "status" field.
func (u *CoreGatewayHttpRouteUpsertOne) SetStatus(v constant.YesOrNo) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *CoreGatewayHttpRouteUpsertOne) AddStatus(v constant.YesOrNo) *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertOne) UpdateStatus() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *CoreGatewayHttpRouteUpsertOne) ClearStatus() *CoreGatewayHttpRouteUpsertOne {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearStatus()
	})
}

// Exec executes the query.
func (u *CoreGatewayHttpRouteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoreGatewayHttpRouteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoreGatewayHttpRouteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CoreGatewayHttpRouteUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CoreGatewayHttpRouteUpsertOne.ID is not supported by MySQL driver. Use CoreGatewayHttpRouteUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CoreGatewayHttpRouteUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CoreGatewayHttpRouteCreateBulk is the builder for creating many CoreGatewayHttpRoute entities in bulk.
type CoreGatewayHttpRouteCreateBulk struct {
	config
	err      error
	builders []*CoreGatewayHttpRouteCreate
	conflict []sql.ConflictOption
}

// Save creates the CoreGatewayHttpRoute entities in the database.
func (_c *CoreGatewayHttpRouteCreateBulk) Save(ctx context.Context) ([]*CoreGatewayHttpRoute, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CoreGatewayHttpRoute, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CoreGatewayHttpRouteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CoreGatewayHttpRouteCreateBulk) SaveX(ctx context.Context) []*CoreGatewayHttpRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CoreGatewayHttpRouteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CoreGatewayHttpRouteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoreGatewayHttpRoute.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoreGatewayHttpRouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CoreGatewayHttpRouteCreateBulk) OnConflict(opts ...sql.ConflictOption) *CoreGatewayHttpRouteUpsertBulk {
	_c.conflict = opts
	return &CoreGatewayHttpRouteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoreGatewayHttpRoute.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CoreGatewayHttpRouteCreateBulk) OnConflictColumns(columns ...string) *CoreGatewayHttpRouteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CoreGatewayHttpRouteUpsertBulk{
		create: _c,
	}
}

// CoreGatewayHttpRouteUpsertBulk is the builder for "upsert"-ing
// a bulk of CoreGatewayHttpRoute nodes.
type CoreGatewayHttpRouteUpsertBulk struct {
	create *CoreGatewayHttpRouteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CoreGatewayHttpRoute.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coregatewayhttproute.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CoreGatewayHttpRouteUpsertBulk) UpdateNewValues() *CoreGatewayHttpRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(coregatewayhttproute.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(coregatewayhttproute.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CoreGatewayHttpRoute.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CoreGatewayHttpRouteUpsertBulk) Ignore() *CoreGatewayHttpRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoreGatewayHttpRouteUpsertBulk) DoNothing() *CoreGatewayHttpRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoreGatewayHttpRouteCreateBulk.OnConflict
// documentation for more info.
func (u *CoreGatewayHttpRouteUpsertBulk) Update(set func(*CoreGatewayHttpRouteUpsert)) *CoreGatewayHttpRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoreGatewayHttpRouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoreGatewayHttpRouteUpsertBulk) SetUpdatedAt(v time.Time) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertBulk) UpdateUpdatedAt() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoreGatewayHttpRouteUpsertBulk) SetDeletedAt(v time.Time) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertBulk) UpdateDeletedAt() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CoreGatewayHttpRouteUpsertBulk) ClearDeletedAt() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *CoreGatewayHttpRouteUpsertBulk) SetName(v string) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertBulk) UpdateName() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *CoreGatewayHttpRouteUpsertBulk) ClearName() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearName()
	})
}

// SetDescription sets the "description" field.
func (u *CoreGatewayHttpRouteUpsertBulk) SetDescription(v string) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertBulk) UpdateDescription() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *CoreGatewayHttpRouteUpsertBulk) ClearDescription() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearDescription()
	})
}

// SetMatchType sets the "match_type" field.
func (u *CoreGatewayHttpRouteUpsertBulk) SetMatchType(v constant.ProxyHttpRouteMatchType) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetMatchType(v)
	})
}

// AddMatchType adds v to the "match_type" field.
func (u *CoreGatewayHttpRouteUpsertBulk) AddMatchType(v constant.ProxyHttpRouteMatchType) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.AddMatchType(v)
	})
}

// UpdateMatchType sets the "match_type" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertBulk) UpdateMatchType() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateMatchType()
	})
}

// ClearMatchType clears the value of the "match_type" field.
func (u *CoreGatewayHttpRouteUpsertBulk) ClearMatchType() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearMatchType()
	})
}

// SetMatchPattern sets the "match_pattern" field.
func (u *CoreGatewayHttpRouteUpsertBulk) SetMatchPattern(v string) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetMatchPattern(v)
	})
}

// UpdateMatchPattern sets the "match_pattern" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertBulk) UpdateMatchPattern() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateMatchPattern()
	})
}

// ClearMatchPattern clears the value of the "match_pattern" field.
func (u *CoreGatewayHttpRouteUpsertBulk) ClearMatchPattern() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearMatchPattern()
	})
}

// SetTimeoutMs sets the "timeout_ms" field.
func (u *CoreGatewayHttpRouteUpsertBulk) SetTimeoutMs(v int) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetTimeoutMs(v)
	})
}

// AddTimeoutMs adds v to the "timeout_ms" field.
func (u *CoreGatewayHttpRouteUpsertBulk) AddTimeoutMs(v int) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.AddTimeoutMs(v)
	})
}

// UpdateTimeoutMs sets the "timeout_ms" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertBulk) UpdateTimeoutMs() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateTimeoutMs()
	})
}

// ClearTimeoutMs clears the value of the "timeout_ms" field.
func (u *CoreGatewayHttpRouteUpsertBulk) ClearTimeoutMs() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearTimeoutMs()
	})
}

// SetEnablePathRewrite sets the "enable_path_rewrite" field.
func (u *CoreGatewayHttpRouteUpsertBulk) SetEnablePathRewrite(v constant.YesOrNo) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetEnablePathRewrite(v)
	})
}

// AddEnablePathRewrite adds v to the "enable_path_rewrite" field.
func (u *CoreGatewayHttpRouteUpsertBulk) AddEnablePathRewrite(v constant.YesOrNo) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.AddEnablePathRewrite(v)
	})
}

// UpdateEnablePathRewrite sets the "enable_path_rewrite" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertBulk) UpdateEnablePathRewrite() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateEnablePathRewrite()
	})
}

// ClearEnablePathRewrite clears the value of the "enable_path_rewrite" field.
func (u *CoreGatewayHttpRouteUpsertBulk) ClearEnablePathRewrite() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearEnablePathRewrite()
	})
}

// SetPathRewrite sets the "path_rewrite" field.
func (u *CoreGatewayHttpRouteUpsertBulk) SetPathRewrite(v string) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetPathRewrite(v)
	})
}

// UpdatePathRewrite sets the "path_rewrite" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertBulk) UpdatePathRewrite() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdatePathRewrite()
	})
}

// ClearPathRewrite clears the value of the "path_rewrite" field.
func (u *CoreGatewayHttpRouteUpsertBulk) ClearPathRewrite() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearPathRewrite()
	})
}

// SetEnableRedirect sets the "enable_redirect" field.
func (u *CoreGatewayHttpRouteUpsertBulk) SetEnableRedirect(v constant.YesOrNo) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetEnableRedirect(v)
	})
}

// AddEnableRedirect adds v to the "enable_redirect" field.
func (u *CoreGatewayHttpRouteUpsertBulk) AddEnableRedirect(v constant.YesOrNo) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.AddEnableRedirect(v)
	})
}

// UpdateEnableRedirect sets the "enable_redirect" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertBulk) UpdateEnableRedirect() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateEnableRedirect()
	})
}

// ClearEnableRedirect clears the value of the "enable_redirect" field.
func (u *CoreGatewayHttpRouteUpsertBulk) ClearEnableRedirect() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearEnableRedirect()
	})
}

// SetRedirectURL sets the "redirect_url" field.
func (u *CoreGatewayHttpRouteUpsertBulk) SetRedirectURL(v string) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetRedirectURL(v)
	})
}

// UpdateRedirectURL sets the "redirect_url" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertBulk) UpdateRedirectURL() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateRedirectURL()
	})
}

// ClearRedirectURL clears the value of the "redirect_url" field.
func (u *CoreGatewayHttpRouteUpsertBulk) ClearRedirectURL() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearRedirectURL()
	})
}

// SetRedirectCode sets the "redirect_code" field.
func (u *CoreGatewayHttpRouteUpsertBulk) SetRedirectCode(v int) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetRedirectCode(v)
	})
}

// AddRedirectCode adds v to the "redirect_code" field.
func (u *CoreGatewayHttpRouteUpsertBulk) AddRedirectCode(v int) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.AddRedirectCode(v)
	})
}

// UpdateRedirectCode sets the "redirect_code" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertBulk) UpdateRedirectCode() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateRedirectCode()
	})
}

// ClearRedirectCode clears the value of the "redirect_code" field.
func (u *CoreGatewayHttpRouteUpsertBulk) ClearRedirectCode() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearRedirectCode()
	})
}

// SetStatus sets the "status" field.
func (u *CoreGatewayHttpRouteUpsertBulk) SetStatus(v constant.YesOrNo) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *CoreGatewayHttpRouteUpsertBulk) AddStatus(v constant.YesOrNo) *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CoreGatewayHttpRouteUpsertBulk) UpdateStatus() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *CoreGatewayHttpRouteUpsertBulk) ClearStatus() *CoreGatewayHttpRouteUpsertBulk {
	return u.Update(func(s *CoreGatewayHttpRouteUpsert) {
		s.ClearStatus()
	})
}

// Exec executes the query.
func (u *CoreGatewayHttpRouteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CoreGatewayHttpRouteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoreGatewayHttpRouteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoreGatewayHttpRouteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
