// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coreupstreamhost"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/predicate"
)

// CoreUpstreamHostDelete is the builder for deleting a CoreUpstreamHost entity.
type CoreUpstreamHostDelete struct {
	config
	hooks    []Hook
	mutation *CoreUpstreamHostMutation
}

// Where appends a list predicates to the CoreUpstreamHostDelete builder.
func (_d *CoreUpstreamHostDelete) Where(ps ...predicate.CoreUpstreamHost) *CoreUpstreamHostDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CoreUpstreamHostDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CoreUpstreamHostDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CoreUpstreamHostDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(coreupstreamhost.Table, sqlgraph.NewFieldSpec(coreupstreamhost.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CoreUpstreamHostDeleteOne is the builder for deleting a single CoreUpstreamHost entity.
type CoreUpstreamHostDeleteOne struct {
	_d *CoreUpstreamHostDelete
}

// Where appends a list predicates to the CoreUpstreamHostDelete builder.
func (_d *CoreUpstreamHostDeleteOne) Where(ps ...predicate.CoreUpstreamHost) *CoreUpstreamHostDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CoreUpstreamHostDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{coreupstreamhost.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CoreUpstreamHostDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
