// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/corerole"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coreuser"
	"github.com/lyonmu/quebec/pkg/constant"
)

// 用户信息表
type CoreUser struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID string `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 用户名
	Username string `json:"username,omitempty"`
	// 密码
	Password string `json:"password,omitempty"`
	// 邮箱
	Email string `json:"email,omitempty"`
	// 昵称
	Nickname string `json:"nickname,omitempty"`
	// 用户状态 [1: 启用, 2: 禁用]
	Status constant.YesOrNo `json:"status,omitempty"`
	// 角色ID
	RoleID string `json:"role_id,omitempty"`
	// 用户备注
	Remark string `json:"remark,omitempty"`
	// 最后密码修改时间戳
	LastPasswordChange int64 `json:"last_password_change,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CoreUserQuery when eager-loading is set.
	Edges        CoreUserEdges `json:"-" gorm:"-"`
	selectValues sql.SelectValues
}

// CoreUserEdges holds the relations/edges for other nodes in the graph.
type CoreUserEdges struct {
	// 用户所属角色
	UserFromRole *CoreRole `json:"user_from_role,omitempty"`
	// 用户在线信息
	OnLineToUser []*CoreOnLineUser `json:"on_line_to_user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserFromRoleOrErr returns the UserFromRole value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CoreUserEdges) UserFromRoleOrErr() (*CoreRole, error) {
	if e.UserFromRole != nil {
		return e.UserFromRole, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: corerole.Label}
	}
	return nil, &NotLoadedError{edge: "user_from_role"}
}

// OnLineToUserOrErr returns the OnLineToUser value or an error if the edge
// was not loaded in eager-loading.
func (e CoreUserEdges) OnLineToUserOrErr() ([]*CoreOnLineUser, error) {
	if e.loadedTypes[1] {
		return e.OnLineToUser, nil
	}
	return nil, &NotLoadedError{edge: "on_line_to_user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CoreUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case coreuser.FieldStatus, coreuser.FieldLastPasswordChange:
			values[i] = new(sql.NullInt64)
		case coreuser.FieldID, coreuser.FieldUsername, coreuser.FieldPassword, coreuser.FieldEmail, coreuser.FieldNickname, coreuser.FieldRoleID, coreuser.FieldRemark:
			values[i] = new(sql.NullString)
		case coreuser.FieldCreatedAt, coreuser.FieldUpdatedAt, coreuser.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CoreUser fields.
func (_m *CoreUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case coreuser.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case coreuser.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case coreuser.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case coreuser.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case coreuser.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case coreuser.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case coreuser.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case coreuser.FieldNickname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nickname", values[i])
			} else if value.Valid {
				_m.Nickname = value.String
			}
		case coreuser.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = constant.YesOrNo(value.Int64)
			}
		case coreuser.FieldRoleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				_m.RoleID = value.String
			}
		case coreuser.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = value.String
			}
		case coreuser.FieldLastPasswordChange:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_password_change", values[i])
			} else if value.Valid {
				_m.LastPasswordChange = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CoreUser.
// This includes values selected through modifiers, order, etc.
func (_m *CoreUser) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUserFromRole queries the "user_from_role" edge of the CoreUser entity.
func (_m *CoreUser) QueryUserFromRole() *CoreRoleQuery {
	return NewCoreUserClient(_m.config).QueryUserFromRole(_m)
}

// QueryOnLineToUser queries the "on_line_to_user" edge of the CoreUser entity.
func (_m *CoreUser) QueryOnLineToUser() *CoreOnLineUserQuery {
	return NewCoreUserClient(_m.config).QueryOnLineToUser(_m)
}

// Update returns a builder for updating this CoreUser.
// Note that you need to call CoreUser.Unwrap() before calling this method if this CoreUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CoreUser) Update() *CoreUserUpdateOne {
	return NewCoreUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CoreUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CoreUser) Unwrap() *CoreUser {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CoreUser is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CoreUser) String() string {
	var builder strings.Builder
	builder.WriteString("CoreUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("password=")
	builder.WriteString(_m.Password)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("nickname=")
	builder.WriteString(_m.Nickname)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(_m.RoleID)
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(_m.Remark)
	builder.WriteString(", ")
	builder.WriteString("last_password_change=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastPasswordChange))
	builder.WriteByte(')')
	return builder.String()
}

// CoreUsers is a parsable slice of CoreUser.
type CoreUsers []*CoreUser
