// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coregatewayl4listener"
	"github.com/lyonmu/quebec/pkg/constant"
)

// L4 TCP/UDP监听器表
type CoreGatewayL4Listener struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID string `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 监听器名称
	Name string `json:"name,omitempty"`
	// 监听器描述
	Description string `json:"description,omitempty"`
	// 监听端口
	Port uint16 `json:"port,omitempty"`
	// 监听地址
	Host string `json:"host,omitempty"`
	// 协议类型: 1-TCP 2-UDP
	Protocol constant.ProxyProtocolType `json:"protocol,omitempty"`
	// 是否可用 [1: 启用, 2: 禁用]
	Status       constant.YesOrNo `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CoreGatewayL4Listener) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case coregatewayl4listener.FieldPort, coregatewayl4listener.FieldProtocol, coregatewayl4listener.FieldStatus:
			values[i] = new(sql.NullInt64)
		case coregatewayl4listener.FieldID, coregatewayl4listener.FieldName, coregatewayl4listener.FieldDescription, coregatewayl4listener.FieldHost:
			values[i] = new(sql.NullString)
		case coregatewayl4listener.FieldCreatedAt, coregatewayl4listener.FieldUpdatedAt, coregatewayl4listener.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CoreGatewayL4Listener fields.
func (_m *CoreGatewayL4Listener) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case coregatewayl4listener.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case coregatewayl4listener.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case coregatewayl4listener.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case coregatewayl4listener.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case coregatewayl4listener.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case coregatewayl4listener.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case coregatewayl4listener.FieldPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port", values[i])
			} else if value.Valid {
				_m.Port = uint16(value.Int64)
			}
		case coregatewayl4listener.FieldHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host", values[i])
			} else if value.Valid {
				_m.Host = value.String
			}
		case coregatewayl4listener.FieldProtocol:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = constant.ProxyProtocolType(value.Int64)
			}
		case coregatewayl4listener.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = constant.YesOrNo(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CoreGatewayL4Listener.
// This includes values selected through modifiers, order, etc.
func (_m *CoreGatewayL4Listener) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CoreGatewayL4Listener.
// Note that you need to call CoreGatewayL4Listener.Unwrap() before calling this method if this CoreGatewayL4Listener
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CoreGatewayL4Listener) Update() *CoreGatewayL4ListenerUpdateOne {
	return NewCoreGatewayL4ListenerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CoreGatewayL4Listener entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CoreGatewayL4Listener) Unwrap() *CoreGatewayL4Listener {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CoreGatewayL4Listener is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CoreGatewayL4Listener) String() string {
	var builder strings.Builder
	builder.WriteString("CoreGatewayL4Listener(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("port=")
	builder.WriteString(fmt.Sprintf("%v", _m.Port))
	builder.WriteString(", ")
	builder.WriteString("host=")
	builder.WriteString(_m.Host)
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(fmt.Sprintf("%v", _m.Protocol))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// CoreGatewayL4Listeners is a parsable slice of CoreGatewayL4Listener.
type CoreGatewayL4Listeners []*CoreGatewayL4Listener
