// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coregatewaycluster"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coregatewaynode"
)

// 网关节点信息表
type CoreGatewayNode struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID string `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 节点ID
	NodeID string `json:"node_id,omitempty"`
	// 集群ID
	ClusterID string `json:"cluster_id,omitempty"`
	// 注册时间
	NodeRegisterTime int64 `json:"node_register_time,omitempty"`
	// 最新请求时间
	NodeLastRequestTime int64 `json:"node_last_request_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CoreGatewayNodeQuery when eager-loading is set.
	Edges        CoreGatewayNodeEdges `json:"-" gorm:"-"`
	selectValues sql.SelectValues
}

// CoreGatewayNodeEdges holds the relations/edges for other nodes in the graph.
type CoreGatewayNodeEdges struct {
	// NodeFromCluster holds the value of the node_from_cluster edge.
	NodeFromCluster *CoreGatewayCluster `json:"node_from_cluster,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NodeFromClusterOrErr returns the NodeFromCluster value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CoreGatewayNodeEdges) NodeFromClusterOrErr() (*CoreGatewayCluster, error) {
	if e.NodeFromCluster != nil {
		return e.NodeFromCluster, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: coregatewaycluster.Label}
	}
	return nil, &NotLoadedError{edge: "node_from_cluster"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CoreGatewayNode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case coregatewaynode.FieldNodeRegisterTime, coregatewaynode.FieldNodeLastRequestTime:
			values[i] = new(sql.NullInt64)
		case coregatewaynode.FieldID, coregatewaynode.FieldNodeID, coregatewaynode.FieldClusterID:
			values[i] = new(sql.NullString)
		case coregatewaynode.FieldCreatedAt, coregatewaynode.FieldUpdatedAt, coregatewaynode.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CoreGatewayNode fields.
func (_m *CoreGatewayNode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case coregatewaynode.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case coregatewaynode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case coregatewaynode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case coregatewaynode.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case coregatewaynode.FieldNodeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_id", values[i])
			} else if value.Valid {
				_m.NodeID = value.String
			}
		case coregatewaynode.FieldClusterID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cluster_id", values[i])
			} else if value.Valid {
				_m.ClusterID = value.String
			}
		case coregatewaynode.FieldNodeRegisterTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field node_register_time", values[i])
			} else if value.Valid {
				_m.NodeRegisterTime = value.Int64
			}
		case coregatewaynode.FieldNodeLastRequestTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field node_last_request_time", values[i])
			} else if value.Valid {
				_m.NodeLastRequestTime = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CoreGatewayNode.
// This includes values selected through modifiers, order, etc.
func (_m *CoreGatewayNode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryNodeFromCluster queries the "node_from_cluster" edge of the CoreGatewayNode entity.
func (_m *CoreGatewayNode) QueryNodeFromCluster() *CoreGatewayClusterQuery {
	return NewCoreGatewayNodeClient(_m.config).QueryNodeFromCluster(_m)
}

// Update returns a builder for updating this CoreGatewayNode.
// Note that you need to call CoreGatewayNode.Unwrap() before calling this method if this CoreGatewayNode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CoreGatewayNode) Update() *CoreGatewayNodeUpdateOne {
	return NewCoreGatewayNodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CoreGatewayNode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CoreGatewayNode) Unwrap() *CoreGatewayNode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CoreGatewayNode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CoreGatewayNode) String() string {
	var builder strings.Builder
	builder.WriteString("CoreGatewayNode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("node_id=")
	builder.WriteString(_m.NodeID)
	builder.WriteString(", ")
	builder.WriteString("cluster_id=")
	builder.WriteString(_m.ClusterID)
	builder.WriteString(", ")
	builder.WriteString("node_register_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.NodeRegisterTime))
	builder.WriteString(", ")
	builder.WriteString("node_last_request_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.NodeLastRequestTime))
	builder.WriteByte(')')
	return builder.String()
}

// CoreGatewayNodes is a parsable slice of CoreGatewayNode.
type CoreGatewayNodes []*CoreGatewayNode
