// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coregatewaycluster"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coregatewaynode"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/predicate"
)

// CoreGatewayNodeQuery is the builder for querying CoreGatewayNode entities.
type CoreGatewayNodeQuery struct {
	config
	ctx                 *QueryContext
	order               []coregatewaynode.OrderOption
	inters              []Interceptor
	predicates          []predicate.CoreGatewayNode
	withNodeFromCluster *CoreGatewayClusterQuery
	modifiers           []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CoreGatewayNodeQuery builder.
func (_q *CoreGatewayNodeQuery) Where(ps ...predicate.CoreGatewayNode) *CoreGatewayNodeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CoreGatewayNodeQuery) Limit(limit int) *CoreGatewayNodeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CoreGatewayNodeQuery) Offset(offset int) *CoreGatewayNodeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CoreGatewayNodeQuery) Unique(unique bool) *CoreGatewayNodeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CoreGatewayNodeQuery) Order(o ...coregatewaynode.OrderOption) *CoreGatewayNodeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryNodeFromCluster chains the current query on the "node_from_cluster" edge.
func (_q *CoreGatewayNodeQuery) QueryNodeFromCluster() *CoreGatewayClusterQuery {
	query := (&CoreGatewayClusterClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(coregatewaynode.Table, coregatewaynode.FieldID, selector),
			sqlgraph.To(coregatewaycluster.Table, coregatewaycluster.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, coregatewaynode.NodeFromClusterTable, coregatewaynode.NodeFromClusterColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CoreGatewayNode entity from the query.
// Returns a *NotFoundError when no CoreGatewayNode was found.
func (_q *CoreGatewayNodeQuery) First(ctx context.Context) (*CoreGatewayNode, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{coregatewaynode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CoreGatewayNodeQuery) FirstX(ctx context.Context) *CoreGatewayNode {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CoreGatewayNode ID from the query.
// Returns a *NotFoundError when no CoreGatewayNode ID was found.
func (_q *CoreGatewayNodeQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{coregatewaynode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CoreGatewayNodeQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CoreGatewayNode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CoreGatewayNode entity is found.
// Returns a *NotFoundError when no CoreGatewayNode entities are found.
func (_q *CoreGatewayNodeQuery) Only(ctx context.Context) (*CoreGatewayNode, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{coregatewaynode.Label}
	default:
		return nil, &NotSingularError{coregatewaynode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CoreGatewayNodeQuery) OnlyX(ctx context.Context) *CoreGatewayNode {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CoreGatewayNode ID in the query.
// Returns a *NotSingularError when more than one CoreGatewayNode ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CoreGatewayNodeQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{coregatewaynode.Label}
	default:
		err = &NotSingularError{coregatewaynode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CoreGatewayNodeQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CoreGatewayNodes.
func (_q *CoreGatewayNodeQuery) All(ctx context.Context) ([]*CoreGatewayNode, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CoreGatewayNode, *CoreGatewayNodeQuery]()
	return withInterceptors[[]*CoreGatewayNode](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CoreGatewayNodeQuery) AllX(ctx context.Context) []*CoreGatewayNode {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CoreGatewayNode IDs.
func (_q *CoreGatewayNodeQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(coregatewaynode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CoreGatewayNodeQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CoreGatewayNodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CoreGatewayNodeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CoreGatewayNodeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CoreGatewayNodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CoreGatewayNodeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CoreGatewayNodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CoreGatewayNodeQuery) Clone() *CoreGatewayNodeQuery {
	if _q == nil {
		return nil
	}
	return &CoreGatewayNodeQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]coregatewaynode.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.CoreGatewayNode{}, _q.predicates...),
		withNodeFromCluster: _q.withNodeFromCluster.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithNodeFromCluster tells the query-builder to eager-load the nodes that are connected to
// the "node_from_cluster" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CoreGatewayNodeQuery) WithNodeFromCluster(opts ...func(*CoreGatewayClusterQuery)) *CoreGatewayNodeQuery {
	query := (&CoreGatewayClusterClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNodeFromCluster = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CoreGatewayNode.Query().
//		GroupBy(coregatewaynode.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CoreGatewayNodeQuery) GroupBy(field string, fields ...string) *CoreGatewayNodeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CoreGatewayNodeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = coregatewaynode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.CoreGatewayNode.Query().
//		Select(coregatewaynode.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *CoreGatewayNodeQuery) Select(fields ...string) *CoreGatewayNodeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CoreGatewayNodeSelect{CoreGatewayNodeQuery: _q}
	sbuild.label = coregatewaynode.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CoreGatewayNodeSelect configured with the given aggregations.
func (_q *CoreGatewayNodeQuery) Aggregate(fns ...AggregateFunc) *CoreGatewayNodeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CoreGatewayNodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !coregatewaynode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CoreGatewayNodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CoreGatewayNode, error) {
	var (
		nodes       = []*CoreGatewayNode{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withNodeFromCluster != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CoreGatewayNode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CoreGatewayNode{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withNodeFromCluster; query != nil {
		if err := _q.loadNodeFromCluster(ctx, query, nodes, nil,
			func(n *CoreGatewayNode, e *CoreGatewayCluster) { n.Edges.NodeFromCluster = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CoreGatewayNodeQuery) loadNodeFromCluster(ctx context.Context, query *CoreGatewayClusterQuery, nodes []*CoreGatewayNode, init func(*CoreGatewayNode), assign func(*CoreGatewayNode, *CoreGatewayCluster)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*CoreGatewayNode)
	for i := range nodes {
		fk := nodes[i].ClusterID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(coregatewaycluster.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "cluster_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *CoreGatewayNodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CoreGatewayNodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(coregatewaynode.Table, coregatewaynode.Columns, sqlgraph.NewFieldSpec(coregatewaynode.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coregatewaynode.FieldID)
		for i := range fields {
			if fields[i] != coregatewaynode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withNodeFromCluster != nil {
			_spec.Node.AddColumnOnce(coregatewaynode.FieldClusterID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CoreGatewayNodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(coregatewaynode.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = coregatewaynode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *CoreGatewayNodeQuery) Modify(modifiers ...func(s *sql.Selector)) *CoreGatewayNodeSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// CoreGatewayNodeGroupBy is the group-by builder for CoreGatewayNode entities.
type CoreGatewayNodeGroupBy struct {
	selector
	build *CoreGatewayNodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CoreGatewayNodeGroupBy) Aggregate(fns ...AggregateFunc) *CoreGatewayNodeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CoreGatewayNodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CoreGatewayNodeQuery, *CoreGatewayNodeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CoreGatewayNodeGroupBy) sqlScan(ctx context.Context, root *CoreGatewayNodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CoreGatewayNodeSelect is the builder for selecting fields of CoreGatewayNode entities.
type CoreGatewayNodeSelect struct {
	*CoreGatewayNodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CoreGatewayNodeSelect) Aggregate(fns ...AggregateFunc) *CoreGatewayNodeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CoreGatewayNodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CoreGatewayNodeQuery, *CoreGatewayNodeSelect](ctx, _s.CoreGatewayNodeQuery, _s, _s.inters, v)
}

func (_s *CoreGatewayNodeSelect) sqlScan(ctx context.Context, root *CoreGatewayNodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *CoreGatewayNodeSelect) Modify(modifiers ...func(s *sql.Selector)) *CoreGatewayNodeSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
