// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lyonmu/quebec/cmd/core/internal/common"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coreoperationlog"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coreuser"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/predicate"
)

// CoreOperationLogUpdate is the builder for updating CoreOperationLog entities.
type CoreOperationLogUpdate struct {
	config
	hooks     []Hook
	mutation  *CoreOperationLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CoreOperationLogUpdate builder.
func (_u *CoreOperationLogUpdate) Where(ps ...predicate.CoreOperationLog) *CoreOperationLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CoreOperationLogUpdate) SetUpdatedAt(v time.Time) *CoreOperationLogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CoreOperationLogUpdate) SetDeletedAt(v time.Time) *CoreOperationLogUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CoreOperationLogUpdate) SetNillableDeletedAt(v *time.Time) *CoreOperationLogUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CoreOperationLogUpdate) ClearDeletedAt() *CoreOperationLogUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CoreOperationLogUpdate) SetUserID(v string) *CoreOperationLogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CoreOperationLogUpdate) SetNillableUserID(v *string) *CoreOperationLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *CoreOperationLogUpdate) ClearUserID() *CoreOperationLogUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetAccessIP sets the "access_ip" field.
func (_u *CoreOperationLogUpdate) SetAccessIP(v string) *CoreOperationLogUpdate {
	_u.mutation.SetAccessIP(v)
	return _u
}

// SetNillableAccessIP sets the "access_ip" field if the given value is not nil.
func (_u *CoreOperationLogUpdate) SetNillableAccessIP(v *string) *CoreOperationLogUpdate {
	if v != nil {
		_u.SetAccessIP(*v)
	}
	return _u
}

// ClearAccessIP clears the value of the "access_ip" field.
func (_u *CoreOperationLogUpdate) ClearAccessIP() *CoreOperationLogUpdate {
	_u.mutation.ClearAccessIP()
	return _u
}

// SetOperationTime sets the "operation_time" field.
func (_u *CoreOperationLogUpdate) SetOperationTime(v int64) *CoreOperationLogUpdate {
	_u.mutation.ResetOperationTime()
	_u.mutation.SetOperationTime(v)
	return _u
}

// SetNillableOperationTime sets the "operation_time" field if the given value is not nil.
func (_u *CoreOperationLogUpdate) SetNillableOperationTime(v *int64) *CoreOperationLogUpdate {
	if v != nil {
		_u.SetOperationTime(*v)
	}
	return _u
}

// AddOperationTime adds value to the "operation_time" field.
func (_u *CoreOperationLogUpdate) AddOperationTime(v int64) *CoreOperationLogUpdate {
	_u.mutation.AddOperationTime(v)
	return _u
}

// ClearOperationTime clears the value of the "operation_time" field.
func (_u *CoreOperationLogUpdate) ClearOperationTime() *CoreOperationLogUpdate {
	_u.mutation.ClearOperationTime()
	return _u
}

// SetOperationType sets the "operation_type" field.
func (_u *CoreOperationLogUpdate) SetOperationType(v common.OperationType) *CoreOperationLogUpdate {
	_u.mutation.ResetOperationType()
	_u.mutation.SetOperationType(v)
	return _u
}

// SetNillableOperationType sets the "operation_type" field if the given value is not nil.
func (_u *CoreOperationLogUpdate) SetNillableOperationType(v *common.OperationType) *CoreOperationLogUpdate {
	if v != nil {
		_u.SetOperationType(*v)
	}
	return _u
}

// AddOperationType adds value to the "operation_type" field.
func (_u *CoreOperationLogUpdate) AddOperationType(v common.OperationType) *CoreOperationLogUpdate {
	_u.mutation.AddOperationType(v)
	return _u
}

// ClearOperationType clears the value of the "operation_type" field.
func (_u *CoreOperationLogUpdate) ClearOperationType() *CoreOperationLogUpdate {
	_u.mutation.ClearOperationType()
	return _u
}

// SetOs sets the "os" field.
func (_u *CoreOperationLogUpdate) SetOs(v string) *CoreOperationLogUpdate {
	_u.mutation.SetOs(v)
	return _u
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (_u *CoreOperationLogUpdate) SetNillableOs(v *string) *CoreOperationLogUpdate {
	if v != nil {
		_u.SetOs(*v)
	}
	return _u
}

// ClearOs clears the value of the "os" field.
func (_u *CoreOperationLogUpdate) ClearOs() *CoreOperationLogUpdate {
	_u.mutation.ClearOs()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *CoreOperationLogUpdate) SetPlatform(v string) *CoreOperationLogUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *CoreOperationLogUpdate) SetNillablePlatform(v *string) *CoreOperationLogUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// ClearPlatform clears the value of the "platform" field.
func (_u *CoreOperationLogUpdate) ClearPlatform() *CoreOperationLogUpdate {
	_u.mutation.ClearPlatform()
	return _u
}

// SetBrowserName sets the "browser_name" field.
func (_u *CoreOperationLogUpdate) SetBrowserName(v string) *CoreOperationLogUpdate {
	_u.mutation.SetBrowserName(v)
	return _u
}

// SetNillableBrowserName sets the "browser_name" field if the given value is not nil.
func (_u *CoreOperationLogUpdate) SetNillableBrowserName(v *string) *CoreOperationLogUpdate {
	if v != nil {
		_u.SetBrowserName(*v)
	}
	return _u
}

// ClearBrowserName clears the value of the "browser_name" field.
func (_u *CoreOperationLogUpdate) ClearBrowserName() *CoreOperationLogUpdate {
	_u.mutation.ClearBrowserName()
	return _u
}

// SetBrowserVersion sets the "browser_version" field.
func (_u *CoreOperationLogUpdate) SetBrowserVersion(v string) *CoreOperationLogUpdate {
	_u.mutation.SetBrowserVersion(v)
	return _u
}

// SetNillableBrowserVersion sets the "browser_version" field if the given value is not nil.
func (_u *CoreOperationLogUpdate) SetNillableBrowserVersion(v *string) *CoreOperationLogUpdate {
	if v != nil {
		_u.SetBrowserVersion(*v)
	}
	return _u
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (_u *CoreOperationLogUpdate) ClearBrowserVersion() *CoreOperationLogUpdate {
	_u.mutation.ClearBrowserVersion()
	return _u
}

// SetBrowserEngineName sets the "browser_engine_name" field.
func (_u *CoreOperationLogUpdate) SetBrowserEngineName(v string) *CoreOperationLogUpdate {
	_u.mutation.SetBrowserEngineName(v)
	return _u
}

// SetNillableBrowserEngineName sets the "browser_engine_name" field if the given value is not nil.
func (_u *CoreOperationLogUpdate) SetNillableBrowserEngineName(v *string) *CoreOperationLogUpdate {
	if v != nil {
		_u.SetBrowserEngineName(*v)
	}
	return _u
}

// ClearBrowserEngineName clears the value of the "browser_engine_name" field.
func (_u *CoreOperationLogUpdate) ClearBrowserEngineName() *CoreOperationLogUpdate {
	_u.mutation.ClearBrowserEngineName()
	return _u
}

// SetBrowserEngineVersion sets the "browser_engine_version" field.
func (_u *CoreOperationLogUpdate) SetBrowserEngineVersion(v string) *CoreOperationLogUpdate {
	_u.mutation.SetBrowserEngineVersion(v)
	return _u
}

// SetNillableBrowserEngineVersion sets the "browser_engine_version" field if the given value is not nil.
func (_u *CoreOperationLogUpdate) SetNillableBrowserEngineVersion(v *string) *CoreOperationLogUpdate {
	if v != nil {
		_u.SetBrowserEngineVersion(*v)
	}
	return _u
}

// ClearBrowserEngineVersion clears the value of the "browser_engine_version" field.
func (_u *CoreOperationLogUpdate) ClearBrowserEngineVersion() *CoreOperationLogUpdate {
	_u.mutation.ClearBrowserEngineVersion()
	return _u
}

// SetOperationLogFromUserID sets the "operation_log_from_user" edge to the CoreUser entity by ID.
func (_u *CoreOperationLogUpdate) SetOperationLogFromUserID(id string) *CoreOperationLogUpdate {
	_u.mutation.SetOperationLogFromUserID(id)
	return _u
}

// SetNillableOperationLogFromUserID sets the "operation_log_from_user" edge to the CoreUser entity by ID if the given value is not nil.
func (_u *CoreOperationLogUpdate) SetNillableOperationLogFromUserID(id *string) *CoreOperationLogUpdate {
	if id != nil {
		_u = _u.SetOperationLogFromUserID(*id)
	}
	return _u
}

// SetOperationLogFromUser sets the "operation_log_from_user" edge to the CoreUser entity.
func (_u *CoreOperationLogUpdate) SetOperationLogFromUser(v *CoreUser) *CoreOperationLogUpdate {
	return _u.SetOperationLogFromUserID(v.ID)
}

// Mutation returns the CoreOperationLogMutation object of the builder.
func (_u *CoreOperationLogUpdate) Mutation() *CoreOperationLogMutation {
	return _u.mutation
}

// ClearOperationLogFromUser clears the "operation_log_from_user" edge to the CoreUser entity.
func (_u *CoreOperationLogUpdate) ClearOperationLogFromUser() *CoreOperationLogUpdate {
	_u.mutation.ClearOperationLogFromUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CoreOperationLogUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoreOperationLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CoreOperationLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoreOperationLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CoreOperationLogUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if coreoperationlog.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized coreoperationlog.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := coreoperationlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CoreOperationLogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CoreOperationLogUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CoreOperationLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(coreoperationlog.Table, coreoperationlog.Columns, sqlgraph.NewFieldSpec(coreoperationlog.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(coreoperationlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(coreoperationlog.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(coreoperationlog.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AccessIP(); ok {
		_spec.SetField(coreoperationlog.FieldAccessIP, field.TypeString, value)
	}
	if _u.mutation.AccessIPCleared() {
		_spec.ClearField(coreoperationlog.FieldAccessIP, field.TypeString)
	}
	if value, ok := _u.mutation.OperationTime(); ok {
		_spec.SetField(coreoperationlog.FieldOperationTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperationTime(); ok {
		_spec.AddField(coreoperationlog.FieldOperationTime, field.TypeInt64, value)
	}
	if _u.mutation.OperationTimeCleared() {
		_spec.ClearField(coreoperationlog.FieldOperationTime, field.TypeInt64)
	}
	if value, ok := _u.mutation.OperationType(); ok {
		_spec.SetField(coreoperationlog.FieldOperationType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOperationType(); ok {
		_spec.AddField(coreoperationlog.FieldOperationType, field.TypeInt, value)
	}
	if _u.mutation.OperationTypeCleared() {
		_spec.ClearField(coreoperationlog.FieldOperationType, field.TypeInt)
	}
	if value, ok := _u.mutation.Os(); ok {
		_spec.SetField(coreoperationlog.FieldOs, field.TypeString, value)
	}
	if _u.mutation.OsCleared() {
		_spec.ClearField(coreoperationlog.FieldOs, field.TypeString)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(coreoperationlog.FieldPlatform, field.TypeString, value)
	}
	if _u.mutation.PlatformCleared() {
		_spec.ClearField(coreoperationlog.FieldPlatform, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserName(); ok {
		_spec.SetField(coreoperationlog.FieldBrowserName, field.TypeString, value)
	}
	if _u.mutation.BrowserNameCleared() {
		_spec.ClearField(coreoperationlog.FieldBrowserName, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserVersion(); ok {
		_spec.SetField(coreoperationlog.FieldBrowserVersion, field.TypeString, value)
	}
	if _u.mutation.BrowserVersionCleared() {
		_spec.ClearField(coreoperationlog.FieldBrowserVersion, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserEngineName(); ok {
		_spec.SetField(coreoperationlog.FieldBrowserEngineName, field.TypeString, value)
	}
	if _u.mutation.BrowserEngineNameCleared() {
		_spec.ClearField(coreoperationlog.FieldBrowserEngineName, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserEngineVersion(); ok {
		_spec.SetField(coreoperationlog.FieldBrowserEngineVersion, field.TypeString, value)
	}
	if _u.mutation.BrowserEngineVersionCleared() {
		_spec.ClearField(coreoperationlog.FieldBrowserEngineVersion, field.TypeString)
	}
	if _u.mutation.OperationLogFromUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coreoperationlog.OperationLogFromUserTable,
			Columns: []string{coreoperationlog.OperationLogFromUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coreuser.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OperationLogFromUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coreoperationlog.OperationLogFromUserTable,
			Columns: []string{coreoperationlog.OperationLogFromUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coreuser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coreoperationlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CoreOperationLogUpdateOne is the builder for updating a single CoreOperationLog entity.
type CoreOperationLogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CoreOperationLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CoreOperationLogUpdateOne) SetUpdatedAt(v time.Time) *CoreOperationLogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CoreOperationLogUpdateOne) SetDeletedAt(v time.Time) *CoreOperationLogUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CoreOperationLogUpdateOne) SetNillableDeletedAt(v *time.Time) *CoreOperationLogUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CoreOperationLogUpdateOne) ClearDeletedAt() *CoreOperationLogUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CoreOperationLogUpdateOne) SetUserID(v string) *CoreOperationLogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CoreOperationLogUpdateOne) SetNillableUserID(v *string) *CoreOperationLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *CoreOperationLogUpdateOne) ClearUserID() *CoreOperationLogUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetAccessIP sets the "access_ip" field.
func (_u *CoreOperationLogUpdateOne) SetAccessIP(v string) *CoreOperationLogUpdateOne {
	_u.mutation.SetAccessIP(v)
	return _u
}

// SetNillableAccessIP sets the "access_ip" field if the given value is not nil.
func (_u *CoreOperationLogUpdateOne) SetNillableAccessIP(v *string) *CoreOperationLogUpdateOne {
	if v != nil {
		_u.SetAccessIP(*v)
	}
	return _u
}

// ClearAccessIP clears the value of the "access_ip" field.
func (_u *CoreOperationLogUpdateOne) ClearAccessIP() *CoreOperationLogUpdateOne {
	_u.mutation.ClearAccessIP()
	return _u
}

// SetOperationTime sets the "operation_time" field.
func (_u *CoreOperationLogUpdateOne) SetOperationTime(v int64) *CoreOperationLogUpdateOne {
	_u.mutation.ResetOperationTime()
	_u.mutation.SetOperationTime(v)
	return _u
}

// SetNillableOperationTime sets the "operation_time" field if the given value is not nil.
func (_u *CoreOperationLogUpdateOne) SetNillableOperationTime(v *int64) *CoreOperationLogUpdateOne {
	if v != nil {
		_u.SetOperationTime(*v)
	}
	return _u
}

// AddOperationTime adds value to the "operation_time" field.
func (_u *CoreOperationLogUpdateOne) AddOperationTime(v int64) *CoreOperationLogUpdateOne {
	_u.mutation.AddOperationTime(v)
	return _u
}

// ClearOperationTime clears the value of the "operation_time" field.
func (_u *CoreOperationLogUpdateOne) ClearOperationTime() *CoreOperationLogUpdateOne {
	_u.mutation.ClearOperationTime()
	return _u
}

// SetOperationType sets the "operation_type" field.
func (_u *CoreOperationLogUpdateOne) SetOperationType(v common.OperationType) *CoreOperationLogUpdateOne {
	_u.mutation.ResetOperationType()
	_u.mutation.SetOperationType(v)
	return _u
}

// SetNillableOperationType sets the "operation_type" field if the given value is not nil.
func (_u *CoreOperationLogUpdateOne) SetNillableOperationType(v *common.OperationType) *CoreOperationLogUpdateOne {
	if v != nil {
		_u.SetOperationType(*v)
	}
	return _u
}

// AddOperationType adds value to the "operation_type" field.
func (_u *CoreOperationLogUpdateOne) AddOperationType(v common.OperationType) *CoreOperationLogUpdateOne {
	_u.mutation.AddOperationType(v)
	return _u
}

// ClearOperationType clears the value of the "operation_type" field.
func (_u *CoreOperationLogUpdateOne) ClearOperationType() *CoreOperationLogUpdateOne {
	_u.mutation.ClearOperationType()
	return _u
}

// SetOs sets the "os" field.
func (_u *CoreOperationLogUpdateOne) SetOs(v string) *CoreOperationLogUpdateOne {
	_u.mutation.SetOs(v)
	return _u
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (_u *CoreOperationLogUpdateOne) SetNillableOs(v *string) *CoreOperationLogUpdateOne {
	if v != nil {
		_u.SetOs(*v)
	}
	return _u
}

// ClearOs clears the value of the "os" field.
func (_u *CoreOperationLogUpdateOne) ClearOs() *CoreOperationLogUpdateOne {
	_u.mutation.ClearOs()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *CoreOperationLogUpdateOne) SetPlatform(v string) *CoreOperationLogUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *CoreOperationLogUpdateOne) SetNillablePlatform(v *string) *CoreOperationLogUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// ClearPlatform clears the value of the "platform" field.
func (_u *CoreOperationLogUpdateOne) ClearPlatform() *CoreOperationLogUpdateOne {
	_u.mutation.ClearPlatform()
	return _u
}

// SetBrowserName sets the "browser_name" field.
func (_u *CoreOperationLogUpdateOne) SetBrowserName(v string) *CoreOperationLogUpdateOne {
	_u.mutation.SetBrowserName(v)
	return _u
}

// SetNillableBrowserName sets the "browser_name" field if the given value is not nil.
func (_u *CoreOperationLogUpdateOne) SetNillableBrowserName(v *string) *CoreOperationLogUpdateOne {
	if v != nil {
		_u.SetBrowserName(*v)
	}
	return _u
}

// ClearBrowserName clears the value of the "browser_name" field.
func (_u *CoreOperationLogUpdateOne) ClearBrowserName() *CoreOperationLogUpdateOne {
	_u.mutation.ClearBrowserName()
	return _u
}

// SetBrowserVersion sets the "browser_version" field.
func (_u *CoreOperationLogUpdateOne) SetBrowserVersion(v string) *CoreOperationLogUpdateOne {
	_u.mutation.SetBrowserVersion(v)
	return _u
}

// SetNillableBrowserVersion sets the "browser_version" field if the given value is not nil.
func (_u *CoreOperationLogUpdateOne) SetNillableBrowserVersion(v *string) *CoreOperationLogUpdateOne {
	if v != nil {
		_u.SetBrowserVersion(*v)
	}
	return _u
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (_u *CoreOperationLogUpdateOne) ClearBrowserVersion() *CoreOperationLogUpdateOne {
	_u.mutation.ClearBrowserVersion()
	return _u
}

// SetBrowserEngineName sets the "browser_engine_name" field.
func (_u *CoreOperationLogUpdateOne) SetBrowserEngineName(v string) *CoreOperationLogUpdateOne {
	_u.mutation.SetBrowserEngineName(v)
	return _u
}

// SetNillableBrowserEngineName sets the "browser_engine_name" field if the given value is not nil.
func (_u *CoreOperationLogUpdateOne) SetNillableBrowserEngineName(v *string) *CoreOperationLogUpdateOne {
	if v != nil {
		_u.SetBrowserEngineName(*v)
	}
	return _u
}

// ClearBrowserEngineName clears the value of the "browser_engine_name" field.
func (_u *CoreOperationLogUpdateOne) ClearBrowserEngineName() *CoreOperationLogUpdateOne {
	_u.mutation.ClearBrowserEngineName()
	return _u
}

// SetBrowserEngineVersion sets the "browser_engine_version" field.
func (_u *CoreOperationLogUpdateOne) SetBrowserEngineVersion(v string) *CoreOperationLogUpdateOne {
	_u.mutation.SetBrowserEngineVersion(v)
	return _u
}

// SetNillableBrowserEngineVersion sets the "browser_engine_version" field if the given value is not nil.
func (_u *CoreOperationLogUpdateOne) SetNillableBrowserEngineVersion(v *string) *CoreOperationLogUpdateOne {
	if v != nil {
		_u.SetBrowserEngineVersion(*v)
	}
	return _u
}

// ClearBrowserEngineVersion clears the value of the "browser_engine_version" field.
func (_u *CoreOperationLogUpdateOne) ClearBrowserEngineVersion() *CoreOperationLogUpdateOne {
	_u.mutation.ClearBrowserEngineVersion()
	return _u
}

// SetOperationLogFromUserID sets the "operation_log_from_user" edge to the CoreUser entity by ID.
func (_u *CoreOperationLogUpdateOne) SetOperationLogFromUserID(id string) *CoreOperationLogUpdateOne {
	_u.mutation.SetOperationLogFromUserID(id)
	return _u
}

// SetNillableOperationLogFromUserID sets the "operation_log_from_user" edge to the CoreUser entity by ID if the given value is not nil.
func (_u *CoreOperationLogUpdateOne) SetNillableOperationLogFromUserID(id *string) *CoreOperationLogUpdateOne {
	if id != nil {
		_u = _u.SetOperationLogFromUserID(*id)
	}
	return _u
}

// SetOperationLogFromUser sets the "operation_log_from_user" edge to the CoreUser entity.
func (_u *CoreOperationLogUpdateOne) SetOperationLogFromUser(v *CoreUser) *CoreOperationLogUpdateOne {
	return _u.SetOperationLogFromUserID(v.ID)
}

// Mutation returns the CoreOperationLogMutation object of the builder.
func (_u *CoreOperationLogUpdateOne) Mutation() *CoreOperationLogMutation {
	return _u.mutation
}

// ClearOperationLogFromUser clears the "operation_log_from_user" edge to the CoreUser entity.
func (_u *CoreOperationLogUpdateOne) ClearOperationLogFromUser() *CoreOperationLogUpdateOne {
	_u.mutation.ClearOperationLogFromUser()
	return _u
}

// Where appends a list predicates to the CoreOperationLogUpdate builder.
func (_u *CoreOperationLogUpdateOne) Where(ps ...predicate.CoreOperationLog) *CoreOperationLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CoreOperationLogUpdateOne) Select(field string, fields ...string) *CoreOperationLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CoreOperationLog entity.
func (_u *CoreOperationLogUpdateOne) Save(ctx context.Context) (*CoreOperationLog, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoreOperationLogUpdateOne) SaveX(ctx context.Context) *CoreOperationLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CoreOperationLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoreOperationLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CoreOperationLogUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if coreoperationlog.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized coreoperationlog.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := coreoperationlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CoreOperationLogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CoreOperationLogUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CoreOperationLogUpdateOne) sqlSave(ctx context.Context) (_node *CoreOperationLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(coreoperationlog.Table, coreoperationlog.Columns, sqlgraph.NewFieldSpec(coreoperationlog.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CoreOperationLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coreoperationlog.FieldID)
		for _, f := range fields {
			if !coreoperationlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != coreoperationlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(coreoperationlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(coreoperationlog.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(coreoperationlog.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AccessIP(); ok {
		_spec.SetField(coreoperationlog.FieldAccessIP, field.TypeString, value)
	}
	if _u.mutation.AccessIPCleared() {
		_spec.ClearField(coreoperationlog.FieldAccessIP, field.TypeString)
	}
	if value, ok := _u.mutation.OperationTime(); ok {
		_spec.SetField(coreoperationlog.FieldOperationTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperationTime(); ok {
		_spec.AddField(coreoperationlog.FieldOperationTime, field.TypeInt64, value)
	}
	if _u.mutation.OperationTimeCleared() {
		_spec.ClearField(coreoperationlog.FieldOperationTime, field.TypeInt64)
	}
	if value, ok := _u.mutation.OperationType(); ok {
		_spec.SetField(coreoperationlog.FieldOperationType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOperationType(); ok {
		_spec.AddField(coreoperationlog.FieldOperationType, field.TypeInt, value)
	}
	if _u.mutation.OperationTypeCleared() {
		_spec.ClearField(coreoperationlog.FieldOperationType, field.TypeInt)
	}
	if value, ok := _u.mutation.Os(); ok {
		_spec.SetField(coreoperationlog.FieldOs, field.TypeString, value)
	}
	if _u.mutation.OsCleared() {
		_spec.ClearField(coreoperationlog.FieldOs, field.TypeString)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(coreoperationlog.FieldPlatform, field.TypeString, value)
	}
	if _u.mutation.PlatformCleared() {
		_spec.ClearField(coreoperationlog.FieldPlatform, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserName(); ok {
		_spec.SetField(coreoperationlog.FieldBrowserName, field.TypeString, value)
	}
	if _u.mutation.BrowserNameCleared() {
		_spec.ClearField(coreoperationlog.FieldBrowserName, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserVersion(); ok {
		_spec.SetField(coreoperationlog.FieldBrowserVersion, field.TypeString, value)
	}
	if _u.mutation.BrowserVersionCleared() {
		_spec.ClearField(coreoperationlog.FieldBrowserVersion, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserEngineName(); ok {
		_spec.SetField(coreoperationlog.FieldBrowserEngineName, field.TypeString, value)
	}
	if _u.mutation.BrowserEngineNameCleared() {
		_spec.ClearField(coreoperationlog.FieldBrowserEngineName, field.TypeString)
	}
	if value, ok := _u.mutation.BrowserEngineVersion(); ok {
		_spec.SetField(coreoperationlog.FieldBrowserEngineVersion, field.TypeString, value)
	}
	if _u.mutation.BrowserEngineVersionCleared() {
		_spec.ClearField(coreoperationlog.FieldBrowserEngineVersion, field.TypeString)
	}
	if _u.mutation.OperationLogFromUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coreoperationlog.OperationLogFromUserTable,
			Columns: []string{coreoperationlog.OperationLogFromUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coreuser.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OperationLogFromUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coreoperationlog.OperationLogFromUserTable,
			Columns: []string{coreoperationlog.OperationLogFromUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coreuser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &CoreOperationLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coreoperationlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
