// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lyonmu/quebec/cmd/core/internal/common"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coredatarelationship"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coremenu"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/corerole"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/predicate"
)

// CoreDataRelationshipUpdate is the builder for updating CoreDataRelationship entities.
type CoreDataRelationshipUpdate struct {
	config
	hooks     []Hook
	mutation  *CoreDataRelationshipMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CoreDataRelationshipUpdate builder.
func (_u *CoreDataRelationshipUpdate) Where(ps ...predicate.CoreDataRelationship) *CoreDataRelationshipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CoreDataRelationshipUpdate) SetUpdatedAt(v time.Time) *CoreDataRelationshipUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CoreDataRelationshipUpdate) SetDeletedAt(v time.Time) *CoreDataRelationshipUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CoreDataRelationshipUpdate) SetNillableDeletedAt(v *time.Time) *CoreDataRelationshipUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CoreDataRelationshipUpdate) ClearDeletedAt() *CoreDataRelationshipUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDataRelationshipType sets the "data_relationship_type" field.
func (_u *CoreDataRelationshipUpdate) SetDataRelationshipType(v common.DataRelationshipType) *CoreDataRelationshipUpdate {
	_u.mutation.ResetDataRelationshipType()
	_u.mutation.SetDataRelationshipType(v)
	return _u
}

// SetNillableDataRelationshipType sets the "data_relationship_type" field if the given value is not nil.
func (_u *CoreDataRelationshipUpdate) SetNillableDataRelationshipType(v *common.DataRelationshipType) *CoreDataRelationshipUpdate {
	if v != nil {
		_u.SetDataRelationshipType(*v)
	}
	return _u
}

// AddDataRelationshipType adds value to the "data_relationship_type" field.
func (_u *CoreDataRelationshipUpdate) AddDataRelationshipType(v common.DataRelationshipType) *CoreDataRelationshipUpdate {
	_u.mutation.AddDataRelationshipType(v)
	return _u
}

// ClearDataRelationshipType clears the value of the "data_relationship_type" field.
func (_u *CoreDataRelationshipUpdate) ClearDataRelationshipType() *CoreDataRelationshipUpdate {
	_u.mutation.ClearDataRelationshipType()
	return _u
}

// SetMenuID sets the "menu_id" field.
func (_u *CoreDataRelationshipUpdate) SetMenuID(v string) *CoreDataRelationshipUpdate {
	_u.mutation.SetMenuID(v)
	return _u
}

// SetNillableMenuID sets the "menu_id" field if the given value is not nil.
func (_u *CoreDataRelationshipUpdate) SetNillableMenuID(v *string) *CoreDataRelationshipUpdate {
	if v != nil {
		_u.SetMenuID(*v)
	}
	return _u
}

// ClearMenuID clears the value of the "menu_id" field.
func (_u *CoreDataRelationshipUpdate) ClearMenuID() *CoreDataRelationshipUpdate {
	_u.mutation.ClearMenuID()
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *CoreDataRelationshipUpdate) SetRoleID(v string) *CoreDataRelationshipUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *CoreDataRelationshipUpdate) SetNillableRoleID(v *string) *CoreDataRelationshipUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// ClearRoleID clears the value of the "role_id" field.
func (_u *CoreDataRelationshipUpdate) ClearRoleID() *CoreDataRelationshipUpdate {
	_u.mutation.ClearRoleID()
	return _u
}

// AddMenuIDs adds the "menu" edge to the CoreMenu entity by IDs.
func (_u *CoreDataRelationshipUpdate) AddMenuIDs(ids ...string) *CoreDataRelationshipUpdate {
	_u.mutation.AddMenuIDs(ids...)
	return _u
}

// AddMenu adds the "menu" edges to the CoreMenu entity.
func (_u *CoreDataRelationshipUpdate) AddMenu(v ...*CoreMenu) *CoreDataRelationshipUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMenuIDs(ids...)
}

// AddRoleIDs adds the "role" edge to the CoreRole entity by IDs.
func (_u *CoreDataRelationshipUpdate) AddRoleIDs(ids ...string) *CoreDataRelationshipUpdate {
	_u.mutation.AddRoleIDs(ids...)
	return _u
}

// AddRole adds the "role" edges to the CoreRole entity.
func (_u *CoreDataRelationshipUpdate) AddRole(v ...*CoreRole) *CoreDataRelationshipUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleIDs(ids...)
}

// Mutation returns the CoreDataRelationshipMutation object of the builder.
func (_u *CoreDataRelationshipUpdate) Mutation() *CoreDataRelationshipMutation {
	return _u.mutation
}

// ClearMenu clears all "menu" edges to the CoreMenu entity.
func (_u *CoreDataRelationshipUpdate) ClearMenu() *CoreDataRelationshipUpdate {
	_u.mutation.ClearMenu()
	return _u
}

// RemoveMenuIDs removes the "menu" edge to CoreMenu entities by IDs.
func (_u *CoreDataRelationshipUpdate) RemoveMenuIDs(ids ...string) *CoreDataRelationshipUpdate {
	_u.mutation.RemoveMenuIDs(ids...)
	return _u
}

// RemoveMenu removes "menu" edges to CoreMenu entities.
func (_u *CoreDataRelationshipUpdate) RemoveMenu(v ...*CoreMenu) *CoreDataRelationshipUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMenuIDs(ids...)
}

// ClearRole clears all "role" edges to the CoreRole entity.
func (_u *CoreDataRelationshipUpdate) ClearRole() *CoreDataRelationshipUpdate {
	_u.mutation.ClearRole()
	return _u
}

// RemoveRoleIDs removes the "role" edge to CoreRole entities by IDs.
func (_u *CoreDataRelationshipUpdate) RemoveRoleIDs(ids ...string) *CoreDataRelationshipUpdate {
	_u.mutation.RemoveRoleIDs(ids...)
	return _u
}

// RemoveRole removes "role" edges to CoreRole entities.
func (_u *CoreDataRelationshipUpdate) RemoveRole(v ...*CoreRole) *CoreDataRelationshipUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CoreDataRelationshipUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoreDataRelationshipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CoreDataRelationshipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoreDataRelationshipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CoreDataRelationshipUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if coredatarelationship.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized coredatarelationship.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := coredatarelationship.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CoreDataRelationshipUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CoreDataRelationshipUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CoreDataRelationshipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(coredatarelationship.Table, coredatarelationship.Columns, sqlgraph.NewFieldSpec(coredatarelationship.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(coredatarelationship.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(coredatarelationship.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(coredatarelationship.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DataRelationshipType(); ok {
		_spec.SetField(coredatarelationship.FieldDataRelationshipType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedDataRelationshipType(); ok {
		_spec.AddField(coredatarelationship.FieldDataRelationshipType, field.TypeInt8, value)
	}
	if _u.mutation.DataRelationshipTypeCleared() {
		_spec.ClearField(coredatarelationship.FieldDataRelationshipType, field.TypeInt8)
	}
	if value, ok := _u.mutation.MenuID(); ok {
		_spec.SetField(coredatarelationship.FieldMenuID, field.TypeString, value)
	}
	if _u.mutation.MenuIDCleared() {
		_spec.ClearField(coredatarelationship.FieldMenuID, field.TypeString)
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(coredatarelationship.FieldRoleID, field.TypeString, value)
	}
	if _u.mutation.RoleIDCleared() {
		_spec.ClearField(coredatarelationship.FieldRoleID, field.TypeString)
	}
	if _u.mutation.MenuCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   coredatarelationship.MenuTable,
			Columns: coredatarelationship.MenuPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coremenu.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMenuIDs(); len(nodes) > 0 && !_u.mutation.MenuCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   coredatarelationship.MenuTable,
			Columns: coredatarelationship.MenuPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coremenu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   coredatarelationship.MenuTable,
			Columns: coredatarelationship.MenuPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coremenu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   coredatarelationship.RoleTable,
			Columns: coredatarelationship.RolePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(corerole.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoleIDs(); len(nodes) > 0 && !_u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   coredatarelationship.RoleTable,
			Columns: coredatarelationship.RolePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(corerole.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   coredatarelationship.RoleTable,
			Columns: coredatarelationship.RolePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(corerole.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coredatarelationship.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CoreDataRelationshipUpdateOne is the builder for updating a single CoreDataRelationship entity.
type CoreDataRelationshipUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CoreDataRelationshipMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CoreDataRelationshipUpdateOne) SetUpdatedAt(v time.Time) *CoreDataRelationshipUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CoreDataRelationshipUpdateOne) SetDeletedAt(v time.Time) *CoreDataRelationshipUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CoreDataRelationshipUpdateOne) SetNillableDeletedAt(v *time.Time) *CoreDataRelationshipUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CoreDataRelationshipUpdateOne) ClearDeletedAt() *CoreDataRelationshipUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDataRelationshipType sets the "data_relationship_type" field.
func (_u *CoreDataRelationshipUpdateOne) SetDataRelationshipType(v common.DataRelationshipType) *CoreDataRelationshipUpdateOne {
	_u.mutation.ResetDataRelationshipType()
	_u.mutation.SetDataRelationshipType(v)
	return _u
}

// SetNillableDataRelationshipType sets the "data_relationship_type" field if the given value is not nil.
func (_u *CoreDataRelationshipUpdateOne) SetNillableDataRelationshipType(v *common.DataRelationshipType) *CoreDataRelationshipUpdateOne {
	if v != nil {
		_u.SetDataRelationshipType(*v)
	}
	return _u
}

// AddDataRelationshipType adds value to the "data_relationship_type" field.
func (_u *CoreDataRelationshipUpdateOne) AddDataRelationshipType(v common.DataRelationshipType) *CoreDataRelationshipUpdateOne {
	_u.mutation.AddDataRelationshipType(v)
	return _u
}

// ClearDataRelationshipType clears the value of the "data_relationship_type" field.
func (_u *CoreDataRelationshipUpdateOne) ClearDataRelationshipType() *CoreDataRelationshipUpdateOne {
	_u.mutation.ClearDataRelationshipType()
	return _u
}

// SetMenuID sets the "menu_id" field.
func (_u *CoreDataRelationshipUpdateOne) SetMenuID(v string) *CoreDataRelationshipUpdateOne {
	_u.mutation.SetMenuID(v)
	return _u
}

// SetNillableMenuID sets the "menu_id" field if the given value is not nil.
func (_u *CoreDataRelationshipUpdateOne) SetNillableMenuID(v *string) *CoreDataRelationshipUpdateOne {
	if v != nil {
		_u.SetMenuID(*v)
	}
	return _u
}

// ClearMenuID clears the value of the "menu_id" field.
func (_u *CoreDataRelationshipUpdateOne) ClearMenuID() *CoreDataRelationshipUpdateOne {
	_u.mutation.ClearMenuID()
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *CoreDataRelationshipUpdateOne) SetRoleID(v string) *CoreDataRelationshipUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *CoreDataRelationshipUpdateOne) SetNillableRoleID(v *string) *CoreDataRelationshipUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// ClearRoleID clears the value of the "role_id" field.
func (_u *CoreDataRelationshipUpdateOne) ClearRoleID() *CoreDataRelationshipUpdateOne {
	_u.mutation.ClearRoleID()
	return _u
}

// AddMenuIDs adds the "menu" edge to the CoreMenu entity by IDs.
func (_u *CoreDataRelationshipUpdateOne) AddMenuIDs(ids ...string) *CoreDataRelationshipUpdateOne {
	_u.mutation.AddMenuIDs(ids...)
	return _u
}

// AddMenu adds the "menu" edges to the CoreMenu entity.
func (_u *CoreDataRelationshipUpdateOne) AddMenu(v ...*CoreMenu) *CoreDataRelationshipUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMenuIDs(ids...)
}

// AddRoleIDs adds the "role" edge to the CoreRole entity by IDs.
func (_u *CoreDataRelationshipUpdateOne) AddRoleIDs(ids ...string) *CoreDataRelationshipUpdateOne {
	_u.mutation.AddRoleIDs(ids...)
	return _u
}

// AddRole adds the "role" edges to the CoreRole entity.
func (_u *CoreDataRelationshipUpdateOne) AddRole(v ...*CoreRole) *CoreDataRelationshipUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleIDs(ids...)
}

// Mutation returns the CoreDataRelationshipMutation object of the builder.
func (_u *CoreDataRelationshipUpdateOne) Mutation() *CoreDataRelationshipMutation {
	return _u.mutation
}

// ClearMenu clears all "menu" edges to the CoreMenu entity.
func (_u *CoreDataRelationshipUpdateOne) ClearMenu() *CoreDataRelationshipUpdateOne {
	_u.mutation.ClearMenu()
	return _u
}

// RemoveMenuIDs removes the "menu" edge to CoreMenu entities by IDs.
func (_u *CoreDataRelationshipUpdateOne) RemoveMenuIDs(ids ...string) *CoreDataRelationshipUpdateOne {
	_u.mutation.RemoveMenuIDs(ids...)
	return _u
}

// RemoveMenu removes "menu" edges to CoreMenu entities.
func (_u *CoreDataRelationshipUpdateOne) RemoveMenu(v ...*CoreMenu) *CoreDataRelationshipUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMenuIDs(ids...)
}

// ClearRole clears all "role" edges to the CoreRole entity.
func (_u *CoreDataRelationshipUpdateOne) ClearRole() *CoreDataRelationshipUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// RemoveRoleIDs removes the "role" edge to CoreRole entities by IDs.
func (_u *CoreDataRelationshipUpdateOne) RemoveRoleIDs(ids ...string) *CoreDataRelationshipUpdateOne {
	_u.mutation.RemoveRoleIDs(ids...)
	return _u
}

// RemoveRole removes "role" edges to CoreRole entities.
func (_u *CoreDataRelationshipUpdateOne) RemoveRole(v ...*CoreRole) *CoreDataRelationshipUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleIDs(ids...)
}

// Where appends a list predicates to the CoreDataRelationshipUpdate builder.
func (_u *CoreDataRelationshipUpdateOne) Where(ps ...predicate.CoreDataRelationship) *CoreDataRelationshipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CoreDataRelationshipUpdateOne) Select(field string, fields ...string) *CoreDataRelationshipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CoreDataRelationship entity.
func (_u *CoreDataRelationshipUpdateOne) Save(ctx context.Context) (*CoreDataRelationship, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CoreDataRelationshipUpdateOne) SaveX(ctx context.Context) *CoreDataRelationship {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CoreDataRelationshipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CoreDataRelationshipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CoreDataRelationshipUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if coredatarelationship.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized coredatarelationship.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := coredatarelationship.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CoreDataRelationshipUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CoreDataRelationshipUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CoreDataRelationshipUpdateOne) sqlSave(ctx context.Context) (_node *CoreDataRelationship, err error) {
	_spec := sqlgraph.NewUpdateSpec(coredatarelationship.Table, coredatarelationship.Columns, sqlgraph.NewFieldSpec(coredatarelationship.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CoreDataRelationship.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coredatarelationship.FieldID)
		for _, f := range fields {
			if !coredatarelationship.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != coredatarelationship.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(coredatarelationship.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(coredatarelationship.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(coredatarelationship.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DataRelationshipType(); ok {
		_spec.SetField(coredatarelationship.FieldDataRelationshipType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedDataRelationshipType(); ok {
		_spec.AddField(coredatarelationship.FieldDataRelationshipType, field.TypeInt8, value)
	}
	if _u.mutation.DataRelationshipTypeCleared() {
		_spec.ClearField(coredatarelationship.FieldDataRelationshipType, field.TypeInt8)
	}
	if value, ok := _u.mutation.MenuID(); ok {
		_spec.SetField(coredatarelationship.FieldMenuID, field.TypeString, value)
	}
	if _u.mutation.MenuIDCleared() {
		_spec.ClearField(coredatarelationship.FieldMenuID, field.TypeString)
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(coredatarelationship.FieldRoleID, field.TypeString, value)
	}
	if _u.mutation.RoleIDCleared() {
		_spec.ClearField(coredatarelationship.FieldRoleID, field.TypeString)
	}
	if _u.mutation.MenuCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   coredatarelationship.MenuTable,
			Columns: coredatarelationship.MenuPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coremenu.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMenuIDs(); len(nodes) > 0 && !_u.mutation.MenuCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   coredatarelationship.MenuTable,
			Columns: coredatarelationship.MenuPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coremenu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   coredatarelationship.MenuTable,
			Columns: coredatarelationship.MenuPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coremenu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   coredatarelationship.RoleTable,
			Columns: coredatarelationship.RolePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(corerole.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoleIDs(); len(nodes) > 0 && !_u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   coredatarelationship.RoleTable,
			Columns: coredatarelationship.RolePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(corerole.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   coredatarelationship.RoleTable,
			Columns: coredatarelationship.RolePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(corerole.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &CoreDataRelationship{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coredatarelationship.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
