// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coreupstreamhost"
	"github.com/lyonmu/quebec/pkg/constant"
)

// 上游服务后端地址表
type CoreUpstreamHost struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID string `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 后端地址IP
	Address string `json:"address,omitempty"`
	// 权重(相对权重)
	Weight int `json:"weight,omitempty"`
	// 后端端口
	Port int `json:"port,omitempty"`
	// 是否可用 [1: 是, 2: 否]
	Enabled      constant.YesOrNo `json:"enabled,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CoreUpstreamHost) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case coreupstreamhost.FieldWeight, coreupstreamhost.FieldPort, coreupstreamhost.FieldEnabled:
			values[i] = new(sql.NullInt64)
		case coreupstreamhost.FieldID, coreupstreamhost.FieldAddress:
			values[i] = new(sql.NullString)
		case coreupstreamhost.FieldCreatedAt, coreupstreamhost.FieldUpdatedAt, coreupstreamhost.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CoreUpstreamHost fields.
func (_m *CoreUpstreamHost) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case coreupstreamhost.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case coreupstreamhost.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case coreupstreamhost.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case coreupstreamhost.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case coreupstreamhost.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case coreupstreamhost.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = int(value.Int64)
			}
		case coreupstreamhost.FieldPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port", values[i])
			} else if value.Valid {
				_m.Port = int(value.Int64)
			}
		case coreupstreamhost.FieldEnabled:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = constant.YesOrNo(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CoreUpstreamHost.
// This includes values selected through modifiers, order, etc.
func (_m *CoreUpstreamHost) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CoreUpstreamHost.
// Note that you need to call CoreUpstreamHost.Unwrap() before calling this method if this CoreUpstreamHost
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CoreUpstreamHost) Update() *CoreUpstreamHostUpdateOne {
	return NewCoreUpstreamHostClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CoreUpstreamHost entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CoreUpstreamHost) Unwrap() *CoreUpstreamHost {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CoreUpstreamHost is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CoreUpstreamHost) String() string {
	var builder strings.Builder
	builder.WriteString("CoreUpstreamHost(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("port=")
	builder.WriteString(fmt.Sprintf("%v", _m.Port))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// CoreUpstreamHosts is a parsable slice of CoreUpstreamHost.
type CoreUpstreamHosts []*CoreUpstreamHost
