// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lyonmu/quebec/cmd/core/internal/ent/coregatewayhttproute"
	"github.com/lyonmu/quebec/pkg/constant"
)

// L7 HTTP路由规则表
type CoreGatewayHttpRoute struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID string `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 路由名称
	Name string `json:"name,omitempty"`
	// 路由描述
	Description string `json:"description,omitempty"`
	// 匹配类型: 1-前缀 2-精确 3-正则
	MatchType constant.ProxyHttpRouteMatchType `json:"match_type,omitempty"`
	// 匹配规则，如 /api/v1/*
	MatchPattern string `json:"match_pattern,omitempty"`
	// 路由超时(毫秒，默认15000=15秒)，包括所有重试
	TimeoutMs int `json:"timeout_ms,omitempty"`
	// 是否启用路径重写 [1-启用 2-禁用]
	EnablePathRewrite constant.YesOrNo `json:"enable_path_rewrite,omitempty"`
	// 路径重写规则，如 /api/v1/* /v1/*
	PathRewrite string `json:"path_rewrite,omitempty"`
	// 是否启用重定向 [1-启用 2-禁用]
	EnableRedirect constant.YesOrNo `json:"enable_redirect,omitempty"`
	// 重定向URL
	RedirectURL string `json:"redirect_url,omitempty"`
	// 重定向状态码
	RedirectCode int `json:"redirect_code,omitempty"`
	// 状态  [1-启用 2-禁用]
	Status       constant.YesOrNo `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CoreGatewayHttpRoute) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case coregatewayhttproute.FieldMatchType, coregatewayhttproute.FieldTimeoutMs, coregatewayhttproute.FieldEnablePathRewrite, coregatewayhttproute.FieldEnableRedirect, coregatewayhttproute.FieldRedirectCode, coregatewayhttproute.FieldStatus:
			values[i] = new(sql.NullInt64)
		case coregatewayhttproute.FieldID, coregatewayhttproute.FieldName, coregatewayhttproute.FieldDescription, coregatewayhttproute.FieldMatchPattern, coregatewayhttproute.FieldPathRewrite, coregatewayhttproute.FieldRedirectURL:
			values[i] = new(sql.NullString)
		case coregatewayhttproute.FieldCreatedAt, coregatewayhttproute.FieldUpdatedAt, coregatewayhttproute.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CoreGatewayHttpRoute fields.
func (_m *CoreGatewayHttpRoute) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case coregatewayhttproute.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case coregatewayhttproute.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case coregatewayhttproute.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case coregatewayhttproute.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case coregatewayhttproute.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case coregatewayhttproute.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case coregatewayhttproute.FieldMatchType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field match_type", values[i])
			} else if value.Valid {
				_m.MatchType = constant.ProxyHttpRouteMatchType(value.Int64)
			}
		case coregatewayhttproute.FieldMatchPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field match_pattern", values[i])
			} else if value.Valid {
				_m.MatchPattern = value.String
			}
		case coregatewayhttproute.FieldTimeoutMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field timeout_ms", values[i])
			} else if value.Valid {
				_m.TimeoutMs = int(value.Int64)
			}
		case coregatewayhttproute.FieldEnablePathRewrite:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field enable_path_rewrite", values[i])
			} else if value.Valid {
				_m.EnablePathRewrite = constant.YesOrNo(value.Int64)
			}
		case coregatewayhttproute.FieldPathRewrite:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path_rewrite", values[i])
			} else if value.Valid {
				_m.PathRewrite = value.String
			}
		case coregatewayhttproute.FieldEnableRedirect:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field enable_redirect", values[i])
			} else if value.Valid {
				_m.EnableRedirect = constant.YesOrNo(value.Int64)
			}
		case coregatewayhttproute.FieldRedirectURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field redirect_url", values[i])
			} else if value.Valid {
				_m.RedirectURL = value.String
			}
		case coregatewayhttproute.FieldRedirectCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field redirect_code", values[i])
			} else if value.Valid {
				_m.RedirectCode = int(value.Int64)
			}
		case coregatewayhttproute.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = constant.YesOrNo(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CoreGatewayHttpRoute.
// This includes values selected through modifiers, order, etc.
func (_m *CoreGatewayHttpRoute) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CoreGatewayHttpRoute.
// Note that you need to call CoreGatewayHttpRoute.Unwrap() before calling this method if this CoreGatewayHttpRoute
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CoreGatewayHttpRoute) Update() *CoreGatewayHttpRouteUpdateOne {
	return NewCoreGatewayHttpRouteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CoreGatewayHttpRoute entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CoreGatewayHttpRoute) Unwrap() *CoreGatewayHttpRoute {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CoreGatewayHttpRoute is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CoreGatewayHttpRoute) String() string {
	var builder strings.Builder
	builder.WriteString("CoreGatewayHttpRoute(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("match_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.MatchType))
	builder.WriteString(", ")
	builder.WriteString("match_pattern=")
	builder.WriteString(_m.MatchPattern)
	builder.WriteString(", ")
	builder.WriteString("timeout_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.TimeoutMs))
	builder.WriteString(", ")
	builder.WriteString("enable_path_rewrite=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnablePathRewrite))
	builder.WriteString(", ")
	builder.WriteString("path_rewrite=")
	builder.WriteString(_m.PathRewrite)
	builder.WriteString(", ")
	builder.WriteString("enable_redirect=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnableRedirect))
	builder.WriteString(", ")
	builder.WriteString("redirect_url=")
	builder.WriteString(_m.RedirectURL)
	builder.WriteString(", ")
	builder.WriteString("redirect_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.RedirectCode))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// CoreGatewayHttpRoutes is a parsable slice of CoreGatewayHttpRoute.
type CoreGatewayHttpRoutes []*CoreGatewayHttpRoute
