services:
  quebec-envoy:
    image: bitnami/envoy:latest
    restart: unless-stopped
    pull_policy: always
    container_name: quebec-envoy
    hostname: quebec-envoy
    ports: ["30811:30811","38080:38080"]
    volumes: ["./envoy.yaml:/opt/bitnami/envoy/conf/envoy.yaml","./log/envoy:/var/log/envoy"]
    networks: ["quebec-component"]

  quebec-redis:
    restart: unless-stopped
    image: redis:alpine
    pull_policy: always
    container_name: quebec-redis
    hostname: quebec-redis
    environment: {REDIS_PASSWORD: "root"}
    ports: ["36379:6379"]
    command: ["redis-server", "--requirepass","root","--notify-keyspace-events", "AKE"]
    volumes: ["./data/redis:/data"]
    networks: ["quebec-component"]

  quebec-prometheus:
    restart: unless-stopped
    image: bitnami/prometheus:latest
    pull_policy: always
    container_name: quebec-prometheus
    hostname: quebec-prometheus
    ports: ["39090:9090"]
    command: ["--web.enable-lifecycle"]
    volumes: ["./data/prometheus:/opt/bitnami/prometheus/data","./prometheus.yml:/opt/bitnami/prometheus/prometheus.yml"]
    networks: ["quebec-component"]

  quebec-node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    pull_policy: always
    container_name: quebec-node-exporter
    hostname: quebec-node-exporter
    command: ["--web.listen-address=:39100","--path.rootfs=/host"]
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes: ["/:/host:ro,rslave"]

  quebec-redis-exporter:
    restart: unless-stopped
    image: quay.io/oliver006/redis_exporter
    pull_policy: always
    container_name: quebec-redis-exporter
    hostname: quebec-redis-exporter
    ports: ["39121:9121"]
    networks: ["quebec-component"]
    environment: {REDIS_ADDR: "redis://quebec-redis:6379",REDIS_PASSWORD: root}

  quebec-grafana:
    restart: unless-stopped
    image: grafana/grafana:latest
    pull_policy: always
    container_name: quebec-grafana
    hostname: quebec-grafana
    volumes: ["./data/grafana:/var/lib/grafana"]
    ports: ["33000:3000"]
    environment: {GF_LOG_LEVEL: "debug",GF_INSTALL_PLUGINS: "grafana-clock-panel"}
    networks: ["quebec-component"]
  
  quebec-mysql:
    restart: unless-stopped
    pull_policy: always
    image: bitnami/mysql:latest  
    container_name: quebec-mysql
    hostname: quebec-mysql
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - quebec-component

  quebec-mysqld-exporter:
    restart: unless-stopped
    pull_policy: always
    image: prom/mysqld-exporter:latest 
    container_name: quebec-mysqld-exporter
    hostname: quebec-mysqld-exporter
    ports:
      - "39104:9104"
    environment:
      MYSQLD_EXPORTER_PASSWORD: root
    command: ["--mysqld.address=quebec-mysql:3306","--mysqld.username=root"]
    networks:
      - quebec-component

networks:
  quebec-component:
    name: quebec-component
    driver: bridge
    ipam:
      driver: default
      config: [{subnet: 118.249.10.0/24,gateway: 118.249.10.1}]
