global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'auth-prometheus'

scrape_configs:

  - job_name: "auth-prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "auth-envoy"
    metrics_path: "/stats/prometheus"
    static_configs:
      - targets: ["auth-envoy:30811"]

  - job_name: "auth-redis_exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets: [ "auth-redis_exporter:9121" ]

  - job_name: "auth-node"
    metrics_path: "/metrics"
    static_configs:
      - targets: [ "172.17.0.1:39100" ]