global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'quebec-prometheus'

scrape_configs:

  - job_name: "quebec-prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "quebec-envoy"
    metrics_path: "/stats/prometheus"
    static_configs:
      - targets: ["quebec-envoy:30811"]

  - job_name: "quebec-redis-exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets: [ "quebec-redis-exporter:9121" ]

  - job_name: "quebec-node-exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets: [ "host.docker.internal:39100" ]
  
  - job_name: "quebec-mysqld-exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets: [ "quebec-mysqld-exporter:9104" ]