// Code generated by ent, DO NOT EDIT.

package coregatewayhttproute

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lyonmu/quebec/pkg/constant"
)

const (
	// Label holds the string label denoting the coregatewayhttproute type in the database.
	Label = "core_gateway_http_route"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldMatchType holds the string denoting the match_type field in the database.
	FieldMatchType = "match_type"
	// FieldMatchPattern holds the string denoting the match_pattern field in the database.
	FieldMatchPattern = "match_pattern"
	// FieldTimeoutMs holds the string denoting the timeout_ms field in the database.
	FieldTimeoutMs = "timeout_ms"
	// FieldEnablePathRewrite holds the string denoting the enable_path_rewrite field in the database.
	FieldEnablePathRewrite = "enable_path_rewrite"
	// FieldPathRewrite holds the string denoting the path_rewrite field in the database.
	FieldPathRewrite = "path_rewrite"
	// FieldEnableRedirect holds the string denoting the enable_redirect field in the database.
	FieldEnableRedirect = "enable_redirect"
	// FieldRedirectURL holds the string denoting the redirect_url field in the database.
	FieldRedirectURL = "redirect_url"
	// FieldRedirectCode holds the string denoting the redirect_code field in the database.
	FieldRedirectCode = "redirect_code"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the coregatewayhttproute in the database.
	Table = "quebec_core_gateway_http_route"
)

// Columns holds all SQL columns for coregatewayhttproute fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldDescription,
	FieldMatchType,
	FieldMatchPattern,
	FieldTimeoutMs,
	FieldEnablePathRewrite,
	FieldPathRewrite,
	FieldEnableRedirect,
	FieldRedirectURL,
	FieldRedirectCode,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/lyonmu/quebec/cmd/core/internal/ent/runtime"
var (
	Hooks [2]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultMatchType holds the default value on creation for the "match_type" field.
	DefaultMatchType constant.ProxyHttpRouteMatchType
	// DefaultTimeoutMs holds the default value on creation for the "timeout_ms" field.
	DefaultTimeoutMs int
	// DefaultEnablePathRewrite holds the default value on creation for the "enable_path_rewrite" field.
	DefaultEnablePathRewrite constant.YesOrNo
	// DefaultEnableRedirect holds the default value on creation for the "enable_redirect" field.
	DefaultEnableRedirect constant.YesOrNo
	// DefaultRedirectCode holds the default value on creation for the "redirect_code" field.
	DefaultRedirectCode int
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus constant.YesOrNo
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the CoreGatewayHttpRoute queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByMatchType orders the results by the match_type field.
func ByMatchType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchType, opts...).ToFunc()
}

// ByMatchPattern orders the results by the match_pattern field.
func ByMatchPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchPattern, opts...).ToFunc()
}

// ByTimeoutMs orders the results by the timeout_ms field.
func ByTimeoutMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeoutMs, opts...).ToFunc()
}

// ByEnablePathRewrite orders the results by the enable_path_rewrite field.
func ByEnablePathRewrite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnablePathRewrite, opts...).ToFunc()
}

// ByPathRewrite orders the results by the path_rewrite field.
func ByPathRewrite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPathRewrite, opts...).ToFunc()
}

// ByEnableRedirect orders the results by the enable_redirect field.
func ByEnableRedirect(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnableRedirect, opts...).ToFunc()
}

// ByRedirectURL orders the results by the redirect_url field.
func ByRedirectURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedirectURL, opts...).ToFunc()
}

// ByRedirectCode orders the results by the redirect_code field.
func ByRedirectCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedirectCode, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}
